//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:		 BSD License
//					 Kratos default license: kratos/license.txt
//
//  Main authors:    @{KRATOS_APP_AUTHOR}
//

#if !defined(KRATOS_STATISTICS_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_STATISTICS_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "includes/kratos_application.h"
#include "containers/variable.h"

namespace Kratos
{
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(STATISTICS_APPLICATION, VELOCITY_SUM )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(STATISTICS_APPLICATION, VELOCITY_MEAN )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(STATISTICS_APPLICATION, VELOCITY_VARIANCE )

KRATOS_DEFINE_APPLICATION_VARIABLE(STATISTICS_APPLICATION, double, VELOCITY_NORM )
KRATOS_DEFINE_APPLICATION_VARIABLE(STATISTICS_APPLICATION,  double, PRESSURE_NORM )
KRATOS_DEFINE_APPLICATION_VARIABLE(STATISTICS_APPLICATION,  double, PRESSURE_SUM )
KRATOS_DEFINE_APPLICATION_VARIABLE(STATISTICS_APPLICATION,  double, PRESSURE_MEAN )
KRATOS_DEFINE_APPLICATION_VARIABLE(STATISTICS_APPLICATION,  double, PRESSURE_VARIANCE )

}

#endif	/* KRATOS_STATISTICS_APPLICATION_VARIABLES_H_INCLUDED */
