//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Reza Najian Asl
//

#include "shape_optimization_application_variables.h"

namespace Kratos
{
    typedef array_1d<double, 3> Vector3;
   // Geometry variables
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(NORMALIZED_SURFACE_NORMAL);

    // Optimization variables
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DF1DX);

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DF1DX_MAPPED);

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC1DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC2DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC3DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC4DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC5DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC6DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC7DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC8DX);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC9DX);

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC1DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC2DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC3DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC4DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC5DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC6DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC7DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC8DX_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DC9DX_MAPPED);

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SEARCH_DIRECTION);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CORRECTION);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CONTROL_POINT_UPDATE);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CONTROL_POINT_CHANGE);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SHAPE_UPDATE);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SHAPE_CHANGE);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MESH_CHANGE);

    // For edge damping
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DAMPING_FACTOR);

    // For Mapping
    KRATOS_CREATE_VARIABLE(int,MAPPING_ID);

    // For bead optimization
    KRATOS_CREATE_VARIABLE(double,ALPHA);
    KRATOS_CREATE_VARIABLE(double,ALPHA_MAPPED);
    KRATOS_CREATE_VARIABLE(double,DF1DALPHA);
    KRATOS_CREATE_VARIABLE(double,DF1DALPHA_MAPPED);
    KRATOS_CREATE_VARIABLE(double,DPDALPHA);
    KRATOS_CREATE_VARIABLE(double,DPDALPHA_MAPPED);
    KRATOS_CREATE_VARIABLE(double,DLDALPHA);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(BEAD_DIRECTION);

    // For auxiliary operations
    KRATOS_CREATE_VARIABLE(double,SCALAR_VARIABLE);
    KRATOS_CREATE_VARIABLE(double,SCALAR_VARIABLE_MAPPED);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VECTOR_VARIABLE);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VECTOR_VARIABLE_MAPPED);

    // For in plane mapping operations
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(BACKGROUND_COORDINATE);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(BACKGROUND_NORMAL);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(OUT_OF_PLANE_DELTA);

    // For implicit vertex-morphing with Helmholtz PDE
    KRATOS_CREATE_VARIABLE(Matrix, HELMHOLTZ_MASS_MATRIX);
    KRATOS_CREATE_VARIABLE( int,HELMHOLTZ_DIRECTION);
    KRATOS_CREATE_VARIABLE( bool,COMPUTE_CONTROL_POINTS);
    KRATOS_CREATE_VARIABLE( double,HELMHOLTZ_POISSON_RATIO);
    KRATOS_CREATE_VARIABLE( double,HELMHOLTZ_RADIUS);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(HELMHOLTZ_VARS);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(HELMHOLTZ_SOURCE);

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(HELMHOLTZ_ROTS);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(HELMHOLTZ_ROTS_SOURCE);

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CONTROL_POINT);
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CONTROL_CURV);    
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SHAPE);

   // For min-max angles constraints in additive manufacturing 
    KRATOS_CREATE_VARIABLE(double,NODAL_MIN_ANGLE);
    KRATOS_CREATE_VARIABLE(double,NODAL_MAX_ANGLE); 

   // For thickness response
    KRATOS_CREATE_VARIABLE(double,NODAL_THICKNESS); 

    // Shape Shell generalized variables
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SHAPE_LOCAL_MATERIAL_AXIS_1)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SHAPE_LOCAL_MATERIAL_AXIS_2)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SHAPE_LOCAL_MATERIAL_AXIS_3)
    KRATOS_CREATE_VARIABLE( double, SHAPE_MATERIAL_ORIENTATION_ANGLE)
    KRATOS_CREATE_VARIABLE( Matrix, SHAPE_LOCAL_ELEMENT_ORIENTATION)


    KRATOS_CREATE_VARIABLE(double, SHAPE_MASS_FACTOR)
    KRATOS_CREATE_VARIABLE(double, SHAPE_RAYLEIGH_BETA)
    KRATOS_CREATE_VARIABLE(double, SHAPE_RAYLEIGH_ALPHA)
    KRATOS_CREATE_VARIABLE(bool, SHAPE_STENBERG_SHEAR_STABILIZATION_SUITABLE)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_OFFSET)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRAIN)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRAIN_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_CURVATURE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_CURVATURE_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_FORCE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_FORCE_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_MOMENT)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_MOMENT_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRESS_TOP_SURFACE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRESS_TOP_SURFACE_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRESS_MIDDLE_SURFACE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRESS_MIDDLE_SURFACE_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRESS_BOTTOM_SURFACE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_STRESS_BOTTOM_SURFACE_GLOBAL)
    KRATOS_CREATE_VARIABLE(double, SHAPE_VON_MISES_STRESS_TOP_SURFACE)
    KRATOS_CREATE_VARIABLE(double, SHAPE_VON_MISES_STRESS)
    KRATOS_CREATE_VARIABLE(double, SHAPE_VON_MISES_STRESS_MIDDLE_SURFACE)
    KRATOS_CREATE_VARIABLE(double, SHAPE_VON_MISES_STRESS_BOTTOM_SURFACE)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHEAR_ANGLE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_ORTHOTROPIC_STRESS_BOTTOM_SURFACE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_ORTHOTROPIC_STRESS_TOP_SURFACE)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_ORTHOTROPIC_STRESS_BOTTOM_SURFACE_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_ORTHOTROPIC_STRESS_TOP_SURFACE_GLOBAL)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_ORTHOTROPIC_4PLY_THROUGH_THICKNESS)
    KRATOS_CREATE_VARIABLE(double, SHAPE_TSAI_WU_RESERVE_FACTOR)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_ORTHOTROPIC_LAMINA_STRENGTHS)

    // ENERGY
    KRATOS_CREATE_VARIABLE(double, SHAPE_ENERGY_DAMPING_DISSIPATION)

    // Shell energies
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_ELEMENT_MEMBRANE_ENERGY)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_ELEMENT_BENDING_ENERGY)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_ELEMENT_SHEAR_ENERGY)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_ELEMENT_MEMBRANE_ENERGY_FRACTION)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_ELEMENT_BENDING_ENERGY_FRACTION)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_ELEMENT_SHEAR_ENERGY_FRACTION)    

    // Cross section
    KRATOS_CREATE_VARIABLE(int, SHAPE_SHELL_CROSS_SECTION_OUTPUT_PLY_ID)
    KRATOS_CREATE_VARIABLE(double, SHAPE_SHELL_CROSS_SECTION_OUTPUT_PLY_LOCATION)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_SHELL_ORTHOTROPIC_LAYERS)   

}
