//
//   Project Name:        KratosSolidMechanicsApplication $
//   Created by:          $Author:            JMCarbonell $
//   Last modified by:    $Co-Author:                     $
//   Date:                $Date:            February 2016 $
//   Revision:            $Revision:                  0.0 $
//
//

#include "solid_mechanics_application_variables.h"

namespace Kratos
{
  ///@name Type Definitions
  ///@{
  typedef array_1d<double,3> Vector3;
  typedef array_1d<double,6> Vector6;
  ///@}

  ///@name Kratos Globals
  ///@{

  //Create Variables

  //explicit schemes
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MIDDLE_VELOCITY )

  //solution
  KRATOS_CREATE_VARIABLE( int, WRITE_ID )
  KRATOS_CREATE_VARIABLE( double, PREVIOUS_DELTA_TIME )
  KRATOS_CREATE_VARIABLE( double, RAYLEIGH_ALPHA )
  KRATOS_CREATE_VARIABLE( double, RAYLEIGH_BETA )

  //constitutive law
  KRATOS_CREATE_VARIABLE( bool, IMPLEX )
  KRATOS_CREATE_VARIABLE( std::string, CONSTITUTIVE_LAW_NAME )


  //nodal load variables
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( POINT_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( LINE_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( SURFACE_LOAD )
  
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FOLLOWER_POINT_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FOLLOWER_LINE_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FOLLOWER_SURFACE_LOAD )
  
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( POINT_MOMENT )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FOLLOWER_POINT_MOMENT )
  
  //condition load variables
  KRATOS_CREATE_VARIABLE( Vector, POINT_LOADS_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, LINE_LOADS_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, SURFACE_LOADS_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, POSITIVE_FACE_PRESSURES_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, NEGATIVE_FACE_PRESSURES_VECTOR )
  
  //material orientation
  KRATOS_CREATE_VARIABLE( Vector3, MATERIAL_ORIENTATION_DX )
  KRATOS_CREATE_VARIABLE( Vector3, MATERIAL_ORIENTATION_DY )
  KRATOS_CREATE_VARIABLE( Vector3, MATERIAL_ORIENTATION_DZ )

  //othotropic/anisotropic constants
  KRATOS_CREATE_VARIABLE( double, YOUNG_MODULUS_X )
  KRATOS_CREATE_VARIABLE( double, YOUNG_MODULUS_Y )
  KRATOS_CREATE_VARIABLE( double, YOUNG_MODULUS_Z )
  KRATOS_CREATE_VARIABLE( double, SHEAR_MODULUS_XY )
  KRATOS_CREATE_VARIABLE( double, SHEAR_MODULUS_YZ )
  KRATOS_CREATE_VARIABLE( double, SHEAR_MODULUS_XZ )
  KRATOS_CREATE_VARIABLE( double, POISSON_RATIO_XY )
  KRATOS_CREATE_VARIABLE( double, POISSON_RATIO_YZ )
  KRATOS_CREATE_VARIABLE( double, POISSON_RATIO_XZ )

  //material : hyperelastic_plastic
  KRATOS_CREATE_VARIABLE( double, NORM_ISOCHORIC_STRESS )
  KRATOS_CREATE_VARIABLE( double, PLASTIC_STRAIN )
  KRATOS_CREATE_VARIABLE( double, DELTA_PLASTIC_STRAIN )
  KRATOS_CREATE_VARIABLE( double, ISOTROPIC_HARDENING_MODULUS )
  KRATOS_CREATE_VARIABLE( double, KINEMATIC_HARDENING_MODULUS )

  KRATOS_CREATE_VARIABLE( double, HARDENING_EXPONENT )
  KRATOS_CREATE_VARIABLE( double, REFERENCE_HARDENING_MODULUS )
  KRATOS_CREATE_VARIABLE( double, INFINITY_HARDENING_MODULUS )

  //material : isotropic damage
  KRATOS_CREATE_VARIABLE( double, DAMAGE_VARIABLE )
  KRATOS_CREATE_VARIABLE( double, DAMAGE_THRESHOLD )
  KRATOS_CREATE_VARIABLE( double, STRENGTH_RATIO )
  KRATOS_CREATE_VARIABLE( double, FRACTURE_ENERGY )
  KRATOS_CREATE_VARIABLE( double, RESIDUAL_STRENGTH )
  KRATOS_CREATE_VARIABLE( double, SOFTENING_SLOPE )

  //thermal
  //KRATOS_CREATE_VARIABLE( double, THERMAL_EXPANSION_COEFFICIENT )
  KRATOS_CREATE_VARIABLE( double, REFERENCE_TEMPERATURE )
  KRATOS_CREATE_VARIABLE( double, PLASTIC_DISSIPATION)
  KRATOS_CREATE_VARIABLE( double, DELTA_PLASTIC_DISSIPATION)

  //element
  KRATOS_CREATE_VARIABLE( Matrix, ALMANSI_STRAIN_TENSOR )
  KRATOS_CREATE_VARIABLE( Vector, GREEN_LAGRANGE_STRAIN_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, ALMANSI_STRAIN_VECTOR )

  //KRATOS_CREATE_VARIABLE( Matrix, MATERIAL_STIFFNESS_MATRIX )
  //KRATOS_CREATE_VARIABLE( Matrix, GEOMETRIC_STIFFNESS_MATRIX )

  KRATOS_CREATE_VARIABLE( double, VON_MISES_STRESS )

  //nodal dofs
  KRATOS_CREATE_VARIABLE( double, PRESSURE_REACTION )


  ///@}

}
