//
//   Project Name:        KratosSolidMechanicsApplication $
//   Created by:          $Author:            JMCarbonell $
//   Last modified by:    $Co-Author:                     $
//   Date:                $Date:            February 2016 $
//   Revision:            $Revision:                  0.0 $
//
//

#include "solid_mechanics_application_variables.h"

namespace Kratos
{
  ///@name Type Definitions
  ///@{
  typedef array_1d<double,3> Vector3;
  typedef array_1d<double,6> Vector6;
  typedef VariableComponent< VectorComponentAdaptor< array_1d<double, 3 > > >   VariableComponentType;
  typedef TimeIntegrationMethod<VariableComponentType, double>     TimeIntegrationMethodComponentType;
  ///@}

  ///@name Kratos Globals
  ///@{

  //Create Variables

  // Generalized eigenvalue problem
  KRATOS_CREATE_VARIABLE( int, BUILD_LEVEL )
  KRATOS_CREATE_VARIABLE( Vector, EIGENVALUE_VECTOR)
  KRATOS_CREATE_VARIABLE( Matrix , EIGENVECTOR_MATRIX )

  //explicit schemes
  KRATOS_CREATE_VARIABLE( TimeIntegrationMethodComponentType::Pointer, TIME_INTEGRATION_METHOD )
  KRATOS_CREATE_VARIABLE( TimeIntegrationMethodComponentType::Pointer, ANGULAR_TIME_INTEGRATION_METHOD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MIDDLE_VELOCITY )

  //solution
  KRATOS_CREATE_VARIABLE( int, WRITE_ID )
  KRATOS_CREATE_VARIABLE( double, RAYLEIGH_ALPHA )
  KRATOS_CREATE_VARIABLE( double, RAYLEIGH_BETA )
  
  //geometrical
  KRATOS_CREATE_VARIABLE( Matrix ,GEOMETRIC_STIFFNESS )

  //beam cross section
  //KRATOS_CREATE_VARIABLE( BeamCrossSection::Pointer, BEAM_CROSS_SECTION )
  KRATOS_CREATE_VARIABLE( double, CROSS_SECTION_AREA )
  KRATOS_CREATE_VARIABLE( double, CROSS_SECTION_RADIUS )  
  KRATOS_CREATE_VARIABLE( int,    CROSS_SECTION_SIDES )
  
  //shell cross section
  KRATOS_CREATE_VARIABLE( ShellCrossSection::Pointer, SHELL_CROSS_SECTION )
  KRATOS_CREATE_VARIABLE( int, SHELL_CROSS_SECTION_OUTPUT_PLY_ID )
  KRATOS_CREATE_VARIABLE( double, SHELL_CROSS_SECTION_OUTPUT_PLY_LOCATION )

  //shell generalized variables
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_STRAIN )
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_STRAIN_GLOBAL )
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_CURVATURE )
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_CURVATURE_GLOBAL )
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_FORCE )
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_FORCE_GLOBAL )
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_MOMENT )
  KRATOS_CREATE_VARIABLE( Matrix, SHELL_MOMENT_GLOBAL )
  
  //nodal load variables
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( POINT_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( LINE_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( SURFACE_LOAD )

  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FOLLOWER_POINT_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FOLLOWER_LINE_LOAD )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FOLLOWER_SURFACE_LOAD )
  
  //nodal moment variables
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( POINT_MOMENT )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( LINE_MOMENT )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( SURFACE_MOMENT )

  KRATOS_CREATE_VARIABLE( double, PLANE_POINT_MOMENT )
  KRATOS_CREATE_VARIABLE( double, PLANE_LINE_MOMENT )
  KRATOS_CREATE_VARIABLE( double, BALLAST_COEFFICIENT )
  
  //nodal elastic variables
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( POINT_STIFFNESS )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( LINE_STIFFNESS )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( SURFACE_STIFFNESS )
  
  //condition load variables
  KRATOS_CREATE_VARIABLE( Vector, POINT_LOAD_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, LINE_LOAD_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, SURFACE_LOAD_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, POSITIVE_FACE_PRESSURE_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, NEGATIVE_FACE_PRESSURE_VECTOR )

  //condition moment variables
  KRATOS_CREATE_VARIABLE( Vector, POINT_MOMENT_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, LINE_MOMENT_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, SURFACE_MOMENT_VECTOR )
  
  KRATOS_CREATE_VARIABLE( Vector, PLANE_POINT_MOMENT_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, PLANE_LINE_MOMENT_VECTOR )
  
  //condition elastic variables
  KRATOS_CREATE_VARIABLE( Vector, POINT_STIFFNESS_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, LINE_STIFFNESS_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, SURFACE_STIFFNESS_VECTOR )
  KRATOS_CREATE_VARIABLE( Vector, BALLAST_COEFFICIENT_VECTOR )
  
  //element
  KRATOS_CREATE_VARIABLE( double, VON_MISES_STRESS )

  //nodal dofs
  KRATOS_CREATE_VARIABLE( double, PRESSURE_REACTION )
  
  //explicit beam
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( EXTERNAL_MOMENT )

  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( POSITION_MOMENTUM )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_MOMENTUM )  
  
  KRATOS_CREATE_VARIABLE( Matrix, INERTIA_DYADIC )

  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( RESIDUAL_LYAPUNOV )  
  KRATOS_CREATE_VARIABLE( Matrix, TANGENT_MATRIX )
  KRATOS_CREATE_VARIABLE( Matrix, TANGENT_LYAPUNOV )

  KRATOS_CREATE_VARIABLE( double, ALPHA_TRAPEZOIDAL_RULE )
  KRATOS_CREATE_VARIABLE( bool, POSITION_UPDATE_LABEL )
  KRATOS_CREATE_VARIABLE( bool, ROTATION_UPDATE_LABEL )
  KRATOS_CREATE_VARIABLE( bool, MOMENTUM_UPDATE_LABEL )

  //reading beam section properties
  KRATOS_CREATE_VARIABLE( double, SECTION_HEIGHT )
  KRATOS_CREATE_VARIABLE( double, SECTION_WIDTH  )
  KRATOS_CREATE_VARIABLE( double, INERTIA_X )
  KRATOS_CREATE_VARIABLE( double, INERTIA_Y )
  KRATOS_CREATE_VARIABLE( double, SECTION_SIZE )

  KRATOS_CREATE_VARIABLE( double, YOUNGxAREA )
  KRATOS_CREATE_VARIABLE( double, YOUNGxINERTIA_X )
  KRATOS_CREATE_VARIABLE( double, YOUNGxINERTIA_Y )
  KRATOS_CREATE_VARIABLE( double, SHEARxREDUCED_AREA )
  KRATOS_CREATE_VARIABLE( double, SHEARxPOLAR_INERTIA )
  
  ///@}

}
