# This functin installs a symbolic link
macro(install_symlink filepath sympath)
    install(CODE "execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${filepath} ${sympath})")
endmacro(install_symlink)

# This function install a symlinc to an entire directory
macro(kratos_python_install_directory INSTALL_PYTHON_USING_LINKS origin_dir destination_dir)
    install(DIRECTORY DESTINATION ${CMAKE_INSTALL_PREFIX}/${destination_dir})
    file(GLOB SRC_FILES ${origin_dir}/*.py)
    if(${INSTALL_PYTHON_USING_LINKS} MATCHES ON )
        foreach(f ${SRC_FILES})
            message("installing symbolic" ${f})
            get_filename_component(barename ${f} NAME)
            install_symlink(${f} ${CMAKE_INSTALL_PREFIX}/${destination_dir}/${barename} )
        endforeach(f ${SRC_FILES})
    else(${INSTALL_PYTHON_USING_LINKS} MATCHES ON )
        foreach(f ${SRC_FILES})
            #message("installing copy " ${f})
            install(FILES ${f} DESTINATION ${CMAKE_INSTALL_PREFIX}/${destination_dir}/ )
        endforeach(f ${SRC_FILES})
    endif(${INSTALL_PYTHON_USING_LINKS} MATCHES ON )
endmacro(kratos_python_install_directory)

macro(kratos_python_install INSTALL_PYTHON_USING_LINKS origin_file destination_file)
    get_filename_component(destination_dir ${destination_file} DIRECTORY )
    get_filename_component(destination_filename ${destination_file} NAME )
    install(DIRECTORY DESTINATION ${CMAKE_INSTALL_PREFIX}/${destination_dir})
    if(${INSTALL_PYTHON_USING_LINKS} MATCHES ON )
        install_symlink(${origin_file} ${CMAKE_INSTALL_PREFIX}/${destination_file} )
    else(${INSTALL_PYTHON_USING_LINKS} MATCHES ON )
        install(FILES ${origin_file} DESTINATION ${CMAKE_INSTALL_PREFIX}/${destination_dir} RENAME ${destination_filename})
    endif(${INSTALL_PYTHON_USING_LINKS} MATCHES ON )
endmacro(kratos_python_install)
