FROM kratosmultiphysics/kratos-image-ci-ubuntu-bionic

ENV HOME /root

RUN git clone --depth 1 https://github.com/KratosMultiphysics/Kratos.git /software/Kratos && \
    # using the configure file from the CI
    cp /software/Kratos/.github/workflows/configure.sh /software/Kratos/scripts/configure.sh && \
    cd /software/Kratos/scripts && \
    sh configure.sh

CMD [ "/bin/bash" ]

WORKDIR $HOME