FROM kratosmultiphysics/kratos-image-ci-ubuntu-bionic

ENV HOME /root

RUN git clone --depth 1 https://github.com/KratosMultiphysics/Kratos.git /software/Kratos && \
    # setting some environment variables for the build
    export KRATOS_BUILD_TYPE=Release && \
    export CC=/usr/lib/ccache/gcc && \
    export CXX=/usr/lib/ccache/g++ && \
    export KRATOS_CMAKE_OPTIONS_FLAGS="-DUSE_EIGEN_MKL=ON" && \
    # using the configure file from the CI
    cp /software/Kratos/.github/workflows/configure.sh /software/Kratos/configure.sh && \
    cd /software/Kratos && \
    sh configure.sh

CMD [ "/bin/bash" ]

WORKDIR $HOME