//
//   Project Name:        KratosConstitutiveModelsApplication $
//   Created by:          $Author:                JMCarbonell $
//   Last modified by:    $Co-Author:                         $
//   Date:                $Date:                   April 2017 $
//   Revision:            $Revision:                      0.0 $
//
//

#include "constitutive_models_application_variables.h"

namespace Kratos
{

  KRATOS_CREATE_VARIABLE( std::string, CONSTITUTIVE_LAW_NAME )
  KRATOS_CREATE_VARIABLE( bool, IMPLEX )
  //KRATOS_CREATE_VARIABLE( double, YOUNG_MODULUS )
  //KRATOS_CREATE_VARIABLE( double, POISSON_RATIO )  
  KRATOS_CREATE_VARIABLE( double, LAME_MU )
  KRATOS_CREATE_VARIABLE( double, LAME_LAMBDA )
  KRATOS_CREATE_VARIABLE( double, C10 )
  KRATOS_CREATE_VARIABLE( double, C20 )
  KRATOS_CREATE_VARIABLE( double, C30 )
  KRATOS_CREATE_VARIABLE( double, NORM_ISOCHORIC_STRESS )
  KRATOS_CREATE_VARIABLE( double, PLASTIC_STRAIN )
  KRATOS_CREATE_VARIABLE( double, DELTA_PLASTIC_STRAIN )
  KRATOS_CREATE_VARIABLE( double, ISOTROPIC_HARDENING_MODULUS )
  KRATOS_CREATE_VARIABLE( double, KINEMATIC_HARDENING_MODULUS )
  KRATOS_CREATE_VARIABLE( double, HARDENING_EXPONENT )
  KRATOS_CREATE_VARIABLE( double, REFERENCE_HARDENING_MODULUS )
  KRATOS_CREATE_VARIABLE( double, INFINITY_HARDENING_MODULUS )
  KRATOS_CREATE_VARIABLE( double, DAMAGE_VARIABLE )
  KRATOS_CREATE_VARIABLE( double, DAMAGE_THRESHOLD )
  KRATOS_CREATE_VARIABLE( double, STRENGTH_RATIO )
  KRATOS_CREATE_VARIABLE( double, FRACTURE_ENERGY )
  KRATOS_CREATE_VARIABLE( double, RESIDUAL_STRENGTH )
  KRATOS_CREATE_VARIABLE( double, SOFTENING_SLOPE )
  KRATOS_CREATE_VARIABLE( double, REFERENCE_TEMPERATURE )
  KRATOS_CREATE_VARIABLE( double, PLASTIC_DISSIPATION )
  KRATOS_CREATE_VARIABLE( double, DELTA_PLASTIC_DISSIPATION )
  KRATOS_CREATE_VARIABLE( double, REFERENCE_CONDUCTIVITY )
  KRATOS_CREATE_VARIABLE( double, HARDNESS_CONDUCTIVITY )
  KRATOS_CREATE_VARIABLE( double, MELD_TEMPERATURE )
  KRATOS_CREATE_VARIABLE( double, PLASTIC_STRAIN_RATE )
  KRATOS_CREATE_VARIABLE( double, JC_PARAMETER_A )
  KRATOS_CREATE_VARIABLE( double, JC_PARAMETER_B )
  KRATOS_CREATE_VARIABLE( double, JC_PARAMETER_C )
  KRATOS_CREATE_VARIABLE( double, JC_PARAMETER_m )
  KRATOS_CREATE_VARIABLE( double, JC_PARAMETER_n )
  KRATOS_CREATE_VARIABLE( double, JC_PARAMETER_K )  
  KRATOS_CREATE_VARIABLE( double, YOUNG_MODULUS_X )
  KRATOS_CREATE_VARIABLE( double, YOUNG_MODULUS_Y )
  KRATOS_CREATE_VARIABLE( double, YOUNG_MODULUS_Z )
  KRATOS_CREATE_VARIABLE( double, SHEAR_MODULUS_XY )
  KRATOS_CREATE_VARIABLE( double, SHEAR_MODULUS_YZ )
  KRATOS_CREATE_VARIABLE( double, SHEAR_MODULUS_XZ )
  KRATOS_CREATE_VARIABLE( double, POISSON_RATIO_XY )
  KRATOS_CREATE_VARIABLE( double, POISSON_RATIO_YZ )
  KRATOS_CREATE_VARIABLE( double, POISSON_RATIO_XZ ) 
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MATERIAL_ORIENTATION_DX )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MATERIAL_ORIENTATION_DY )
  KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MATERIAL_ORIENTATION_DZ )
  //KRATOS_CREATE_VARIABLE( double, THERMAL_EXPANSION_COEFFICIENT )
  //KRATOS_CREATE_VARIABLE( double, SHEAR_MODULUS )
  //KRATOS_CREATE_VARIABLE( double, BULK_MODULUS )

}
