stages:
  - build
    
# Master branch build
build linux_master:
    stage: build
    tags:
        - linux 
    only: 
        refs:
            - master
    script:
        - cp scripts/build/gitlab/build_and_test_master.sh build.sh
        - bash build.sh

build linux_branch:
    stage: build
    tags:
        - linux
    except: 
        refs:
            - master
    script:
        - cp scripts/build/gitlab/build_and_test_branch.sh build.sh
        - bash build.sh

build windows:
    stage: build
    tags:
        - windows
    script:
        - "call %VCVARS% x64"
        - copy scripts\build\gitlab\configure_gitlab_windows.bat cmake_build\configure.bat
        - cd cmake_build
        - call configure.bat
        - MSBuild.exe /m ALL_BUILD.vcxproj /p:TrackFileAccess=false /p:CLToolExe=clcache.exe /p:CLToolPath=%CLCACHE% /p:Configuration=Custom /p:Platform="x64"
        - MSBuild.exe /m INSTALL.vcxproj /p:TrackFileAccess=false /p:CLToolExe=clcache.exe /p:CLToolPath=%CLCACHE% /p:Configuration=Custom /p:Platform="x64"
        - cd ..
        - set pythonpath=%cd%;%cd%\libs
        - cd kratos/python_scripts
        - "%PYTHON% run_tests.py -l small -c %PYTHON%"
