sudo: false
dist: bionic
language: cpp
compiler: g++

git:
  depth: 1

cache: ccache

env:
  global:
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPILERCHECK=content
    - CCACHE_COMPRESS=true
    - CCACHE_NODISABLE=true
    - CCACHE_MAXSIZE=500M
    - FC=gfortran-7
    - CC=gcc
    - CXX=g++
addons:
  apt:
    packages:
      - gfortran-7
      - libboost-dev
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin
      - libmetis-dev
      - libtrilinos-amesos-dev
      - libtrilinos-aztecoo-dev
      - libtrilinos-epetra-dev
      - libtrilinos-epetraext-dev
      - libtrilinos-ifpack-dev
      - libtrilinos-ml-dev
      - libtrilinos-teuchos-dev

before_script:
- export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR}/bin/Custom
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/bin/Custom/libs

script:
- cp scripts/build/travis/configure_travis_bionic.sh configure.sh
- bash configure.sh
- python3 kratos/python_scripts/run_tests.py -l small -c python3
- ccache -s
