sudo: false
dist: bionic
language: cpp
compiler: g++

git:
  depth: 3

cache: ccache

env:
  global:
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPILERCHECK=content
    - CCACHE_COMPRESS=true
    - CCACHE_NODISABLE=true
    - CCACHE_MAXSIZE=500M
    - FC=gfortran-6

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-6
      - g++-6
      - gfortran-6
      - libboost-dev
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin
      - libmetis-dev
      - libtrilinos-amesos-dev
      - libtrilinos-aztecoo-dev
      - libtrilinos-epetra-dev
      - libtrilinos-epetraext-dev
      - libtrilinos-ifpack-dev
      - libtrilinos-ml-dev
      - libtrilinos-teuchos-dev

before_script:
- export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR}
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/libs

script:
- cp scripts/build/travis/configure_travis_bionic.sh cmake_build/configure.sh
- cd cmake_build
- bash configure.sh
- make all_unity
- make runkratos
- make install/fast
- cd ../kratos/python_scripts
- python3 run_tests.py -l small -c python3
- ccache -s
