sudo: false
dist: trusty
language: cpp
compiler: clang

git:
  depth: 2

cache: ccache

env:
  global:
    - CCACHE_COMPILERCHECK=content
    - CCACHE_COMPRESS=true
    - CCACHE_NODISABLE=true
    - CCACHE_MAXSIZE=500M

addons:
  apt:
    sources:
      - sourceline: 'ppa:boost-latest/ppa'
    packages:
      - gfortran
      - libboost1.55-dev
      - libboost-serialization1.55-dev
      - libboost-python1.55-dev
      - libblas-dev
      - liblapack-dev

before_script:
- export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR}
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/libs

script:
- cp scripts/build/travis/configure_travis_trusty.sh cmake_build/configure.sh
- cd cmake_build
- bash configure.sh
- make install -j2
- ccache -s

# - cd ../kratos/python_scripts
# - python3 run_tests.py -l small
