# build only master
branches:
  only:
    - master

# Specify version format
version: "{build}"

# set clone depth
shallow_clone: true

# Image
image: Visual Studio 2017

# Build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - x64

# Specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_65_1
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_65_1\lib64-msvc-14.1

# Build configuration, i.e. Debug, Release, etc.
configuration:
  - Release

# Scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# Clone directory
clone_folder: C:\projects\kratos

# Scripts that run after cloning repository
install:
  - SET preferredToolArchitecture=x64
  - cmd: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvars64.bat x64
  - cmd: cp C:\projects\kratos\scripts\build\appveyor\configure_appveyor_VS2017.bat C:\projects\kratos\cmake_build\configure_appveyor_VS2017.bat

# Scripts to run before build
before_build:
  - cmd: cd C:\projects\kratos\applications\DelaunayMeshingApplication
  - cmd: mkdir external_modules
  - cmd: cd external_modules
  - cmd: curl -L https://github.com/PFEM/tetgen/archive/0f0c1c95388d9a515e2383533c6b4f18524d9e76.zip -o tetgen.zip
  - cmd: 7z e tetgen.zip -o"tetgen"
  - cmd: cd C:\projects\kratos\cmake_build
  - cmd: .\configure_appveyor_VS2017.bat

# Custom build script
build_script:
  - cmd: SET preferredToolArchitecture=x64
  - cmd: MSBuild.exe kratos/all_unity.vcxproj /p:Configuration=Debug /p:Platform="x64"

test: off
