#include "stabilized_cfd_application_variables.h"

namespace Kratos
{
KRATOS_CREATE_VARIABLE( double, FIC_BETA )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DIRECTIONAL_BETA )
KRATOS_CREATE_VARIABLE( int, RECORDED_STEPS )
KRATOS_CREATE_VARIABLE( double, MEAN_KINETIC_ENERGY )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MEAN_VELOCITY )
KRATOS_CREATE_VARIABLE( double, MEAN_PRESSURE )
KRATOS_CREATE_VARIABLE( Matrix, VELOCITY_COVARIANCES )
KRATOS_CREATE_VARIABLE( TurbulenceStatisticsContainer::Pointer, TURBULENCE_STATISTICS )
KRATOS_CREATE_VARIABLE( double, TRACE_XI )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DIV_XI )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM_PROJECTION )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM_PROJECTION_RHS )
KRATOS_CREATE_VARIABLE( double, MASS_PROJECTION )
KRATOS_CREATE_VARIABLE( double, MASS_PROJECTION_RHS )

}
