# CMake generated Testfile for 
# Source directory: /home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/example
# Build directory: /home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/example
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(example_drv_facto0_s_analyze "./analyze" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_s_analyze "./analyze" "-9" "s:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_s_analyze "./analyze" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_analyze "./analyze" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_d_analyze "./analyze" "-9" "d:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_d_analyze "./analyze" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_analyze "./analyze" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_c_analyze "./analyze" "-9" "c:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_c_analyze "./analyze" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_c_analyze "./analyze" "-9" "c:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_c_analyze "./analyze" "-9" "c:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_z_analyze "./analyze" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_z_analyze "./analyze" "-9" "z:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_z_analyze "./analyze" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_z_analyze "./analyze" "-9" "z:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_z_analyze "./analyze" "-9" "z:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_s_step-by-step "./step-by-step" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_s_step-by-step "./step-by-step" "-9" "s:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_s_step-by-step "./step-by-step" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_step-by-step "./step-by-step" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_d_step-by-step "./step-by-step" "-9" "d:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_d_step-by-step "./step-by-step" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_step-by-step "./step-by-step" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_c_step-by-step "./step-by-step" "-9" "c:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_c_step-by-step "./step-by-step" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_c_step-by-step "./step-by-step" "-9" "c:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_c_step-by-step "./step-by-step" "-9" "c:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_z_step-by-step "./step-by-step" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_z_step-by-step "./step-by-step" "-9" "z:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_z_step-by-step "./step-by-step" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_z_step-by-step "./step-by-step" "-9" "z:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_z_step-by-step "./step-by-step" "-9" "z:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_s_schur "./schur" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto2_s_schur "./schur" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_schur "./schur" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto2_d_schur "./schur" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_schur "./schur" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto2_c_schur "./schur" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_z_schur "./schur" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto2_z_schur "./schur" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_s_personal "./personal" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_s_personal "./personal" "-9" "s:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_s_personal "./personal" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_personal "./personal" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_d_personal "./personal" "-9" "d:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_d_personal "./personal" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_personal "./personal" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_c_personal "./personal" "-9" "c:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_c_personal "./personal" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_c_personal "./personal" "-9" "c:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_c_personal "./personal" "-9" "c:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_z_personal "./personal" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_z_personal "./personal" "-9" "z:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_z_personal "./personal" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_z_personal "./personal" "-9" "z:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_z_personal "./personal" "-9" "z:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_s_reentrant "./reentrant" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_s_reentrant "./reentrant" "-9" "s:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_s_reentrant "./reentrant" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_reentrant "./reentrant" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_d_reentrant "./reentrant" "-9" "d:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_d_reentrant "./reentrant" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_reentrant "./reentrant" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_c_reentrant "./reentrant" "-9" "c:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_c_reentrant "./reentrant" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_c_reentrant "./reentrant" "-9" "c:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_c_reentrant "./reentrant" "-9" "c:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_z_reentrant "./reentrant" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_z_reentrant "./reentrant" "-9" "z:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_z_reentrant "./reentrant" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_z_reentrant "./reentrant" "-9" "z:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_z_reentrant "./reentrant" "-9" "z:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_s_old/old_simple "./old/old_simple" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_s_old/old_simple "./old/old_simple" "-9" "s:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_s_old/old_simple "./old/old_simple" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_old/old_simple "./old/old_simple" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_d_old/old_simple "./old/old_simple" "-9" "d:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_d_old/old_simple "./old/old_simple" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_old/old_simple "./old/old_simple" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_c_old/old_simple "./old/old_simple" "-9" "c:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_c_old/old_simple "./old/old_simple" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_c_old/old_simple "./old/old_simple" "-9" "c:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_c_old/old_simple "./old/old_simple" "-9" "c:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_z_old/old_simple "./old/old_simple" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_z_old/old_simple "./old/old_simple" "-9" "z:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_z_old/old_simple "./old/old_simple" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_z_old/old_simple "./old/old_simple" "-9" "z:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_z_old/old_simple "./old/old_simple" "-9" "z:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_s_old/old_step-by-step "./old/old_step-by-step" "-9" "s:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_s_old/old_step-by-step "./old/old_step-by-step" "-9" "s:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_s_old/old_step-by-step "./old/old_step-by-step" "-9" "s:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_d_old/old_step-by-step "./old/old_step-by-step" "-9" "d:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_d_old/old_step-by-step "./old/old_step-by-step" "-9" "d:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_d_old/old_step-by-step "./old/old_step-by-step" "-9" "d:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto0_c_old/old_step-by-step "./old/old_step-by-step" "-9" "c:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_c_old/old_step-by-step "./old/old_step-by-step" "-9" "c:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_c_old/old_step-by-step "./old/old_step-by-step" "-9" "c:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_c_old/old_step-by-step "./old/old_step-by-step" "-9" "c:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_c_old/old_step-by-step "./old/old_step-by-step" "-9" "c:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_drv_facto0_z_old/old_step-by-step "./old/old_step-by-step" "-9" "z:10:10:10:2" "-f" "0" "-c" "2")
add_test(example_drv_facto1_z_old/old_step-by-step "./old/old_step-by-step" "-9" "z:10:10:10:2" "-f" "1" "-c" "2")
add_test(example_drv_facto2_z_old/old_step-by-step "./old/old_step-by-step" "-9" "z:10:10:10:2" "-f" "2" "-c" "2")
add_test(example_drv_facto3_z_old/old_step-by-step "./old/old_step-by-step" "-9" "z:10:10:10:2" "-f" "3" "-c" "2")
add_test(example_drv_facto4_z_old/old_step-by-step "./old/old_step-by-step" "-9" "z:10:10:10:2" "-f" "4" "-c" "2")
add_test(example_mm_simple_pastixorderscotch "./simple" "--mm" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/young4c.mtx" "-f" "1" "-i" "iparm_ordering" "pastixorderscotch")
add_test(example_hb_simple_pastixorderscotch "./simple" "--hb" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/orsirr.rua" "-f" "2" "-i" "iparm_ordering" "pastixorderscotch")
add_test(example_mm2_simple_pastixorderscotch "./simple" "--mm" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/mhd1280b.mtx" "-f" "2" "-i" "iparm_ordering" "pastixorderscotch")
add_test(example_refine_cg_simple "./simple" "--hb" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/small.rsa" "-f" "1" "-i" "iparm_refinement" "pastixrefinecg" "-d" "dparm_epsilon_magn_ctrl" "1e-14")
add_test(example_refine_gmres_simple "./simple" "--hb" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/orsirr.rua" "-f" "2" "-i" "iparm_refinement" "pastixrefinegmres")
add_test(example_refine_bicgstab_simple "./simple" "--hb" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/orsirr.rua" "-f" "2" "-i" "iparm_refinement" "pastixrefinebicgstab")
add_test(example_cg_sym_s_refinement "./refinement" "-9" "s:10:10:10:2" "-i" "iparm_refinement" "pastixrefinecg")
add_test(example_gmres_sym_s_refinement "./refinement" "-9" "s:10:10:10:2" "-i" "iparm_refinement" "pastixrefinegmres")
add_test(example_bicgstab_sym_s_refinement "./refinement" "-9" "s:10:10:10:2" "-i" "iparm_refinement" "pastixrefinebicgstab")
add_test(example_cg_sym_d_refinement "./refinement" "-9" "d:10:10:10:2" "-i" "iparm_refinement" "pastixrefinecg")
add_test(example_gmres_sym_d_refinement "./refinement" "-9" "d:10:10:10:2" "-i" "iparm_refinement" "pastixrefinegmres")
add_test(example_bicgstab_sym_d_refinement "./refinement" "-9" "d:10:10:10:2" "-i" "iparm_refinement" "pastixrefinebicgstab")
add_test(example_cg_her_c_refinement "./refinement" "-x" "c:10:10:10:2" "-i" "iparm_refinement" "pastixrefinecg")
add_test(example_gmres_her_c_refinement "./refinement" "-x" "c:10:10:10:2" "-i" "iparm_refinement" "pastixrefinegmres")
add_test(example_bicgstab_her_c_refinement "./refinement" "-x" "c:10:10:10:2" "-i" "iparm_refinement" "pastixrefinebicgstab")
add_test(example_cg_sym_c_refinement "./refinement" "-9" "c:10:10:10:2" "-i" "iparm_refinement" "pastixrefinecg")
add_test(example_gmres_sym_c_refinement "./refinement" "-9" "c:10:10:10:2" "-i" "iparm_refinement" "pastixrefinegmres")
add_test(example_bicgstab_sym_c_refinement "./refinement" "-9" "c:10:10:10:2" "-i" "iparm_refinement" "pastixrefinebicgstab")
add_test(example_cg_her_z_refinement "./refinement" "-x" "z:10:10:10:2" "-i" "iparm_refinement" "pastixrefinecg")
add_test(example_gmres_her_z_refinement "./refinement" "-x" "z:10:10:10:2" "-i" "iparm_refinement" "pastixrefinegmres")
add_test(example_bicgstab_her_z_refinement "./refinement" "-x" "z:10:10:10:2" "-i" "iparm_refinement" "pastixrefinebicgstab")
add_test(example_cg_sym_z_refinement "./refinement" "-9" "z:10:10:10:2" "-i" "iparm_refinement" "pastixrefinecg")
add_test(example_gmres_sym_z_refinement "./refinement" "-9" "z:10:10:10:2" "-i" "iparm_refinement" "pastixrefinegmres")
add_test(example_bicgstab_sym_z_refinement "./refinement" "-9" "z:10:10:10:2" "-i" "iparm_refinement" "pastixrefinebicgstab")
add_test(example_sched0_1d_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched0_1d_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_tasks2d_level" "0")
add_test(example_sched1_1d_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_tasks2d_level" "0")
add_test(example_svdbegin_sched0_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched0_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched0_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched0_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched0_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "0" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto0_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto1_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto2_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto3_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto4_s_simple "./simple" "-9" "s:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto0_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto1_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto2_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto3_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto4_d_simple "./simple" "-9" "d:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto0_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto1_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto2_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto3_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto4_c_simple "./simple" "-9" "c:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto0_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "0" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto1_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "1" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto2_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "2" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto3_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "3" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdbegin_sched1_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_svdend_sched1_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodsvd" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrbegin_sched1_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenbegin" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
add_test(example_rrqrend_sched1_facto4_z_simple "./simple" "-9" "z:10:10:10:2" "-s" "1" "-f" "4" "-i" "iparm_compress_when" "pastixcompresswhenend" "-i" "iparm_compress_method" "pastixcompressmethodrrqr" "-i" "iparm_compress_min_width" "16" "-i" "iparm_compress_min_height" "16")
subdirs("old")
