//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ \.
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Suneth Warnakulasuriya
//

#if !defined(KRATOS_INDIRECT_SCALAR_VARIABLES_H_INCLUDED )
#define  KRATOS_INDIRECT_SCALAR_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "containers/indirect_scalar_variable.h"

#undef  KRATOS_EXPORT_MACRO
#define KRATOS_EXPORT_MACRO KRATOS_API

namespace Kratos
{
    // Zero scalar variable
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(SCALAR_ZERO)

    // Adjoint variables variable
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_1_X)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_1_Y)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_1_Z)


    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_2_X)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_2_Y)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_2_Z)

    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_3_X)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_3_Y)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_VECTOR_3_Z)

    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(AUX_ADJOINT_VECTOR_1_X)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(AUX_ADJOINT_VECTOR_1_Y)
    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(AUX_ADJOINT_VECTOR_1_Z)

    KRATOS_DEFINE_INDIRECT_VARIABLE_VARIABLE(ADJOINT_SCALAR_1)

}  // namespace Kratos.

#undef  KRATOS_EXPORT_MACRO
#define KRATOS_EXPORT_MACRO KRATOS_NO_EXPORT

#endif // KRATOS_INDIRECT_SCALAR_VARIABLES_H_INCLUDED  defined
