FROM ubuntu:focal

ENV HOME /root

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get -y install \
        gnupg2 \
        software-properties-common \
        wget && \
    wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB -P/tmp && \
    apt-key add /tmp/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    rm /tmp/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list && \
    add-apt-repository ppa:git-core/ppa && \
    apt-get -y update && \
    apt-get install -y \
        build-essential \
        ccache \
        clang-9 \
        cmake \
        gfortran-7 \
        git \
        intel-mkl-2020.0-088 \
        libopenmpi-dev \
        openmpi-bin \
        valgrind && \
    /usr/sbin/update-ccache-symlinks && \
    echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc && \
    python3 -m pip install --upgrade pip && \
    pip3 install \
        numpy \
        scipy && \
    # remove some now unnecessary packages
    apt-get -y remove \
        gnupg2 \
        software-properties-common \
        wget && \
    apt-get clean

CMD [ "/bin/bash" ]

WORKDIR $HOME
