FROM ubuntu:focal

ENV HOME /root

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get -y install \
        gnupg2 \
        software-properties-common \
        wget && \
    wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB -P/tmp && \
    apt-key add /tmp/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && \
    rm /tmp/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && \
    echo deb https://apt.repos.intel.com/oneapi all main > /etc/apt/sources.list.d/oneAPI.list && \
    add-apt-repository ppa:git-core/ppa && \
    apt-get -y update && \
    apt-get install -y \
        build-essential \
        clang \
        intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic \
        intel-oneapi-mpi \
        cmake \
        gfortran \
        git \
        libopenmpi-dev \
        openmpi-bin \
        valgrind && \
    # remove some now unnecessary packages
    apt-get -y remove \
        gnupg2 \
        software-properties-common \
        wget && \
    apt-get clean

CMD [ "/bin/bash" ]

WORKDIR $HOME

COPY scripts/docker_files/docker_file_compilers_ubuntu_20_04/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
