# Application dependent names and paths
from KratosMultiphysics import _ImportApplication, python_registry_utilities
from KratosFluidDynamicsHydraulicsApplication import *

application = KratosFluidDynamicsHydraulicsApplication()
application_name = "KratosFluidDynamicsHydraulicsApplication"

_ImportApplication(application, application_name)

from . import python_registry_lists
python_registry_utilities.RegisterModelersList("KratosMultiphysics.FluidDynamicsHydraulicsApplication", python_registry_lists)
python_registry_utilities.RegisterOperationsList("KratosMultiphysics.FluidDynamicsHydraulicsApplication", python_registry_lists)
python_registry_utilities.RegisterProcessesList("KratosMultiphysics.FluidDynamicsHydraulicsApplication", python_registry_lists)