//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Mohammad R. Hashemi
//

#if !defined(KRATOS_DROPLET_DYNAMICS_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_DROPLET_DYNAMICS_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "containers/variable.h"

namespace Kratos
{
    // External interfacial force, e.g. for including the electromagentic coupling
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, EXT_INT_FORCE)
    
    //Auxiliary variable to store maximum element size (h_{max})
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, NODAL_H_MAX)

    // Smoothing surface auxiliary distance
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, DISTANCE_AUX)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, DISTANCE_AUX2) //For re-distancing
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, DISTANCE_GRADIENT_AUX)

    // Parallel levelset distance calculator needs an AREA_VARIABLE_AUX
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, AREA_VARIABLE_AUX)

    // A variable to check if node is on cut element (maybe in a layer farther for future!)
    //KRATOS_DEFINE_APPLICATION_VARIABLE( FLUID_DYNAMICS_APPLICATION, double, IS_NEAR_CUT)

    // Contact line calculation
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, NORMAL_VECTOR)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, TANGENT_VECTOR)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, CONTACT_VECTOR)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, CONTACT_ANGLE)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, CONTACT_VECTOR_MICRO)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, CONTACT_ANGLE_MICRO)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, CONTACT_VELOCITY)

    // Enriched pressure is an array of NumNodes components defined for elements. Access it using Element.GetValue()
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, ENRICHED_PRESSURE_1)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, ENRICHED_PRESSURE_2)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, ENRICHED_PRESSURE_3)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, ENRICHED_PRESSURE_4)

    // Last known velocity and pressure to recalculate the last increment
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, VELOCITY_STAR)
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, PRESSURE_STAR)

    // Pressure gradient to calculate its jump over interface
    // KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( FLUID_DYNAMICS_APPLICATION, PRESSURE_GRADIENT_AUX)

    // Level-set convective velocity
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, CONVECTIVE_VELOCITY)

}

#endif	/* KRATOS_DROPLET_DYNAMICS_APPLICATION_VARIABLES_H_INCLUDED */
