//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Mohammad R. Hashemi
//

#if !defined(KRATOS_DROPLET_DYNAMICS_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_DROPLET_DYNAMICS_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "containers/variable.h"

namespace Kratos
{
    // External interfacial force, e.g. for including the electromagentic coupling
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, EXT_INT_FORCE)

    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, EPOTENTIAL )
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, PERMITTIVITYPOS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, PERMITTIVITYNEG )
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, CONDUCTIVITYPOS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, CONDUCTIVITYNEG )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, EFIELD )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, SCHARGE )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, EFORCE )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, EFIELDPOS )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, EFIELDNEG )


    // variables for enrich CASES
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, double, INV_K_ENRICH )
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, Vector, BIJ_ENRICH_ROW )
    KRATOS_DEFINE_APPLICATION_VARIABLE( DROPLET_DYNAMICS_APPLICATION, Vector, BJI_ENRICH_ROW )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, POS_GRAD_ENRICH )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, NEG_GRAD_ENRICH )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( DROPLET_DYNAMICS_APPLICATION, RHS_ENRICH )
    }

#endif	/* KRATOS_DROPLET_DYNAMICS_APPLICATION_VARIABLES_H_INCLUDED */
