FROM rockylinux:8

USER root

ENV HOME /root

# Install devtools 13
RUN dnf -y install gcc-toolset-13

# Enable devtools 13 every time a shell is started
# TODO: /etc/bashrc is never executed so this line does not fulfill its purpose => fix it.
RUN echo "source /opt/rh/gcc-toolset-13/enable" >> /etc/bashrc

# Install python3.10.18
RUN dnf update -y && \
    dnf groupinstall "Development Tools" -y && \
    dnf install -y wget openssl-devel bzip2-devel libffi-devel && \
    wget https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz && \
    tar xzf Python-3.10.18.tgz && \
    cd Python-3.10.18 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.10.18 Python-3.10.18.tgz

ENV PYTHON_EXECUTABLE /usr/local/bin/python3.10

RUN python3.10 -m pip install numpy sympy scipy parameterized

# Install build utils
RUN dnf update -y && dnf install -y \
    --enablerepo=devel ninja-build \
    cmake \
    gcc-gfortran \
    --enablerepo=devel blas-devel \
    --enablerepo=devel lapack-devel

# Install Boost libraries
RUN dnf update -y && dnf install -y \
    boost-devel

CMD [ "/bin/bash" ]

WORKDIR $HOME