#!/bin/bash

CONFPATH="/etc/ld.so.conf.d"
CONFFILE="kratos.conf"
#CONFPATH="${HOME}"

if [ -e ${CONFPATH}/${CONFFILE} ]; then
 rm -f ${CONFPATH}/${CONFFILE}
fi

##pwd
##echo "/opt/kratos/libs" > ${CONFPATH}/${CONFFILE}
cp /opt/kratos/packaging/kratos.conf ${CONFPATH}/${CONFFILE}
ldconfig

cd /opt/kratos/packaging
python script.py install
rm kratos.conf
rm KratosLoader.py
rm script.py
cd ..
rmdir packaging

