FROM ubuntu:focal

ENV HOME /root

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get -y install \
        gnupg2 \
        software-properties-common \
        wget && \
    wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB -P/tmp && \
    apt-key add /tmp/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    rm /tmp/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list && \
    add-apt-repository ppa:git-core/ppa && \
    apt-get -y update && \
    apt-get install -y \
        build-essential \
        ccache \
        clang-9 \
        cmake \
        gfortran-7 \
        git \
        intel-mkl-2020.0-088 \
        libblas-dev \
        libboost-dev \
        libhdf5-dev \
        libhdf5-openmpi-dev \
        liblapack-dev \
        libmetis-dev \
        libopenmpi-dev \
        libscotch-dev \
        libtrilinos-amesos-dev \
        libtrilinos-aztecoo-dev \
        libtrilinos-epetra-dev \
        libtrilinos-epetraext-dev \
        libtrilinos-ifpack-dev \
        libtrilinos-ml-dev \
        libtrilinos-teuchos-dev \
        openmpi-bin \
        python3-dev \
        python3-h5py \
        python3-pip \
        valgrind && \
    /usr/sbin/update-ccache-symlinks && \
    echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc && \
    python3 -m pip install --upgrade pip && \
    pip3 install \
        numpy \
        scipy && \
    # install MMG 5.4
    git clone -b 'v5.4.1' --depth 1 https://github.com/MmgTools/mmg /tmp/mmg && \
    mkdir /tmp/mmg/build && \
    cd /tmp/mmg/build && \
    cmake .. -DLIBMMG3D_SHARED=ON -DLIBMMG2D_SHARED=ON -DLIBMMGS_SHARED=ON -DLIBMMG_SHARED=ON && \
    make install && \
    rm -r /tmp/mmg && \
    cd / && \
    # install MMG 5.5
    git clone -b 'v5.5.1' --depth 1 https://github.com/MmgTools/mmg /tmp/mmg_5_5_1 && \
    mkdir /tmp/mmg_5_5_1/build && \
    mkdir -p /external_libraries/mmg/mmg_5_5_1 && \
    cd /tmp/mmg_5_5_1/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX="/external_libraries/mmg/mmg_5_5_1" -DLIBMMG3D_SHARED=ON -DLIBMMG2D_SHARED=ON -DLIBMMGS_SHARED=ON -DLIBMMG_SHARED=ON && \
    make install && \
    rm -r /tmp/mmg_5_5_1 && \
    cd / && \
    # remove some now unnecessary packages
    apt-get -y remove \
        gnupg2 \
        software-properties-common \
        wget && \
    apt-get clean

CMD [ "/bin/bash" ]

WORKDIR $HOME
