.TH MPE_Log_event 4 "6/15/2009" " " "MPE"
.SH NAME
MPE_Log_event \-  Log an event in MPI_COMM_WORLD. 
.SH SYNOPSIS
.nf
int MPE_Log_event( int event, int data, const char *bytebuf )
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B event   
- event number.
.PD 1
.PD 0
.TP
.B data    
- integer data value
(not used, provided for backward compatibility purpose).
.PD 1
.PD 0
.TP
.B bytebuf 
- optional byte informational array.  In C, bytebuf should be
set to NULL when no extra byte informational data.  In Fortran,
an zero-length string "", or a single blank string " ",
is equivalent to NULL in C.
.PD 1

.SH NOTES
This function is threadsafe.

.SH RETURNS
alway returns MPE_LOG_OK

.SH LOCATION
../src/logging/src/mpe_log.c
