.TH MPE_Log_comm_event 4 "6/15/2009" " " "MPE"
.SH NAME
MPE_Log_comm_event \-  Log an event in a specified MPI_Comm. (on the calling thread where the event takes place) 
.SH SYNOPSIS
.nf
int MPE_Log_comm_event( MPI_Comm comm, int event, const char *bytebuf )
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B comm          
- MPI_Comm where this process is part of.
.PD 1
.PD 0
.TP
.B event         
- event number.
.PD 1
.PD 0
.TP
.B bytebuf       
- optional byte informational array.  In C, bytebuf should be
set to NULL when no extra byte informational data.  In
Fortran, an zero-length string "", or a single blank string
" ", is equivalent to NULL in C.
.PD 1

.SH NOTES
This function is threadsafe.

.SH RETURNS
alway returns MPE_LOG_OK
.SH LOCATION
../src/logging/src/mpe_log.c
