.TH MPE_Log_merged_logfilename 4 "6/15/2009" " " "MPE"
.SH NAME
MPE_Log_merged_logfilename \-  return the immutable name of the merged final logfile. 
.SH SYNOPSIS
.nf
const char *MPE_Log_merged_logfilename( void )
.fi
.SH NOTES
This function has no fortran interface.
.SH LOCATION
../src/logging/src/mpe_log.c
