//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ \.
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics ThermalDEM Application
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Rafael Rangel (rrangel@cimne.upc.edu)
//

#if !defined(KRATOS_THERMAL_DEM_APPLICATION_VARIABLES_H_INCLUDED)
#define KRATOS_THERMAL_DEM_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "includes/variables.h"
#include "includes/kratos_application.h"

namespace Kratos
{
  // Variables
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, std::string, DIRECT_CONDUCTION_MODEL)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, std::string, INDIRECT_CONDUCTION_MODEL)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, std::string, CONVECTION_MODEL)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, std::string, RADIATION_MODEL)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, std::string, ADJUSTED_CONTACT_MODEL)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, std::string, VORONOI_METHOD)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, std::string, POSORITY_METHOD)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        MOTION_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        DIRECT_CONDUCTION_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        INDIRECT_CONDUCTION_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        CONVECTION_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        RADIATION_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        FRICTION_HEAT_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        ADJUSTED_CONTACT_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        TEMPERATURE_DEPENDENT_RADIUS_OPTION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        FIXED_TEMPERATURE)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, bool,        ADIABATIC)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, int,         THERMAL_FREQUENCY)
  //KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      HEATFLUX)             //defined in DEMApp
  //KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      THERMAL_CONDUCTIVITY) // defined in DEMApp
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      REAL_YOUNG_MODULUS_RATIO)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      HEATSOURCE)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      MIN_CONDUCTION_DISTANCE)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      MAX_CONDUCTION_DISTANCE)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      ISOTHERMAL_CORE_RADIUS)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      MAX_RADIATION_DISTANCE)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      FRICTION_HEAT_CONVERSION)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      AVERAGE_POROSITY)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      ALPHA_SHAPE_PARAMETER)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      INTEGRAL_TOLERANCE)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      FLUID_LAYER_THICKNESS)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      FLUID_DENSITY)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      FLUID_VISCOSITY)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      FLUID_THERMAL_CONDUCTIVITY)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      FLUID_HEAT_CAPACITY)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, double,      FLUID_TEMPERATURE)
  KRATOS_DEFINE_APPLICATION_VARIABLE(THERMAL_DEM_APPLICATION, Vector,      FLUID_VELOCITY)

  // Flags
  class DEMThermalFlags
  {
    public:
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, IS_ADIABATIC);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_MOTION);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_FIXED_TEMPERATURE);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_DIRECT_CONDUCTION);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_INDIRECT_CONDUCTION);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_CONVECTION);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_RADIATION);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_FRICTION_HEAT);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_ADJUSTED_CONTACT);
      KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_DEM_APPLICATION, HAS_TEMPERATURE_DEPENDENT_RADIUS);
  };
} // namespace Kratos

#endif // KRATOS_THERMAL_DEM_APPLICATION_VARIABLES_H_INCLUDED defined
