 
//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:		 
//					 Kratos default license: 
//
//  Main authors:    
//


#if !defined(KRATOS_ULF_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_ULF_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "includes/kratos_application.h"
#include "includes/variables.h"
#include "includes/dem_variables.h"
#include "includes/cfd_variables.h"
#include "includes/legacy_structural_app_vars.h"

namespace Kratos
{

     KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PRESSURE_FORCE)
     KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(DISP_FRAC)
     KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(VAUX)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, TAUONE)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, TAUTWO)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, NODAL_LENGTH)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, CURVATURE)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, TRIPLE_POINT)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, CONTACT_ANGLE)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, CONTACT_ANGLE_STATIC )
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, SURFTENS_COEFF) 
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, MEAN_CURVATURE)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, GAUSSIAN_CURVATURE)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, PRINCIPAL_CURVATURE_1)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, PRINCIPAL_CURVATURE_2)
     KRATOS_DEFINE_APPLICATION_VARIABLE(ULF_APPLICATION, double, SUBSCALE_PRESSURE)
     
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, VISCOUS_STRESSX)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, VISCOUS_STRESSY)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, VISCOUS_STRESSZ) 
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, PRINCIPAL_DIRECTION_1) 
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, PRINCIPAL_DIRECTION_2)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, NORMAL_GEOMETRIC)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, ADHESION_FORCE)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, NORMAL_EQ)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, NORMAL_CL_EQ)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, NORMAL_TP)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, NORMAL_CL)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, SOLID_FRACTION_GRADIENT)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, SOLID_FRACTION_GRADIENT_PROJECTED)
     KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(ULF_APPLICATION, SUBSCALE_VELOCITY)
     
    }

#endif	