domain_size = *GenData(DOMAIN_SIZE)

max_time = *GenData(max_time)
max_x = *GenData(max_x)
max_y = *GenData(max_y)
max_z = *GenData(max_z)
min_x = *GenData(min_x)
min_y = *GenData(min_y)
min_z = *GenData(min_z)
use_oss = *GenData(use_oss)
dynamic_tau = *GenData(dynamic_tau)
nsteps = *GenData(nsteps)
output_Dt = *GenData(output_dt)
min_dt = *GenData(min_dt)
max_dt = *GenData(max_dt)
safety_factor = *GenData(safety_factor)
SolverType = *GenData(SolverType)
laplacian_form = *GenData(laplacian_form)
# Declare Python Variables

