from __future__ import print_function, absolute_import, division  # makes these scripts backward compatible with python 2.6 and 2.7

class Variable(object):
    def __init__(self, var_name, components=None):
        self.__name = var_name
        # self.__type = var_type
        self.components = components

    def Name(self):
        return self.__name

    def __hash__(self):
        return hash(self.__name)

DISPLACEMENT_X = Variable("DISPLACEMENT_X")
DISPLACEMENT_Y = Variable("DISPLACEMENT_Y")
DISPLACEMENT_Z = Variable("DISPLACEMENT_Z")
DISPLACEMENT = Variable("DISPLACEMENT", [DISPLACEMENT_X, DISPLACEMENT_Y, DISPLACEMENT_Z])

MESH_DISPLACEMENT_X = Variable("MESH_DISPLACEMENT_X")
MESH_DISPLACEMENT_Y = Variable("MESH_DISPLACEMENT_Y")
MESH_DISPLACEMENT_Z = Variable("MESH_DISPLACEMENT_Z")
MESH_DISPLACEMENT = Variable("MESH_DISPLACEMENT",[MESH_DISPLACEMENT_X, MESH_DISPLACEMENT_Y, MESH_DISPLACEMENT_Z])

VELOCITY_X = Variable("VELOCITY_X")
VELOCITY_Y = Variable("VELOCITY_Y")
VELOCITY_Z = Variable("VELOCITY_Z")
VELOCITY = Variable("VELOCITY",[VELOCITY_X,VELOCITY_Y, VELOCITY_Z])

POINT_LOAD_X = Variable("POINT_LOAD_X")
POINT_LOAD_Y = Variable("POINT_LOAD_Y")
POINT_LOAD_Z = Variable("POINT_LOAD_Z")
POINT_LOAD = Variable("POINT_LOAD",[POINT_LOAD_X,POINT_LOAD_Y, POINT_LOAD_Z])

FORCE_X = Variable("FORCE_X")
FORCE_Y = Variable("FORCE_Y")
FORCE_Z = Variable("FORCE_Z")
FORCE = Variable("FORCE",[FORCE_X, FORCE_Y, FORCE_Z])

REACTION_X = Variable("REACTION_X")
REACTION_Y = Variable("REACTION_Y")
REACTION_Z = Variable("REACTION_Z")
REACTION = Variable("REACTION",[REACTION_X, REACTION_Y, REACTION_Z])

EXTERNAL_FORCE_X = Variable("EXTERNAL_FORCE_X")
EXTERNAL_FORCE_Y = Variable("EXTERNAL_FORCE_Y")
EXTERNAL_FORCE_Z = Variable("EXTERNAL_FORCE_Z")
EXTERNAL_FORCE = Variable("EXTERNAL_FORCE",[EXTERNAL_FORCE_X, EXTERNAL_FORCE_Y, EXTERNAL_FORCE_Z])

EXTERNAL_FORCE_X = Variable("EXTERNAL_FORCE_X")
EXTERNAL_FORCE_Y = Variable("EXTERNAL_FORCE_Y")
EXTERNAL_FORCE_Z = Variable("EXTERNAL_FORCE_Z")
EXTERNAL_FORCE = Variable("EXTERNAL_FORCE",[EXTERNAL_FORCE_X, EXTERNAL_FORCE_Y, EXTERNAL_FORCE_Z])

TORQUE_X = Variable("TORQUE_X")
TORQUE_Y = Variable("TORQUE_Y")
TORQUE_Z = Variable("TORQUE_Z")
TORQUE = Variable("TORQUE",[TORQUE_X, TORQUE_Y, TORQUE_Z])

NORMAL_X = Variable("NORMAL_X")
NORMAL_Y = Variable("NORMAL_Y")
NORMAL_Z = Variable("NORMAL_Z")
NORMAL = Variable("NORMAL",[NORMAL_X, NORMAL_Y, NORMAL_Z])

PRESSURE = Variable("PRESSURE")
YOUNG_MODULUS = Variable("YOUNG_MODULUS")
POISSON_RATIO = Variable("POISSON_RATIO")
DOMAIN_SIZE = Variable("DOMAIN_SIZE")
DENSITY = Variable("DENSITY")
VISCOSITY = Variable("VISCOSITY")
TIME = Variable("TIME")
DELTA_TIME = Variable("DELTA_TIME")
TEMPERATURE = Variable("TEMPERATURE")
NODAL_MASS = Variable("NODAL_MASS")
NODAL_ERROR = Variable("NODAL_ERROR")
