from __future__ import print_function, absolute_import, division  # makes these scripts backward compatible with python 2.6 and 2.7

DISPLACEMENT_X = "DISPLACEMENT_X"
DISPLACEMENT_Y = "DISPLACEMENT_Y"
DISPLACEMENT_Z = "DISPLACEMENT_Z"
DISPLACEMENT = ["DISPLACEMENT",DISPLACEMENT_X, DISPLACEMENT_Y, DISPLACEMENT_Z]

MESH_DISPLACEMENT_X = "MESH_DISPLACEMENT_X"
MESH_DISPLACEMENT_Y = "MESH_DISPLACEMENT_Y"
MESH_DISPLACEMENT_Z = "MESH_DISPLACEMENT_Z"
MESH_DISPLACEMENT = ["MESH_DISPLACEMENT",MESH_DISPLACEMENT_X, MESH_DISPLACEMENT_Y, MESH_DISPLACEMENT_Z]

VELOCITY_X = "VELOCITY_X"
VELOCITY_Y = "VELOCITY_Y"
VELOCITY_Z = "VELOCITY_Z"
VELOCITY = ["VELOCITY",VELOCITY_X,VELOCITY_Y, VELOCITY_Z]

POINT_LOAD_X = "POINT_LOAD_X"
POINT_LOAD_Y = "POINT_LOAD_Y"
POINT_LOAD_Z = "POINT_LOAD_Z"
POINT_LOAD = ["POINT_LOAD",POINT_LOAD_X,POINT_LOAD_Y, POINT_LOAD_Z]

REACTION_X = "REACTION_X"
REACTION_Y = "REACTION_Y"
REACTION_Z = "REACTION_Z"
REACTION = ["REACTION",REACTION_X, REACTION_Y, REACTION_Z]

EXTERNAL_FORCE_X = "EXTERNAL_FORCE_X"
EXTERNAL_FORCE_Y = "EXTERNAL_FORCE_Y"
EXTERNAL_FORCE_Z = "EXTERNAL_FORCE_Z"
EXTERNAL_FORCE = ["EXTERNAL_FORCE",EXTERNAL_FORCE_X, EXTERNAL_FORCE_Y, EXTERNAL_FORCE_Z]

PRESSURE = "PRESSURE"
YOUNG_MODULUS = "YOUNG_MODULUS"
POISSON_RATIO = "POISSON_RATIO"
DOMAIN_SIZE = "DOMAIN_SIZE"
DENSITY = "DENSITY"
VISCOSITY = "VISCOSITY"
TIME = "TIME"
DELTA_TIME = "DELTA_TIME"
TEMPERATURE = "TEMPERATURE"
