clear
rm CMakeCache.txt

cmake ..  \
-DCMAKE_BUILD_TYPE=Release  \
-DVERBOSE=1   \
-DINCOMPRESSIBLE_FLUID_APPLICATION=ON  \
-DMESHING_APPLICATION=ON \
-DEXTERNAL_SOLVERS_APPLICATION=ON \
-DPFEM_APPLICATION=ON \
-DSTRUCTURAL_APPLICATION=ON