.TH MPI_Comm_accept 3 "9/20/2012" " " "MPI"
.SH NAME
MPI_Comm_accept \-  Accept a request to form a new intercommunicator 
.SH SYNOPSIS
.nf
int MPI_Comm_accept(MPICH2_CONST char *port_name, MPI_Info info, int root, MPI_Comm comm,
                    MPI_Comm *newcomm)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B port_name 
- port name (string, used only on root) 
.PD 1
.PD 0
.TP
.B info 
- implementation-dependent information (handle, used only on root) 
.PD 1
.PD 0
.TP
.B root 
- rank in comm of root node (integer) 
.PD 1
.PD 0
.TP
.B IN 
- comm intracommunicator over which call is collective (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B newcomm 
- intercommunicator with client as remote group (handle) 
.PD 1

.SH THREAD AND INTERRUPT SAFETY

This routine is thread-safe.  This means that this routine may be
safely used by multiple threads without the need for any user-provided
thread locks.  However, the routine is not interrupt safe.  Typically,
this is due to the use of memory allocation routines such as 
.I malloc
or other non-MPICH runtime routines that are themselves not interrupt-safe.

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.

.SH ERRORS

All MPI routines (except 
.I MPI_Wtime
and 
.I MPI_Wtick
) return an error value;
C routines as the value of the function and Fortran routines in the last
argument.  Before the value is returned, the current MPI error handler is
called.  By default, this error handler aborts the MPI job.  The error handler
may be changed with 
.I MPI_Comm_set_errhandler
(for communicators),
.I MPI_File_set_errhandler
(for files), and 
.I MPI_Win_set_errhandler
(for
RMA windows).  The MPI-1 routine 
.I MPI_Errhandler_set
may be used but
its use is deprecated.  The predefined error handler
.I MPI_ERRORS_RETURN
may be used to cause error values to be returned.
Note that MPI does 
.B not
guarentee that an MPI program can continue past
an error; however, MPI implementations will attempt to continue whenever
possible.

.PD 0
.TP
.B MPI_SUCCESS 
- No error; MPI routine completed successfully.
.PD 1
.PD 0
.TP
.B MPI_ERR_INFO 
- Invalid Info 
.PD 1
.PD 0
.TP
.B MPI_ERR_COMM 
- Invalid communicator.  A common error is to use a null
communicator in a call (not even allowed in 
.I MPI_Comm_rank
).
.PD 1
.SH LOCATION
src/mpi/spawn/comm_accept.c
