/* 
 * File:   DEM_application_variables.h
 * Author: latorre
 *
 * Created on October 9, 2014, 10:54 AM
 */

#ifndef KRATOS_DEM_APPLICATION_VARIABLES_H
#define	KRATOS_DEM_APPLICATION_VARIABLES_H

#include "includes/define.h"
#include "includes/variables.h"
#include "includes/dem_variables.h"

namespace Kratos
{
  KRATOS_DEFINE_VARIABLE(WeakPointerVector< Element >, CONTINUUM_INI_NEIGHBOUR_ELEMENTS)
  KRATOS_DEFINE_VARIABLE(WeakPointerVector< Element >, NODE_TO_NEIGH_ELEMENT_POINTER)
     

  //constitutive law
  KRATOS_DEFINE_VARIABLE(std::string, DEM_CONTINUUM_CONSTITUTIVE_LAW_NAME)
  KRATOS_DEFINE_VARIABLE(std::string, DEM_DISCONTINUUM_CONSTITUTIVE_LAW_NAME)
  //KRATOS_DEFINE_VARIABLE( DEMConstitutiveLaw::Pointer, DEM_CONSTITUTIVE_LAW_POINTER )
   
  KRATOS_DEFINE_VARIABLE(std::string, PROBABILITY_DISTRIBUTION)
  
  // OPTIONS AND FLAGS
  
  KRATOS_DEFINE_VARIABLE(int, TOP)
  KRATOS_DEFINE_VARIABLE(int, BOTTOM)
  KRATOS_DEFINE_VARIABLE(int, FORCE_INTEGRATION_GROUP)
  KRATOS_DEFINE_VARIABLE(int, BOUNDING_BOX_OPTION)
  KRATOS_DEFINE_VARIABLE(int, ROTATION_OPTION)
  KRATOS_DEFINE_VARIABLE(int, ROTATION_SPRING_OPTION)
  KRATOS_DEFINE_VARIABLE(int, CRITICAL_TIME_OPTION)
  KRATOS_DEFINE_VARIABLE(int, VIRTUAL_MASS_OPTION)
  KRATOS_DEFINE_VARIABLE(int, SEARCH_CONTROL)
  KRATOS_DEFINE_VARIABLE(vector<int>, SEARCH_CONTROL_VECTOR)
  KRATOS_DEFINE_VARIABLE(int, LIMIT_SURFACE_OPTION)
  KRATOS_DEFINE_VARIABLE(int, LIMIT_CYLINDER_OPTION)
  KRATOS_DEFINE_VARIABLE(int, CLEAN_INDENT_OPTION)
  KRATOS_DEFINE_VARIABLE(int, TRIHEDRON_OPTION)
  KRATOS_DEFINE_VARIABLE(int, ROLLING_FRICTION_OPTION)
  KRATOS_DEFINE_VARIABLE(int, NEIGH_INITIALIZED)
  KRATOS_DEFINE_VARIABLE(int, TRIAXIAL_TEST_OPTION)
  KRATOS_DEFINE_VARIABLE(int, FIX_VELOCITIES_FLAG)
  KRATOS_DEFINE_VARIABLE(int, STRESS_STRAIN_OPTION)
  KRATOS_DEFINE_VARIABLE(double,DUMMY_DEBUG_DOUBLE)
  KRATOS_DEFINE_VARIABLE(int, DUMMY_DEBUG_INT)
  KRATOS_DEFINE_VARIABLE(int, PARTICLE_ID)
  KRATOS_DEFINE_VARIABLE(bool, CONTAINS_CLUSTERS)
  KRATOS_DEFINE_VARIABLE(bool, RANDOM_EULER_ANGLES)
  KRATOS_DEFINE_VARIABLE(int, LOCAL_RESOLUTION_METHOD)
    

  // *************** Continuum only BEGIN *************
  KRATOS_DEFINE_VARIABLE(Vector, DEM_AREA_VECTOR)
  KRATOS_DEFINE_VARIABLE(bool, DELTA_OPTION)
  KRATOS_DEFINE_VARIABLE(int, CASE_OPTION)
  KRATOS_DEFINE_VARIABLE(int, SKIN_SPHERE)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_COHESION)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_TENSION)
  
  KRATOS_DEFINE_VARIABLE(int, CONTACT_MESH_OPTION)
  //KRATOS_DEFINE_VARIABLE(int, FAILURE_CRITERION_OPTION)
  KRATOS_DEFINE_VARIABLE(int, CONCRETE_TEST_OPTION)
  KRATOS_DEFINE_VARIABLE(int, COHESIVE_GROUP)
  KRATOS_DEFINE_VARIABLE(int, plot_OPTIONS)
  KRATOS_DEFINE_VARIABLE(double, SURFACE_FRICTION_1)
  KRATOS_DEFINE_VARIABLE(double, SURFACE_FRICTION_2)
  KRATOS_DEFINE_VARIABLE(double, SURFACE_FRICTION_3)
  KRATOS_DEFINE_VARIABLE(double, SURFACE_FRICTION_4)
  KRATOS_DEFINE_VARIABLE(double, SURFACE_FRICTION_5)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_FRICTION_1)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_FRICTION_2)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_FRICTION_3)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_FRICTION_4)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_FRICTION_5)
  KRATOS_DEFINE_VARIABLE(int, IF_BOUNDARY_ELEMENT)
  KRATOS_DEFINE_VARIABLE(Vector, IF_BOUNDARY_FACE)
  KRATOS_DEFINE_VARIABLE(vector<int>, PARTICLE_CONTACT_FAILURE_ID)
  //KRATOS_DEFINE_VARIABLE(int, PARTICLE_FAILURE_ID)
  
  KRATOS_DEFINE_VARIABLE(double, PREDEFINED_SKIN)
  // *************** Continuum only END ***************

  // MATERIAL PARAMETERS

  KRATOS_DEFINE_VARIABLE(double, NODAL_MASS_COEFF)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_MOMENT_OF_INERTIA)
  KRATOS_DEFINE_VARIABLE(double, ROLLING_FRICTION)
  KRATOS_DEFINE_VARIABLE(double, HISTORICAL_MIN_K)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_INERTIA)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_DENSITY)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_FRICTION)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_STATIC_FRICTION_COEF)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_DYNAMIC_FRICTION_COEF)
  KRATOS_DEFINE_VARIABLE(double, COEFFICIENT_OF_RESTITUTION)
  KRATOS_DEFINE_VARIABLE(double, PARTICLE_ROTATION_DAMP_RATIO)
  KRATOS_DEFINE_VARIABLE(double, SQRT_OF_MASS)
  KRATOS_DEFINE_VARIABLE(double, LN_OF_RESTITUTION_COEFF)
  KRATOS_DEFINE_VARIABLE(double, DAMPING_GAMMA)

  // *************** Continuum only BEGIN *************
  KRATOS_DEFINE_VARIABLE(double, SLOPE_FRACTION_N1)
  KRATOS_DEFINE_VARIABLE(double, SLOPE_FRACTION_N2)
  KRATOS_DEFINE_VARIABLE(double, SLOPE_FRACTION_N3)
  KRATOS_DEFINE_VARIABLE(double, SLOPE_LIMIT_COEFF_C1)
  KRATOS_DEFINE_VARIABLE(double, SLOPE_LIMIT_COEFF_C2)
  KRATOS_DEFINE_VARIABLE(double, SLOPE_LIMIT_COEFF_C3)
  KRATOS_DEFINE_VARIABLE(double, YOUNG_MODULUS_PLASTIC)
  KRATOS_DEFINE_VARIABLE(double, PLASTIC_YIELD_STRESS)
  KRATOS_DEFINE_VARIABLE(double, DAMAGE_FACTOR)
  KRATOS_DEFINE_VARIABLE(double, SHEAR_ENERGY_COEF)
  KRATOS_DEFINE_VARIABLE(double, DONZE_G1)
  KRATOS_DEFINE_VARIABLE(double, DONZE_G2)
  KRATOS_DEFINE_VARIABLE(double, DONZE_G3)
  KRATOS_DEFINE_VARIABLE(double, DONZE_MAX_DEF)
  KRATOS_DEFINE_VARIABLE(double, CONTACT_FAILURE)
  KRATOS_DEFINE_VARIABLE(double, CONTACT_ORIENTATION)
  KRATOS_DEFINE_VARIABLE(double, CONTACT_SIGMA)
  KRATOS_DEFINE_VARIABLE(double, CONTACT_TAU)
  KRATOS_DEFINE_VARIABLE(double, FAILURE_CRITERION_STATE)
  KRATOS_DEFINE_VARIABLE(double, UNIDIMENSIONAL_DAMAGE)
  KRATOS_DEFINE_VARIABLE(double, CONTACT_SIGMA_MIN)
  KRATOS_DEFINE_VARIABLE(double, CONTACT_TAU_ZERO)
  KRATOS_DEFINE_VARIABLE(double, CONTACT_INTERNAL_FRICC)
  KRATOS_DEFINE_VARIABLE(double, LOW_POISSON_FORCE)
  KRATOS_DEFINE_VARIABLE(double, HIGH_POISSON_FORCE)

  // *************** Continuum only END *************

  // GEOMETRIC PARAMETERS


  // *************** Continuum only BEGIN *************
  KRATOS_DEFINE_VARIABLE(double, LOCAL_CONTACT_AREA_HIGH)
  KRATOS_DEFINE_VARIABLE(double, LOCAL_CONTACT_AREA_LOW)
  KRATOS_DEFINE_VARIABLE(double, MEAN_CONTACT_AREA)
  KRATOS_DEFINE_VARIABLE(double, REPRESENTATIVE_VOLUME)
  KRATOS_DEFINE_VARIABLE(Vector, PARTICLE_INITIAL_DELTA)
  KRATOS_DEFINE_VARIABLE(Vector, PARTICLE_CONTACT_DELTA)

  KRATOS_DEFINE_VARIABLE(VectorArray3Double, ARROW_POINT)
  // *************** Continuum only END ***************
  
  
  // INLET PARAMETERS
    
  KRATOS_DEFINE_VARIABLE(double,INLET_START_TIME)    
  KRATOS_DEFINE_VARIABLE(double,INLET_STOP_TIME)
  KRATOS_DEFINE_VARIABLE(double,INLET_NUMBER_OF_PARTICLES)
  KRATOS_DEFINE_VARIABLE(double,STANDARD_DEVIATION)
  KRATOS_DEFINE_VARIABLE(double,MAX_RAND_DEVIATION_ANGLE)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(INLET_INITIAL_VELOCITY)
    

  // KINEMATICS

  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_ROTATION_ANGLE)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(EULER_ANGLES)
  KRATOS_DEFINE_VARIABLE(double, ORIENTATION_REAL)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(ORIENTATION_IMAG)
  KRATOS_DEFINE_VARIABLE(Vector, INITIAL_AXES_TRACKING)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_NORMAL_DIR_1)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_NORMAL_DIR_2)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_NORMAL_DIR_3)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_NORMAL_DIR_4)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_NORMAL_DIR_5)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_POINT_COOR_1)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_POINT_COOR_2)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_POINT_COOR_3)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_POINT_COOR_4)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_POINT_COOR_5)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(CYLINDER_AXIS_DIR_1)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(CYLINDER_AXIS_DIR_2)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(CYLINDER_AXIS_DIR_3)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(CYLINDER_AXIS_DIR_4)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(CYLINDER_AXIS_DIR_5)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(INITIAL_BASE_CYLINDER_CENTRE_1)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(INITIAL_BASE_CYLINDER_CENTRE_2)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(INITIAL_BASE_CYLINDER_CENTRE_3)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(INITIAL_BASE_CYLINDER_CENTRE_4)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(INITIAL_BASE_CYLINDER_CENTRE_5)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_RADIUS_1)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_RADIUS_2)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_RADIUS_3)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_RADIUS_4)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_RADIUS_5)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_VELOCITY_1)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_VELOCITY_2)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_VELOCITY_3)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_VELOCITY_4)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_VELOCITY_5)
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_ANGULAR_VELOCITY_1)  
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_ANGULAR_VELOCITY_2) 
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_ANGULAR_VELOCITY_3) 
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_ANGULAR_VELOCITY_4) 
  KRATOS_DEFINE_VARIABLE(double, CYLINDER_ANGULAR_VELOCITY_5) 
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(DELTA_DISPLACEMENT)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(DELTA_ROTA_DISPLACEMENT)
  KRATOS_DEFINE_VARIABLE(double, VELOCITY_START_TIME) 
  KRATOS_DEFINE_VARIABLE(double, VELOCITY_STOP_TIME)
  KRATOS_DEFINE_VARIABLE(double, ANGULAR_VELOCITY_START_TIME) 
  KRATOS_DEFINE_VARIABLE(double, ANGULAR_VELOCITY_STOP_TIME)

  // FORCE AND MOMENTUM

  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(TOTAL_FORCES)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_SURFACE_CONTACT_FORCES_1)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_SURFACE_CONTACT_FORCES_2)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_SURFACE_CONTACT_FORCES_3)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_SURFACE_CONTACT_FORCES_4)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_SURFACE_CONTACT_FORCES_5)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_CYLINDER_CONTACT_FORCES_1)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_CYLINDER_CONTACT_FORCES_2)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_CYLINDER_CONTACT_FORCES_3)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_CYLINDER_CONTACT_FORCES_4)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_CYLINDER_CONTACT_FORCES_5)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARTICLE_MOMENT)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(MAX_ROTA_MOMENT)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(ELASTIC_FORCES)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(CONTACT_FORCES)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(RIGID_ELEMENT_FORCE)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(TANGENTIAL_ELASTIC_FORCES)
  KRATOS_DEFINE_VARIABLE(double, DEM_PRESSURE) 
  KRATOS_DEFINE_VARIABLE(double, DEM_NODAL_AREA)
    
  // ENERGY

  KRATOS_DEFINE_VARIABLE( double, PARTICLE_ELASTIC_ENERGY )
  KRATOS_DEFINE_VARIABLE( double, PARTICLE_KINEMATIC_ENERGY )
  KRATOS_DEFINE_VARIABLE( double, PARTICLE_GRAVITATIONAL_ENERGY )
  KRATOS_DEFINE_VARIABLE( double, PARTICLE_INELASTIC_VISCODAMPING_ENERGY )
  KRATOS_DEFINE_VARIABLE( double, PARTICLE_INELASTIC_FRICTIONAL_WORK )

  // *************** Continuum only BEGIN *************
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(INITIAL_ROTA_MOMENT)
  KRATOS_DEFINE_VARIABLE(Vector, PARTICLE_BLOCK_CONTACT_FORCE)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(EXTERNAL_APPLIED_FORCE)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(LOCAL_CONTACT_FORCE)
  KRATOS_DEFINE_VARIABLE(VectorArray3Double, PARTICLE_CONTACT_FORCES )

  // CONCRETE TEST

  KRATOS_DEFINE_VARIABLE(double, FIXED_VEL_TOP)
  KRATOS_DEFINE_VARIABLE(double, FIXED_VEL_BOT)
  KRATOS_DEFINE_VARIABLE(double, AREA_VERTICAL_TAPA)
  KRATOS_DEFINE_VARIABLE(double, AREA_VERTICAL_CENTRE)

  // TENSION

  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_XX)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_XY)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_XZ)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_YX)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_YY)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_YZ)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_ZX)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_ZY)
  KRATOS_DEFINE_VARIABLE(double, DEM_STRESS_ZZ)
  // *************** Continuum only END *************

  // Possible future blocks (no FEM) interaction

  KRATOS_DEFINE_VARIABLE(Vector, PARTICLE_BLOCK_CONTACT_FAILURE_ID)
  KRATOS_DEFINE_VARIABLE(Vector, PARTICLE_BLOCK_IF_INITIAL_CONTACT)
  KRATOS_DEFINE_VARIABLE(WeakPointerVector<Element >, NEIGHBOUR_PARTICLE_BLOCK_ELEMENTS)
  KRATOS_DEFINE_VARIABLE(WeakPointerVector<Condition >,     NEIGHBOUR_RIGID_FACES)
  KRATOS_DEFINE_VARIABLE(WeakPointerVector<Element >, NEIGHBOUR_PARTICLE_OF_RIGID_FACE)
  KRATOS_DEFINE_VARIABLE(Vector,   NEIGHBOUR_RIGID_FACES_PRAM)
  KRATOS_DEFINE_VARIABLE(Vector,   NEIGHBOUR_RIGID_FACES_ELASTIC_CONTACT_FORCE)
  KRATOS_DEFINE_VARIABLE(Vector,   NEIGHBOUR_RIGID_FACES_TOTAL_CONTACT_FORCE)

  // DUMMIES INT AND DOUBLE VARIABLES

  KRATOS_DEFINE_VARIABLE(int, DUMMY_SWITCH)
  KRATOS_DEFINE_VARIABLE(double, DUMMY_FORCES)
  KRATOS_DEFINE_VARIABLE(double, DUMMY_LOCAL_AXES)
  
  // EXPORTS
  
  KRATOS_DEFINE_VARIABLE(double, EXPORT_ID)
  KRATOS_DEFINE_VARIABLE(double, EXPORT_PARTICLE_FAILURE_ID)
  KRATOS_DEFINE_VARIABLE(double, EXPORT_SKIN_SPHERE)
  KRATOS_DEFINE_VARIABLE(int, PRINT_EXPORT_ID)
  KRATOS_DEFINE_VARIABLE(int, PRINT_SKIN_SPHERE)
  
  // For DEM_FEM Element
  
  KRATOS_DEFINE_VARIABLE(double, LOCAL_DAMP_RATIO)
  
  // For the DEM_Clusters Element
  
  KRATOS_DEFINE_VARIABLE(double, CLUSTER_MASS)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PRINCIPAL_MOMENTS_OF_INERTIA)
  KRATOS_DEFINE_VARIABLE(double, CHARACTERISTIC_LENGTH)

  // DUMMY VARIABLES FOR CALCULATE
  KRATOS_DEFINE_VARIABLE(double, CALCULATE_COMPUTE_NEW_NEIGHBOURS_HISTORICAL_DATA)
  KRATOS_DEFINE_VARIABLE(double, CALCULATE_COMPUTE_NEW_RIGID_FACE_NEIGHBOURS_HISTORICAL_DATA)
  KRATOS_DEFINE_VARIABLE(double, CALCULATE_SET_INITIAL_DEM_CONTACTS)
  KRATOS_DEFINE_VARIABLE(double, CALCULATE_SET_INITIAL_FEM_CONTACTS)
  
  
  //Cfeng,131013,RigidFace
  
  KRATOS_DEFINE_VARIABLE(double, RIGID_FACE_ROTA_SPEED)
  KRATOS_DEFINE_VARIABLE(double, RIGID_FACE_AXIAL_SPEED)
  KRATOS_DEFINE_VARIABLE(int,    RIGID_FACE_PROP_ID)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(RIGID_FACE_ROTA_ORIGIN_COORD)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(RIGID_FACE_ROTA_AXIAL_DIR)
  KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(RIGID_FACE_ROTA_GLOBAL_VELOCITY)
  KRATOS_DEFINE_VARIABLE(double, RIGID_FACE_BEGIN_TIME)
  KRATOS_DEFINE_VARIABLE(double, RIGID_FACE_END_TIME)
  KRATOS_DEFINE_VARIABLE(int, RIGID_FACE_FLAG)
  KRATOS_DEFINE_VARIABLE(Vector, RIGID_FACE_COMPUTE_MOVEMENT)
  
  //SLS DEM-FEM
  KRATOS_DEFINE_VARIABLE(double, WALL_FRICTION)
  KRATOS_DEFINE_VARIABLE(double, SHEAR_STRESS)
  KRATOS_DEFINE_VARIABLE(double, NON_DIMENSIONAL_VOLUME_WEAR)
  KRATOS_DEFINE_VARIABLE(double, IMPACT_WEAR)
  KRATOS_DEFINE_VARIABLE(double, SEVERITY_OF_WEAR)
  KRATOS_DEFINE_VARIABLE(double, BRINELL_HARDNESS)
  KRATOS_DEFINE_VARIABLE(bool  , PRINT_WEAR)
  KRATOS_DEFINE_VARIABLE(double, IMPACT_WEAR_SEVERITY)
  KRATOS_DEFINE_VARIABLE(double, WALL_COHESION)
  //BOUNDING BOX
  KRATOS_DEFINE_VARIABLE(double, BOUNDING_BOX_START_TIME)
  KRATOS_DEFINE_VARIABLE(double, BOUNDING_BOX_STOP_TIME)
  
  //OPTIMIZATION 
  KRATOS_DEFINE_VARIABLE(double, TOTAL_CONTACT_DISTANCES)

  //MSI DEM-FEM & OTHERS
  KRATOS_DEFINE_VARIABLE(Vector, CAUCHY_STRESS_VECTOR)
  KRATOS_DEFINE_VARIABLE(Vector, PK2_STRESS_VECTOR)
  KRATOS_DEFINE_VARIABLE(Matrix, ALMANSI_STRAIN_TENSOR)
  KRATOS_DEFINE_VARIABLE(Vector, GREEN_LAGRANGE_STRAIN_VECTOR)
  KRATOS_DEFINE_VARIABLE(Vector, ALMANSI_STRAIN_VECTOR)
  KRATOS_DEFINE_VARIABLE(Matrix, MATERIAL_STIFFNESS_MATRIX)
  KRATOS_DEFINE_VARIABLE(Matrix, GEOMETRIC_STIFFNESS_MATRIX)
  KRATOS_DEFINE_VARIABLE(double, VON_MISES_STRESS)
  
  // *************** Thermal only BEGIN *************
  KRATOS_DEFINE_VARIABLE(double, HEATFLUX)
  KRATOS_DEFINE_VARIABLE(double, THERMAL_CONDUCTIVITY)
  // *************** Thermal only END ***************  
  
class DEMFlags
  {
  public:
    KRATOS_DEFINE_LOCAL_FLAG(HAS_ROTATION);
    KRATOS_DEFINE_LOCAL_FLAG(HAS_ROTATION_SPRING);
    KRATOS_DEFINE_LOCAL_FLAG(HAS_ROLLING_FRICTION);
    //KRATOS_DEFINE_LOCAL_FLAG(HAS_INITIALIZED_VARIABLES);
    KRATOS_DEFINE_LOCAL_FLAG(HAS_CRITICAL_TIME);  
    KRATOS_DEFINE_LOCAL_FLAG(FIXED_VEL_X); 
    KRATOS_DEFINE_LOCAL_FLAG(FIXED_VEL_Y); 
    KRATOS_DEFINE_LOCAL_FLAG(FIXED_VEL_Z); 
    KRATOS_DEFINE_LOCAL_FLAG(FIXED_ANG_VEL_X); 
    KRATOS_DEFINE_LOCAL_FLAG(FIXED_ANG_VEL_Y); 
    KRATOS_DEFINE_LOCAL_FLAG(FIXED_ANG_VEL_Z);
    KRATOS_DEFINE_LOCAL_FLAG(BELONGS_TO_A_CLUSTER);
    
  };  
}


#endif	/* KRATOS_DEM_APPLICATION_VARIABLES_H */

