#include "co_simulation_application_variables.h"

namespace Kratos
{

KRATOS_CREATE_VARIABLE(double, SCALAR_DISPLACEMENT);
KRATOS_CREATE_VARIABLE(double, SCALAR_ROOT_POINT_DISPLACEMENT);
KRATOS_CREATE_VARIABLE(double, SCALAR_REACTION);
KRATOS_CREATE_VARIABLE(double, SCALAR_FORCE);
KRATOS_CREATE_VARIABLE(double, SCALAR_VOLUME_ACCELERATION);


}