#include "co_simulation_application_variables.h"

namespace Kratos
{

KRATOS_CREATE_VARIABLE(double, SCALAR_DISPLACEMENT);
KRATOS_CREATE_VARIABLE(double, SCALAR_ROOT_POINT_DISPLACEMENT);
KRATOS_CREATE_VARIABLE(double, SCALAR_REACTION);
KRATOS_CREATE_VARIABLE(double, SCALAR_FORCE);
KRATOS_CREATE_VARIABLE(double, SCALAR_VOLUME_ACCELERATION);

KRATOS_CREATE_VARIABLE(Vector, DISPLACEMENT_VECTOR)
KRATOS_CREATE_VARIABLE(Vector, ROOT_POINT_DISPLACEMENT_VECTOR)
KRATOS_CREATE_VARIABLE(Vector, REACTION_VECTOR)
KRATOS_CREATE_VARIABLE(Vector, FORCE_VECTOR)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(RESULTANT_FORCE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(RESULTANT_MOMENT)
KRATOS_CREATE_VARIABLE(Vector, RESULTANT_FORCE_MOMENT)

KRATOS_CREATE_VARIABLE(int, INTERFACE_EQUATION_ID);
KRATOS_CREATE_VARIABLE(int, EXPLICIT_EQUATION_ID);

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MIDDLE_VELOCITY)
}