#include "pfem_fluid_dynamic_application_variables.h"

namespace Kratos
{
    KRATOS_CREATE_VARIABLE(double,TAUONE)
    KRATOS_CREATE_VARIABLE(double,TAUTWO)
    KRATOS_CREATE_VARIABLE(double,SUBSCALE_PRESSURE)

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SUBSCALE_VELOCITY)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VORTICITY)
}
