#include "iga_structural_mechanics_application_variables.h"

namespace Kratos
{
	//
	KRATOS_CREATE_VARIABLE(double, INTEGRATION_WEIGHT)
	//Values of Shapefunctions N
	KRATOS_CREATE_VARIABLE(Vector, SHAPE_FUNCTION_VALUES)
	//Values of Shapefunctionderivatives in local space DN_De
	KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_DERIVATIVES)
  KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_SECOND_DERIVATIVES)
	KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_DERIVATIVES_MASTER)
	KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_DERIVATIVES_SLAVE)

	KRATOS_CREATE_VARIABLE(double, PENALTY_FACTOR)
	KRATOS_CREATE_VARIABLE(Vector, TANGENTS)

	KRATOS_CREATE_VARIABLE(int, DISPLACEMENT_ROTATION_FIX)
	KRATOS_CREATE_VARIABLE(int, LOAD_TYPE)

	//KRATOS_CREATE_VARIABLE(std::string, CONDITION_TYPE_DEFINITION)
	KRATOS_CREATE_VARIABLE(double, DISTRIBUTED_LOAD_FACTOR)
}
