.TH MPE_Log_get_state_eventIDs 4 "6/15/2009" " " "MPE"
.SH NAME
MPE_Log_get_state_eventIDs \-  Get a pair of event numbers to be used to define STATE drawable through MPE_Describe_state(). 
.SH SYNOPSIS
.nf
int MPE_Log_get_state_eventIDs( int *statedef_startID,
                                int *statedef_finalID )
.fi
.SH INPUT/OUTPUT PARAMETERS
.PD 0
.TP
.B statedef_startID  
- starting eventID for the definition of state drawable.
.PD 1
.PD 0
.TP
.B statedef_finalID  
- ending eventID for the definition of state drawable.
.PD 1

.SH NOTES
This routine is provided to ensure that users are
using unique event numbers.  It relies on all packages using this
routine.

This function is threadsafe.
.SH LOCATION
../src/logging/src/mpe_log.c
