//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Ignasi de Pouplana
//

#if defined(KRATOS_PYTHON)

// System includes
#include <pybind11/pybind11.h>

// Project includes
#include "includes/define.h"
#include "includes/define_python.h"

// Application includes
#include "custom_python/add_custom_processes_to_python.h"
#include "laserdrilling_application.h"

namespace Kratos
{

namespace Python
{

namespace py = pybind11;

PYBIND11_MODULE(KratosLaserDrillingApplication,m)
{

    py::class_<KratosLaserDrillingApplication,
           KratosLaserDrillingApplication::Pointer,
           KratosApplication >(m,"KratosLaserDrillingApplication")
           .def(py::init<>())
           ;
    AddCustomProcessesToPython(m);

    // Registering variables in python
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THERMAL_ENERGY)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THERMAL_ENERGY_PER_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MATERIAL_THERMAL_ENERGY_PER_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THERMAL_DECOMPOSITION)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THERMAL_COUNTER)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THERMAL_ENERGY_PER_VOLUME_THRESHOLD)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ALPHA_THRESHOLD)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DECOMPOSITION_LAW)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DECOMPOSED_ELEMENTAL_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ELEMENTAL_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, A_COEFFICIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, EA_COEFFICIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, R_GAS_CONSTANT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, M_COEFFICIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, N_COEFFICIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DECOMPOSITION_LAW_REFERENCE_TEMPERATURE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DECOMPOSITION_LAW_CONSTANT_1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DECOMPOSITION_LAW_CONSTANT_2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DECOMPOSED_NODE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, IONIZATION_ALPHA)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THERMAL_DEPTH)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ABLATION_THRESHOLD)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, PENETRATION_DEPTH)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, PRE_EVAPORATION_TEMPERATURE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, OPTICAL_PENETRATION_DEPTH)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ENERGY_PER_VOLUME_THRESHOLD)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ENERGY_PER_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ENTHALPY_ENERGY_PER_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, IONIZATION_ENERGY_PER_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, REFRACTIVE_INDEX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, VAPORISATION_TEMPERATURE)

}

}  // namespace Python.

}  // namespace Kratos.

#endif // KRATOS_PYTHON defined
