@startuml
'https://plantuml.com/class-diagram

abstract class Scheme
class GeoMechanicsTimeIntegrationScheme
{
    - std::vector<FirstOrderScalarVariable> firstOrderScalarVariables;
    - std::vector<SecondOrderVectorVariable> secondOrderVectorVariables;

    virtual void UpdateVariablesDerivatives() = 0;
}
Scheme <|-- GeoMechanicsTimeIntegrationScheme

class BackwardEulerScheme
{
    void UpdateVariablesDerivatives() override;
}
class BackwardEulerQuasistaticPwScheme
class BackwardEulerQuasistaticUPwScheme
class BackwardEulerQuasistaticTScheme

GeoMechanicsTimeIntegrationScheme <|-- BackwardEulerScheme
BackwardEulerScheme <|-- BackwardEulerQuasistaticPwScheme
BackwardEulerScheme <|-- BackwardEulerQuasistaticUPwScheme
BackwardEulerScheme <|-- BackwardEulerQuasistaticTScheme

class GeneralizedNewmarkScheme
{
    void UpdateVariablesDerivatives() override;
}
class NewmarkQuasistaticPwScheme
class GeneralizedNewmarkTScheme
class NewmarkQuasistaticUPwScheme
class NewmarkDynamicUPwScheme
class NewmarkQuasistaticDampedUPwScheme

GeoMechanicsTimeIntegrationScheme <|-- GeneralizedNewmarkScheme
GeneralizedNewmarkScheme <|-- NewmarkQuasistaticPwScheme
GeneralizedNewmarkScheme <|-- GeneralizedNewmarkTScheme
GeneralizedNewmarkScheme <|-- NewmarkQuasistaticUPwScheme
NewmarkQuasistaticUPwScheme <|-- NewmarkDynamicUPwScheme
NewmarkQuasistaticUPwScheme <|-- NewmarkQuasistaticDampedUPwScheme

@enduml