//    |  /           | 
//    ' /   __| _` | __|  _ \   __| 
//    . \  |   (   | |   (   |\__ \.
//   _|\_\_|  \__,_|\__|\___/ ____/ 
//                   Multi-Physics  
//
//  License:		 BSD License 
//					 Kratos default license: kratos/license.txt
//
//  Main authors:    Riccardo Rossi
//


// System includes

// External includes
#include <boost/python.hpp>


// Project includes
#include "includes/define.h"
#include "includes/ublas_interface.h"
#include "containers/data_value_container.h"
#include "containers/flags.h"
#include "includes/c2c_variables.h"
#include "python/add_c2c_variables_to_python.h"
#include "utilities/timer.h"




namespace Kratos
{

namespace Python
{
using namespace boost::python;

void  AddC2CVariablesToPython()
{
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  SOLID_TEMPERATURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  FLUID_TEMPERATURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  AVERAGE_TEMPERATURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  INLET_TEMPERATURE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_AVERAGE_TEMPERATURE)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(   LAST_AIR)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(   PRESSURES)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_DENSITY)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_SPECIFIC_HEAT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_THICKNESS)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_SFACT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_VFACT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_CONDUCTIVITY)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_HTC_ENVIRONMENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_TEMPERATURE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  MOLD_INNER_TEMPERATURE)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( HTC)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SOLIDFRACTION )
	KRATOS_REGISTER_IN_PYTHON_VARIABLE( SOLIDFRACTION_RATE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SOLIDIF_TIME  )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SOLIDIF_MODULUS  )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FILLTIME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MACRO_POROSITY  )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHRINKAGE_POROSITY  )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MAX_VEL  )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FRONT_MEETING)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LIQUID_TIME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FLOW_LENGTH)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FLOW_LENGTH2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( COOLING_RATE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LIQUID_TO_SOLID_TIME)
	KRATOS_REGISTER_IN_PYTHON_VARIABLE( TIME_CRT)
	KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINKMARK)
	KRATOS_REGISTER_IN_PYTHON_VARIABLE(COLD_SHUTS)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(NIYAMA)
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(TEMPERATURE_GRADIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(INITIAL_TEMPERATURE)
}
}  // namespace Python.
} // Namespace Kratos
