//    |  /           | 
//    ' /   __| _` | __|  _ \   __| 
//    . \  |   (   | |   (   |\__ \.
//   _|\_\_|  \__,_|\__|\___/ ____/ 
//                   Multi-Physics  
//
//  License:		 BSD License 
//			 Kratos default license: kratos/license.txt
//
//  Main authors:  Josep Maria Carbonell    
//


// System includes

// External includes
#include <boost/python.hpp>


// Project includes
#include "includes/define.h"
#include "includes/ublas_interface.h"
#include "includes/variables.h"
#include "includes/mat_variables.h"
#include "python/add_mat_variables_to_python.h"

//commented variables are registered in add_containers_to_python.cpp

namespace Kratos
{

  namespace Python
  {
    using namespace boost::python;

    void  AddMATVariablesToPython()
    {
      
      //registering variables in python

      //solution
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONSTITUTIVE_LAW_NAME )
	
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( IMPLEX_CONTACT )
      //elasticity
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( POISSON_RATIO )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DENSITY )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( THICKNESS )
      //KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_YOUNG_MODULUS )
      //KRATOS_REGISTER_IN_PYTHON_VARIABLE( BULK_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHEAR_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAME_MU )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAME_LAMBDA )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( C10 )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( C20 )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( C30 )

      //viscosity
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( VISCOSITY )

      //damage
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DAMAGE_VARIABLE )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DAMAGE_THRESHOLD )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRENGTH_RATIO )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( FRACTURE_ENERGY )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( RESIDUAL_STRENGTH )

      //plasticity
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_STRAIN )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DELTA_PLASTIC_STRAIN )      
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( NORM_ISOCHORIC_STRESS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_STRAIN_RATE )

      //hardening
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( ISOTROPIC_HARDENING_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( KINEMATIC_HARDENING_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( HARDENING_EXPONENT )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( REFERENCE_HARDENING_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( INFINITY_HARDENING_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SOFTENING_SLOPE )

      //baker-johnson-cook parameters
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( JC_PARAMETER_A )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( JC_PARAMETER_B )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( JC_PARAMETER_C )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( JC_PARAMETER_m )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( JC_PARAMETER_n )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( JC_PARAMETER_K ) 

      //thermal
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DELTA_PLASTIC_STRAIN )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( REFERENCE_CONDUCTIVITY )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( HARDNESS_CONDUCTIVITY )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( REFERENCE_TEMPERATURE )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( MELD_TEMPERATURE )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_DISSIPATION )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DELTA_PLASTIC_DISSIPATION )

      //anisotropy
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS_X )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS_Y )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS_Z )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHEAR_MODULUS_XY )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHEAR_MODULUS_YZ )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHEAR_MODULUS_XZ )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( POISSON_RATIO_XY )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( POISSON_RATIO_YZ )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( POISSON_RATIO_XZ )
      
      KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MATERIAL_ORIENTATION_DX )
      KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MATERIAL_ORIENTATION_DY )
      KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MATERIAL_ORIENTATION_DZ )

      //critical state
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( CRITICAL_STATE_LINE )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRE_CONSOLIDATION_STRESS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( OVER_CONSOLIDATION_RATIO )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( INITIAL_SHEAR_MODULUS )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( NORMAL_COMPRESSION_SLOPE )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SWELLING_SLOPE )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( ALPHA_SHEAR )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SPACING_RATIO )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHAPE_PARAMETER )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( INITIAL_BONDING )
			KRATOS_REGISTER_IN_PYTHON_VARIABLE( DEGRADATION_THRESHOLD )
			KRATOS_REGISTER_IN_PYTHON_VARIABLE( DEGRADATION_RATE_COMPRESSION )
			KRATOS_REGISTER_IN_PYTHON_VARIABLE( DEGRADATION_RATE_SHEAR )
			KRATOS_REGISTER_IN_PYTHON_VARIABLE( ALPHA_TENSILE )
			KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_DEVIATORIC_STRAIN_HARDENING )

      //strain
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DETERMINANT_F )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( DEFORMATION_GRADIENT )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( GREEN_LAGRANGE_STRAIN_VECTOR )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( GREEN_LAGRANGE_STRAIN_TENSOR )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( ALMANSI_STRAIN_VECTOR )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( ALMANSI_STRAIN_TENSOR )

      //stress
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( KIRCHHOFF_STRESS_VECTOR )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( KIRCHHOFF_STRESS_TENSOR )

      KRATOS_REGISTER_IN_PYTHON_VARIABLE( CAUCHY_STRESS_VECTOR )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( CAUCHY_STRESS_TENSOR )

      KRATOS_REGISTER_IN_PYTHON_VARIABLE( PK2_STRESS_VECTOR )
      KRATOS_REGISTER_IN_PYTHON_VARIABLE( PK2_STRESS_TENSOR )
      
    }
  }  // namespace Python.
} // Namespace Kratos


