#!/bin/bash

CONFPATH="/etc/ld.so.conf.d"
CONFFILE="kratos.conf"
#CONFPATH="${HOME}"

if [ -e ${CONFPATH}/${CONFFILE} ]; then
 rm -f ${CONFPATH}/${CONFFILE}
fi

##pwd
##echo "/opt/kratos/libs" > ${CONFPATH}/${CONFFILE}
cp /opt/kratos/packaging/kratos.conf ${CONFPATH}/${CONFFILE}
ldconfig

cd /opt/kratos/
python script.py install
python script.py clean
rm /opt/kratos/script.py
rm -rf /opt/kratos/KratosMultiphysics
rm -rf /opt/kratos/packaging
rm -rf /opt/kratos/build


