#ifndef VEXCL_BACKEND_OPENCL_DEFINES_HPP
#define VEXCL_BACKEND_OPENCL_DEFINES_HPP

#ifndef __CL_ENABLE_EXCEPTIONS
#  define __CL_ENABLE_EXCEPTIONS
#endif

#ifndef CL_USE_DEPRECATED_OPENCL_2_0_APIS
#  define CL_USE_DEPRECATED_OPENCL_2_0_APIS
#endif

#endif
