/*
//  KRATOS  _____________
//         /  _/ ____/   |
//         / // / __/ /| |
//       _/ // /_/ / ___ |
//      /___/\____/_/  |_| Application
//
//  Main authors:   Thomas Oberbichler
*/

#if defined(KRATOS_PYTHON)

// System includes

// External includes
#include <pybind11/pybind11.h>

// Project includes
#include "includes/define.h"
#include "iga_application.h"
#include "iga_application_variables.h"
#include "custom_python/add_custom_utilities_to_python.h"

namespace Kratos {
namespace Python {

PYBIND11_MODULE(KratosIgaApplication, m)
{
    namespace py = pybind11;

    py::class_<KratosIgaApplication, KratosIgaApplication::Pointer, 
        KratosApplication>(m, "KratosIgaApplication")
        .def(py::init<>())
    ;

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, BREP_ID)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, NURBS_CONTROL_POINT_WEIGHT)

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, COORDINATES)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, LOCAL_COORDINATES)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, TANGENTS)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, TANGENTS_SLAVE)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CROSS_AREA)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, PRESTRESS_CAUCHY)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHAPE_FUNCTION_VALUES)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHAPE_FUNCTION_LOCAL_DERIVATIVES)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHAPE_FUNCTION_LOCAL_SECOND_DERIVATIVES)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHAPE_FUNCTION_LOCAL_THIRD_DERIVATIVES)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHAPE_FUNCTION_VALUES_SLAVE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHAPE_FUNCTION_LOCAL_DERIVATIVES_SLAVE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHAPE_FUNCTION_LOCAL_SECOND_DERIVATIVES_SLAVE)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, RAYLEIGH_ALPHA)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, RAYLEIGH_BETA)

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, POINT_LOAD)
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, LINE_LOAD)
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, SURFACE_LOAD)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, PENALTY_FACTOR)
    
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_11)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_12)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_22)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_23)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_13)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_TOP_11)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_TOP_12)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_TOP_22)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_TOP_23)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_TOP_13)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_BOTTOM_11)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_BOTTOM_12)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_BOTTOM_22)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_BOTTOM_23)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, STRESS_CAUCHY_BOTTOM_13)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INTERNAL_FORCE_11)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INTERNAL_FORCE_12)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INTERNAL_FORCE_22)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INTERNAL_MOMENT_11)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INTERNAL_MOMENT_12)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INTERNAL_MOMENT_22)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHEAR_FORCE_1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SHEAR_FORCE_2)

    // DOF
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, W_BAR)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, W_BAR_REACTION)

    AddCustomUtilitiesToPython(m);
}

} // namespace Python
} // namespace Kratos

#endif // defined(KRATOS_PYTHON)
