#include "nurbs_brep_application_variables.h"

namespace Kratos
{
  //
  KRATOS_CREATE_VARIABLE(double, CONTROL_POINT_WEIGHT)

  KRATOS_CREATE_VARIABLE(double, INTEGRATION_WEIGHT)

  KRATOS_CREATE_VARIABLE(Vector, TANGENTS_BASIS_VECTOR)

  KRATOS_CREATE_VARIABLE(Vector, LOCAL_PARAMETERS)
  KRATOS_CREATE_VARIABLE(int, FACE_BREP_ID)

  KRATOS_CREATE_VARIABLE(Vector, CONTROL_POINT_IDS)

  ////Values of Shapefunctions N
  KRATOS_CREATE_VARIABLE(Vector, SHAPE_FUNCTION_VALUES)
  ////Values of Shapefunctionderivatives in local space DN_De
  KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_DERIVATIVES)
  KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_SECOND_DERIVATIVES)

  KRATOS_CREATE_VARIABLE(Vector, LOCATION_SLAVE)

  KRATOS_CREATE_VARIABLE(Vector, TANGENTS_BASIS_VECTOR_SLAVE)

  KRATOS_CREATE_VARIABLE(Vector, LOCAL_PARAMETERS_SLAVE)
  KRATOS_CREATE_VARIABLE(int, FACE_BREP_ID_SLAVE)
    
  KRATOS_CREATE_VARIABLE(Vector, CONTROL_POINT_IDS_SLAVE)

  KRATOS_CREATE_VARIABLE(Vector, SHAPE_FUNCTION_SLAVE)
  KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_DERIVATIVES_SLAVE)
  KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_SECOND_DERIVATIVES_SLAVE)
}
