#include "nurbs_brep_application_variables.h"
#include "../../kratos/spatial_containers/spatial_containers.h"
//#include "custom_utilities/NurbsBrepModeler.h"

namespace Kratos
{
    //variables for IGA - DEM coupling
    KRATOS_CREATE_VARIABLE(std::vector<Condition*>, WALL_POINT_CONDITION_POINTERS)
    typedef std::vector<array_1d<double, 3> > std_vector_of_arrays_3d;
    KRATOS_CREATE_VARIABLE(std_vector_of_arrays_3d, WALL_POINT_CONDITION_ELASTIC_FORCES)
    KRATOS_CREATE_VARIABLE(std_vector_of_arrays_3d, WALL_POINT_CONDITION_TOTAL_FORCES)

    KRATOS_CREATE_VARIABLE(double, RADIUS)
    KRATOS_CREATE_VARIABLE(Vector, COORDINATES)
    KRATOS_CREATE_VARIABLE(Vector, SURFACE_NORMAL)

	KRATOS_CREATE_VARIABLE(double, CONTROL_POINT_WEIGHT)

	//KRATOS_CREATE_VARIABLE(double, INTEGRATION_WEIGHT)

	KRATOS_CREATE_VARIABLE(Vector, TANGENTS_BASIS_VECTOR)

	KRATOS_CREATE_VARIABLE(Vector, LOCAL_PARAMETERS)
	KRATOS_CREATE_VARIABLE(int, FACE_BREP_ID)

	KRATOS_CREATE_VARIABLE(Vector, CONTROL_POINT_IDS)

	////Values of Shapefunctions N
	KRATOS_CREATE_VARIABLE(Vector, SHAPE_FUNCTION_VALUES)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_DERIVATIVES)
    KRATOS_CREATE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_SECOND_DERIVATIVES)
	KRATOS_CREATE_VARIABLE(Vector, NURBS_SHAPE_FUNCTIONS)
	////Values of Shapefunctionderivatives in local space DN_De
	KRATOS_CREATE_VARIABLE(Matrix, NURBS_SHAPE_FUNCTION_DERIVATIVES)
	KRATOS_CREATE_VARIABLE(Matrix, NURBS_SHAPE_FUNCTION_SECOND_DERIVATIVES)


	// SLAVE VARIABLES
	KRATOS_CREATE_VARIABLE(Vector, LOCATION_SLAVE)

	KRATOS_CREATE_VARIABLE(Vector, TANGENTS_BASIS_VECTOR_SLAVE)

	KRATOS_CREATE_VARIABLE(Vector, LOCAL_PARAMETERS_SLAVE)
	KRATOS_CREATE_VARIABLE(int, FACE_BREP_ID_SLAVE)
    
	KRATOS_CREATE_VARIABLE(Vector, CONTROL_POINT_IDS_SLAVE)

	KRATOS_CREATE_VARIABLE(Vector, NURBS_SHAPE_FUNCTIONS_SLAVE)
	KRATOS_CREATE_VARIABLE(Matrix, NURBS_SHAPE_FUNCTION_DERIVATIVES_SLAVE)
	KRATOS_CREATE_VARIABLE(Matrix, NURBS_SHAPE_FUNCTION_SECOND_DERIVATIVES_SLAVE)

	// internal variable to optimize projections between master and slave curves.
	KRATOS_CREATE_VARIABLE(double, CURVE_PARAMETER_KNOT_LOCATION_PERCENTAGE)
}
