#include "multilevel_monte_carlo_application_variables.h"

namespace Kratos
{
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_1 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_2 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_3 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_4 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_5 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_6 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_7 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_8 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_9 )
    KRATOS_CREATE_VARIABLE( double, POWER_SUM_10 )
}
