# CMake generated Testfile for 
# Source directory: /home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test
# Build directory: /home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_lap_s_bcsc_norm_tests "./bcsc_norm_tests" "--lap" "s:10:10:10")
add_test(test_lap_d_bcsc_norm_tests "./bcsc_norm_tests" "--lap" "d:10:10:10")
add_test(test_lap_c_bcsc_norm_tests "./bcsc_norm_tests" "--lap" "c:10:10:10")
add_test(test_lap_z_bcsc_norm_tests "./bcsc_norm_tests" "--lap" "z:10:10:10")
add_test(test_lap_s_bcsc_spmv_tests "./bcsc_spmv_tests" "--lap" "s:10:10:10")
add_test(test_lap_d_bcsc_spmv_tests "./bcsc_spmv_tests" "--lap" "d:10:10:10")
add_test(test_lap_c_bcsc_spmv_tests "./bcsc_spmv_tests" "--lap" "c:10:10:10")
add_test(test_lap_z_bcsc_spmv_tests "./bcsc_spmv_tests" "--lap" "z:10:10:10")
add_test(test_rsa_bcsc_norm_tests "./bcsc_norm_tests" "--rsa" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/small.rsa")
add_test(test_rsa_bcsc_spmv_tests "./bcsc_spmv_tests" "--rsa" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/small.rsa")
add_test(test_mm_bcsc_norm_tests "./bcsc_norm_tests" "--mm" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/young4c.mtx")
add_test(test_mm_bcsc_spmv_tests "./bcsc_spmv_tests" "--mm" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/young4c.mtx")
add_test(test_hb_bcsc_norm_tests "./bcsc_norm_tests" "--hb" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/orsirr.rua")
add_test(test_hb_bcsc_spmv_tests "./bcsc_spmv_tests" "--hb" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/orsirr.rua")
add_test(test_mm2_bcsc_norm_tests "./bcsc_norm_tests" "--mm" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/mhd1280b.mtx")
add_test(test_mm2_bcsc_spmv_tests "./bcsc_spmv_tests" "--mm" "/home/josep_maria/Kratos/applications/SolversApplication/external_libraries/pastix-lib/pastix/test/matrix/mhd1280b.mtx")
add_test(test_c_ge2lr_tests "./c_ge2lr_tests" "-9" "1000:10:1")
add_test(test_s_ge2lr_tests "./s_ge2lr_tests" "-9" "1000:10:1")
add_test(test_z_ge2lr_tests "./z_ge2lr_tests" "-9" "1000:10:1")
add_test(test_d_ge2lr_tests "./d_ge2lr_tests" "-9" "1000:10:1")
add_test(test_c_rradd_tests "./c_rradd_tests" "-9" "1000:10:1")
add_test(test_s_rradd_tests "./s_rradd_tests" "-9" "1000:10:1")
add_test(test_z_rradd_tests "./z_rradd_tests" "-9" "1000:10:1")
add_test(test_d_rradd_tests "./d_rradd_tests" "-9" "1000:10:1")
add_test(test_c_lrmm_tests "./c_lrmm_tests" "-9" "1000:10:1")
add_test(test_s_lrmm_tests "./s_lrmm_tests" "-9" "1000:10:1")
add_test(test_z_lrmm_tests "./z_lrmm_tests" "-9" "1000:10:1")
add_test(test_d_lrmm_tests "./d_lrmm_tests" "-9" "1000:10:1")
add_test(test_bcsc_spmv_time "./bcsc_spmv_time" "-9" "1000:10:1")
add_test(test_bvec_gemv_tests "./bvec_gemv_tests" "-9" "1000:10:1")
add_test(test_bvec_tests "./bvec_tests" "-9" "1000:10:1")
