#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es {Root folder can't be edited} {La carpeta raíz no se puede editar}
::msgcat::mcset es {You can't use some reservate chars like:
  :   /   $   .   \\  %  } {Algunos carácteres reservados no pueden ser utilizados:
  :   /   $   .   \\  %  }
::msgcat::mcset es {Could not make a backup copy of Kratos interface data file (%s)} {No se puede hacer un backup del archivo maestro de Kratos %s}
::msgcat::mcset es {Error reading file %s %s %s problem type has been not correctly installed} {Error leyendo el archivo %s %s %s el problem type no está correctamente instalado}
::msgcat::mcset es Workshop#C#menu Workshop
::msgcat::mcset es {Simulation characteristics#C#menu} {Características de simulación}
::msgcat::mcset es {Group editor#C#menu} {Edición de grupos}
::msgcat::mcset es {Project setting#C#menu} {Configuración proyecto}
::msgcat::mcset es {Define the group properties using the group editor} {Defina el grupo de propiedades utilizando el editor de grupos}
::msgcat::mcset es {Define the Model Properties} {Define the Model Properties}
::msgcat::mcset es {Model definition toolbar} {Model definition toolbar}
::msgcat::mcset es {The project must be saved} {The project must be saved}
::msgcat::mcset es {Create new material} {Create new material}
::msgcat::mcset es {Delete material} {Delete material}
::msgcat::mcset es {Refresh Tree} {Refresh Tree}
::msgcat::mcset es Close Close
::msgcat::mcset es Root Root
::msgcat::mcset es {No material selected} {No material selected}
::msgcat::mcset es {Collapse All} {Collapse All}
::msgcat::mcset es {Expand All} {Expand All}
::msgcat::mcset es Model Model
::msgcat::mcset es Materials Materials
::msgcat::mcset es Properties Properties
::msgcat::mcset es C1 C1
::msgcat::mcset es {Entity $command} {Entity $command}
::msgcat::mcset es {Create automatic new group} {Create automatic new group}
::msgcat::mcset es {Assign condition to the selected group} {Assign condition to the selected group}
::msgcat::mcset es {Cancel assignation} {Cancel assignation}
::msgcat::mcset es {Property Name:} {Property Name:}
::msgcat::mcset es {The property name can not be empty} {The property name can not be empty}
::msgcat::mcset es {This name property it is already assigned.} {This name property it is already assigned.}
::msgcat::mcset es {You have to choose one group
 (you can create a new one pushing the button on the right)} {You have to choose one group
 (you can create a new one pushing the button on the right)}
::msgcat::mcset es {This group it is already assigned to this condition.} {This group it is already assigned to this condition.}
::msgcat::mcset es Group: Group:
::msgcat::mcset es {Confirm values} {Confirm values}
::msgcat::mcset es Project Project
::msgcat::mcset es {New Group#C#layer} {New Group}
::msgcat::mcset es New New
::msgcat::mcset es Delete Delete
::msgcat::mcset es Edit Edit
::msgcat::mcset es {Add a new group identifier} {Add a new group identifier}
::msgcat::mcset es {Delete the selected group} {Delete the selected group}
::msgcat::mcset es {Assing Entities to Groups} {Assing Entities to Groups}
::msgcat::mcset es {Unassing Entities from Groups} {Unassing Entities from Groups}
::msgcat::mcset es {Any group selected} {Any group selected}
::msgcat::mcset es {Press 'Finish' to stop the entities selection} {Press 'Finish' to stop the entities selection}
::msgcat::mcset es {Bad group name, start or end by '//' is not allowed} {Bad group name, start or end by '//' is not allowed}
::msgcat::mcset es {No group selected} {No group selected}
::msgcat::mcset es {Select color} {Select color}
::msgcat::mcset es {You can not choose an empty group name.} {You can not choose an empty group name.}
::msgcat::mcset es {The group name '%s' already exist.
Choose another, please.} {El nombre de grupo '%s' already exist.
Choose another, please.}
::msgcat::mcset es {Group Id} {Group Id}
::msgcat::mcset es Color Color
::msgcat::mcset es On/Off On/Off
::msgcat::mcset es Type Type
::msgcat::mcset es {Entities group editor} {Entities group editor}
::msgcat::mcset es Rename Rename
::msgcat::mcset es On#C#verb On
::msgcat::mcset es Off#C#verb Off
::msgcat::mcset es {Assign Entities} {Assign Entities}
::msgcat::mcset es Unassign Unassign
::msgcat::mcset es %i %i
::msgcat::mcset es {Entity %s} {Entity %s}
::msgcat::mcset es {The new group '%s' has not any usefull entity assigned.} {El nuevo grupo '%s' no tiene ninguna entidad apropiada asociada.}
::msgcat::mcset es {This property name already exist.} {This property name already exist.}
::msgcat::mcset es %s %s
::msgcat::mcset es {0 } {0 }
::msgcat::mcset es {1 } {1 }
::msgcat::mcset es {2D } {2D }
::msgcat::mcset es {3D } {3D }
::msgcat::mcset es {Absolute tolerance } {Absolute tolerance }
::msgcat::mcset es {Activation } {Activation }
::msgcat::mcset es {Add a new Property } {Add a new Property }
::msgcat::mcset es {Analysis Data } {Analysis Data }
::msgcat::mcset es {Analysis Type } {Analysis Type }
::msgcat::mcset es {Analysis type } {Analysis type }
::msgcat::mcset es {Application types } {Application types }
::msgcat::mcset es {Arc length } {Arc length }
::msgcat::mcset es {BC } {BC }
::msgcat::mcset es {Beams } {Beams }
::msgcat::mcset es {BiConjugate gradient stabilized } {BiConjugate gradient stabilized }
::msgcat::mcset es {Body force } {Body force }
::msgcat::mcset es {BodyForce } {BodyForce }
::msgcat::mcset es {Boundary Conditions } {Boundary Conditions }
::msgcat::mcset es {Company name } {Company name }
::msgcat::mcset es {Concentrated } {Concentrated }
::msgcat::mcset es {Conditions } {Conditions }
::msgcat::mcset es {Conjugate gradient } {Conjugate gradient }
::msgcat::mcset es {Convection diffusion } {Convection diffusion }
::msgcat::mcset es {Convergence criteria } {Convergence criteria }
::msgcat::mcset es {Convergence tolerance } {Convergence tolerance }
::msgcat::mcset es {Crisfield Truss Element } {Crisfield Truss Element }
::msgcat::mcset es {Crisfield truss element } {Crisfield truss element }
::msgcat::mcset es {Cx } {Cx }
::msgcat::mcset es {Cy } {Cy }
::msgcat::mcset es {Cz } {Cz }
::msgcat::mcset es {Delta time } {Delta time }
::msgcat::mcset es {Developing in process } {Developing in process }
::msgcat::mcset es {Diagonal } {Diagonal }
::msgcat::mcset es {Direct } {Direct }
::msgcat::mcset es {Direct solver type } {Direct solver type }
::msgcat::mcset es {Displacement } {Displacement }
::msgcat::mcset es {Displacement and residual } {Displacement and residual }
::msgcat::mcset es {Displacement or residual } {Displacement or residual }
::msgcat::mcset es {Displacements } Desplazamientos
::msgcat::mcset es {Domain } Dominio
::msgcat::mcset es {Dynamic } Dinámico
::msgcat::mcset es {EBST (formulation) } {EBST (formulación) }
::msgcat::mcset es {Element Type } {Tipo de elemento}
::msgcat::mcset es {Element type } {Tipo de elemento}
::msgcat::mcset es {Elements } {Elementos }
::msgcat::mcset es {End time } {Tiempo final}
::msgcat::mcset es {Engineer } Ingeniero
::msgcat::mcset es {Face } Cara
::msgcat::mcset es {Fluid } Fluido
::msgcat::mcset es {Fluid structure interaction (FSI) } {Fluid structure interaction (FSI) }
::msgcat::mcset es {Fx } {Fx }
::msgcat::mcset es {Fx Vector } {Fx Vector }
::msgcat::mcset es {Fy } {Fy }
::msgcat::mcset es {Fy Vector } {Fy Vector }
::msgcat::mcset es {Fz } {Fz }
::msgcat::mcset es {Fz Vector } {Fz Vector }
::msgcat::mcset es {General application data } {General application data }
::msgcat::mcset es {Generic } Genérico
::msgcat::mcset es {Gravity value } {Factor gravedad}
::msgcat::mcset es {Helptext } {Helptext }
::msgcat::mcset es {Hexahedra } {Hexahedra }
::msgcat::mcset es {ILU0 } {ILU0 }
::msgcat::mcset es {Iterative } {Iterative }
::msgcat::mcset es {Iterative solver type } {Iterative solver type }
::msgcat::mcset es {Line search } {Line search }
::msgcat::mcset es {Linear } {Linear }
::msgcat::mcset es {Linear element } {Linear element }
::msgcat::mcset es {Linear solver type } {Linear solver type }
::msgcat::mcset es {LinearElement } {LinearElement }
::msgcat::mcset es {Load } {Load }
::msgcat::mcset es {Loads } {Loads }
::msgcat::mcset es {Material } {Material }
::msgcat::mcset es {Maximum iteration } {Maximum iteration }
::msgcat::mcset es {Maximum iterations } {Maximum iterations }
::msgcat::mcset es {Model description } {Model description }
::msgcat::mcset es {Model name } {Model name }
::msgcat::mcset es {Mx } {Mx }
::msgcat::mcset es {Mx Vector } {Mx Vector }
::msgcat::mcset es {My } {My }
::msgcat::mcset es {My Vector } {My Vector }
::msgcat::mcset es {Mz } {Mz }
::msgcat::mcset es {Mz Vector } {Mz Vector }
::msgcat::mcset es {New property } {New property }
::msgcat::mcset es {Newton-Raphson } {Newton-Raphson }
::msgcat::mcset es {No } {No }
::msgcat::mcset es {Non-Linear } {Non-Linear }
::msgcat::mcset es {None } {None }
::msgcat::mcset es {Not available } {Not available }
::msgcat::mcset es {Parallel MKL Pardiso } {Parallel MKL Pardiso }
::msgcat::mcset es {Preconditioner type } {Preconditioner type }
::msgcat::mcset es {Pressure } {Pressure }
::msgcat::mcset es {Project information } {Project information }
::msgcat::mcset es {Project name } {Project name }
::msgcat::mcset es {Project number } {Project number }
::msgcat::mcset es {Properties } {Properties }
::msgcat::mcset es {Property } {Property }
::msgcat::mcset es {Property1 } {Property1 }
::msgcat::mcset es {Puntual } {Puntual }
::msgcat::mcset es {Quadrilateral } {Quadrilateral }
::msgcat::mcset es {Residual } {Residual }
::msgcat::mcset es {Results } {Results }
::msgcat::mcset es {Revision number } {Revision number }
::msgcat::mcset es {Rotations } {Rotations }
::msgcat::mcset es {Shell anisotropic } {Shell anisotropic }
::msgcat::mcset es {Shell isotropic } {Shell isotropic }
::msgcat::mcset es {ShellAnisotropic } {ShellAnisotropic }
::msgcat::mcset es {ShellIsotropic } {ShellIsotropic }
::msgcat::mcset es {Shells } {Shells }
::msgcat::mcset es {Skyline LU factorization } {Skyline LU factorization }
::msgcat::mcset es {Solids } {Solids }
::msgcat::mcset es {Solution Strategy } {Solution Strategy }
::msgcat::mcset es {Solution Type } {Solution Type }
::msgcat::mcset es {Solution method } {Solution method }
::msgcat::mcset es {Solution strategy } {Solution strategy }
::msgcat::mcset es {Solution type } {Solution type }
::msgcat::mcset es {Spatial Dimension } {Spatial Dimension }
::msgcat::mcset es {Spatial dimension } {Spatial dimension }
::msgcat::mcset es {Start time } {Start time }
::msgcat::mcset es {Static } {Static }
::msgcat::mcset es {Stresses } {Stresses }
::msgcat::mcset es {Structural Type } {Structural Type }
::msgcat::mcset es {Structural analysis } {Structural analysis }
::msgcat::mcset es {Structural simulation } {Structural simulation }
::msgcat::mcset es {Structural type } {Structural type }
::msgcat::mcset es {Super LU } {Super LU }
::msgcat::mcset es {Supervisor } {Supervisor }
::msgcat::mcset es {Tetrahedra } {Tetrahedra }
::msgcat::mcset es {Thickness } {Thickness }
::msgcat::mcset es {Total Lagrangian } {Total Lagrangian }
::msgcat::mcset es {TotalLagrangian } {TotalLagrangian }
::msgcat::mcset es {Triangle } {Triangle }
::msgcat::mcset es {Truss } {Truss }
::msgcat::mcset es {Values } {Values }
::msgcat::mcset es {X } {X }
::msgcat::mcset es {X Vector } {X Vector }
::msgcat::mcset es {X active } {X active }
::msgcat::mcset es {X coordinate } {X coordinate }
::msgcat::mcset es {Y } {Y }
::msgcat::mcset es {Y Vector } {Y Vector }
::msgcat::mcset es {Y active } {Y active }
::msgcat::mcset es {Y coordinate } {Y coordinate }
::msgcat::mcset es {Yes } {Yes }
::msgcat::mcset es {Z } {Z }
::msgcat::mcset es {Z Vector } {Z Vector }
::msgcat::mcset es {Z active } {Z active }
::msgcat::mcset es {Z coordinate } {Z coordinate }
