#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es {alfa 11} {alfa 11}
::msgcat::mcset es {alfa 22} {alfa 22}
::msgcat::mcset es {alfa 33} {alfa 33}
::msgcat::mcset es ConjugateGradient {Gradiente conjugado}
::msgcat::mcset es DruckerPrager Drucker-Prager
::msgcat::mcset es Newton-Raphson Newton-Raphson
::msgcat::mcset es ParallelMKLPardiso {Paralelo MKL Pardiso}
::msgcat::mcset es SuperLU {Súper LU}
::msgcat::mcset es Vx Vx
::msgcat::mcset es Z Z
::msgcat::mcset es {Add this function} {Añadir esta función}
::msgcat::mcset es {Add variable} {Añadir variable}
::msgcat::mcset es Anisotropic Anisótropo
::msgcat::mcset es Apply Aplicar
::msgcat::mcset es ArcLength {Longitud arco}
::msgcat::mcset es Area Area
::msgcat::mcset es {Assign condition to the selected group} {Asignar condiciones para el grupo seleccionado}
::msgcat::mcset es Automatic Automático
::msgcat::mcset es {Automatic delta time} {Incremento de tiempo automático}
::msgcat::mcset es {Beam element} {Elemento viga}
::msgcat::mcset es {Beam element type} {Tipo de elemento de viga}
::msgcat::mcset es {Beam total Lagrangian} {Viga total Lagrangiana}
::msgcat::mcset es Beams Vigas
::msgcat::mcset es BiConjugateGradientStabilized {Gradientes biconjugados estabilizado}
::msgcat::mcset es {Body force} {Fuerza cuerpo}
::msgcat::mcset es {Body forces} {Fuerzas cuerpo}
::msgcat::mcset es BodyForce {Fuerza cuerpo}
::msgcat::mcset es {Boundary Conditions} {Condiciones contorno}
::msgcat::mcset es {Boundary conditions} {Condiciones de contorno}
::msgcat::mcset es {Bounding Box} {Caja delimitadora}
::msgcat::mcset es Boundingbox {Caja delimitadora}
::msgcat::mcset es {Bulk Modulus} {Módulo Bulk}
::msgcat::mcset es ByPoints {Por puntos}
::msgcat::mcset es {Cancel assignation} {Cancelar asignación}
::msgcat::mcset es Composite Compuesto
::msgcat::mcset es Composite1 Compuesto1
::msgcat::mcset es Compressible Compresible
::msgcat::mcset es {Compressive fracture energy} {Energía de fractura compresión}
::msgcat::mcset es {Compressive strength} {Esfuerzo de compresión}
::msgcat::mcset es Concentrated Concentrado
::msgcat::mcset es Conditions Condiciones
::msgcat::mcset es Conductivity Conductividad
::msgcat::mcset es {Conjugate gradient} {Gradiente conjugado}
::msgcat::mcset es Continuous Continuo
::msgcat::mcset es {Convection diffusion} {Convección difusión}
::msgcat::mcset es {Crisfield truss element} {Elemento barra Crisfield}
::msgcat::mcset es {Cross section area} {Sección transversal}
::msgcat::mcset es {Curve definition} {Definición de la curva}
::msgcat::mcset es {Curve Id} {Id curva}
::msgcat::mcset es {Curve Identifier} {Identificador curva}
::msgcat::mcset es {Curve Points} {Puntos curva}
::msgcat::mcset es {Curve Type} {Tipo de curva}
::msgcat::mcset es {Cut plane postprocess options} {Opciones de plano de corte}
::msgcat::mcset es {Cut planes} {Planos de corte}
::msgcat::mcset es {Cut properties} {Propiedades corte}
::msgcat::mcset es Damage Daño
::msgcat::mcset es {Define the diameter value} {Definir el valor del diámetro}
::msgcat::mcset es {Define the divergence cleareance step value} {Defina el valor del paso de reinicio de divergencia}
::msgcat::mcset es {Define the flag variable properties} {Define las propiedades de la variable}
::msgcat::mcset es {Define the linear Darcy coefficient value} {Definir el valor del coeficiente de Darcy lineal}
::msgcat::mcset es {Define the nonlinear Darcy coefficient value} {Definir el valor del coeficiente de Darcy no lineal}
::msgcat::mcset es {Define the porosity value} {Definir el valor de porosidad}
::msgcat::mcset es {Define the positive or negative pressure} {Definir la presión positiva o negativa}
::msgcat::mcset es {Define the positive or negative shell pressure} {Definir la presión positiva o negativa en lámina}
::msgcat::mcset es {Define the turbulent viscosity value} {Definir el valor de la viscosidad turbulenta}
::msgcat::mcset es {Define the value} {Definir el valor}
::msgcat::mcset es {Defines which side of the face that matches the direction of the normal to the surface, positive or negative} {Define qué lado de la cara coincide con la dirección de la normal a la superficie, positivo o negativo}
::msgcat::mcset es Diameter Diámetro
::msgcat::mcset es DiscreteWithDt {Discreto con dt}
::msgcat::mcset es {Displacement or residual} {Displazamiento o residual}
::msgcat::mcset es DisplacementAndResidual {Displazamiento y residual
}
::msgcat::mcset es DisplacementOrResidual {Displazamiento o residual}
::msgcat::mcset es Displacements Desplazamientos
::msgcat::mcset es {Distance variable for the free surface using level set method} {Distancia variable de superficie libre utilizando el método 'level set'}
::msgcat::mcset es {Divergence cleareance step} {Paso reinicialización divergencia}
::msgcat::mcset es {Drag calculation} {Cálculo arrastre}
::msgcat::mcset es {Drag calculation properties} {Cálculo propiedades arrastre}
::msgcat::mcset es Elastic Elástico
::msgcat::mcset es Elasto-plastic Elasto-plástico
::msgcat::mcset es Electromagnetic Electromagnético
::msgcat::mcset es ElementBased {Basado en elemento}
::msgcat::mcset es {Error when preparing data for analysis (%s)} {Error preparando datos para análisis (%s)}
::msgcat::mcset es Eulerian Euleriano
::msgcat::mcset es {Extrapolation layers} {Capas extrapolación}
::msgcat::mcset es {Face type} {Tipo de Cara}
::msgcat::mcset es {Fix X velocity} {Fijar velocidad X}
::msgcat::mcset es {Fix Y velocity} {Fijar velocidad Y}
::msgcat::mcset es {Fix Z velocity} {Fijar velocidad Z}
::msgcat::mcset es Fixed Fijo
::msgcat::mcset es Fixity Fijo
::msgcat::mcset es Flag Flag
::msgcat::mcset es {Flag variable} {Variables Flag}
::msgcat::mcset es Flag-Variable Flag-Variable
::msgcat::mcset es {Fluid Approach} {Enfoque Fluido}
::msgcat::mcset es {Fluid approach} {Enfoque Fluido}
::msgcat::mcset es {Fluid dynamics} {Dinámica de fluidos}
::msgcat::mcset es {Fluid Inlet} {Entrada de fluido}
::msgcat::mcset es {Fractional step} {Paso fraccional}
::msgcat::mcset es {Fractional step level set} {Paso fraccional 'level set'}
::msgcat::mcset es {Fractional step semi-explicit element based} {Fraccional paso semi-explícita basado elemento}
::msgcat::mcset es {Free surface} {Superficie libre}
::msgcat::mcset es FSSE-ElementBased {FSSE-Basado elemento}
::msgcat::mcset es General General
::msgcat::mcset es {General application data} {Datos generales aplicación}
::msgcat::mcset es Generic Genérico
::msgcat::mcset es {GiD postprocess options} {Opciones postproceso GiD}
::msgcat::mcset es {GiD result file format} {Formato de archivo de resultados GiD}
::msgcat::mcset es {Green Lagrange strain tensor} {Tensor tensión Green Lagrange}
::msgcat::mcset es {Hardening law} {Ley de endurecimiento}
::msgcat::mcset es Helptext {Texto ayuda}
::msgcat::mcset es Hexahedra Hexaedro
::msgcat::mcset es {History graph} {Historia gráfica}
::msgcat::mcset es {History graph properties} {Historia propiedades del gráfico}
::msgcat::mcset es {History output on points} {Historia salida en puntos}
::msgcat::mcset es {History output on points properties} {Historia salid propiedades puntos}
::msgcat::mcset es Incompressible Imcompresible
::msgcat::mcset es {Inertia Ix} {Inercia Ix}
::msgcat::mcset es {Inertia Iy} {Inercia Iy}
::msgcat::mcset es {Initial Conditions} {Condiciones iniciales}
::msgcat::mcset es {Initial conditions} {Condiciones iniciales}
::msgcat::mcset es {Initial pressure} {Presión inicial}
::msgcat::mcset es {Initial temperature} {Temperatura inicial}
::msgcat::mcset es {Initial velocity} {Velocidad inicial}
::msgcat::mcset es {Inlet velocity} {Velocidad de entrada}
::msgcat::mcset es {Internal friction angle} {Ángulo de fricción interna}
::msgcat::mcset es {Is boundary} {Es contorno}
::msgcat::mcset es {Is fluid} {Es fluido}
::msgcat::mcset es Is-Boundary {Es contorno}
::msgcat::mcset es {Is-boundary conditional data} {Datos condicional es contorno}
::msgcat::mcset es Is-Fluid {Es fluido}
::msgcat::mcset es Is-Slip {Es Slip}
::msgcat::mcset es {Is-Slip conditional data} {Es-Slip datos condicionales}
::msgcat::mcset es Isotropic Isotrópico
::msgcat::mcset es {Isotropic + Kinematic} {Isotrópico + Cinemático}
::msgcat::mcset es {Isotropic hardening modulus} {Módulo endurecimiento isótropo}
::msgcat::mcset es IsotropicKinematic {Isotrópico Cinemático
}
::msgcat::mcset es {Iterative solver type} {Solver tipo iterativo}
::msgcat::mcset es {Iterative solver type options} {Opciones de tipo de solucionador iterativo}
::msgcat::mcset es Kinematic Cinemático
::msgcat::mcset es {Kinematic hardening modulus} {módulo endurecimiento cinemático}
::msgcat::mcset es {Kratos path} {Ruta Kratos}
::msgcat::mcset es {Krylov space dimension} {dimensión espacio Krylov}
::msgcat::mcset es {Laplacian correction of pressure} {Corrección de presión Laplaciano}
::msgcat::mcset es {Laplacian form} {Forma Laplaciana}
::msgcat::mcset es {Level set distance data} {Distancia datos 'level set'}
::msgcat::mcset es LevelSet {'Level set'}
::msgcat::mcset es {Linear Darcy coefficient} {Coeficiente de Darcy Lineal}
::msgcat::mcset es {Linear element} {Elemento lineal}
::msgcat::mcset es {Linear solver type} {Tipo solver lineal}
::msgcat::mcset es {Linear Velocity} {Velocidad Lineal}
::msgcat::mcset es LinearElement {Elemento Lineal}
::msgcat::mcset es LineSearch {Busqueda línea}
::msgcat::mcset es Load Cargar
::msgcat::mcset es Loads Cargas
::msgcat::mcset es {Magnetic permeability} {Permeabilidad magnética}
::msgcat::mcset es {Material model} {Material del modelo}
::msgcat::mcset es {Matrix A} {Matriz A}
::msgcat::mcset es {Matrix B} {Matriz B}
::msgcat::mcset es {Matrix D} {Matriz C}
::msgcat::mcset es {Max time variation} {Máx variación tiempo}
::msgcat::mcset es {Max X} {Max X}
::msgcat::mcset es {Max Y} {Max Y}
::msgcat::mcset es {Max Z} {Max Z}
::msgcat::mcset es {Maximum iteration} {Máximas iteraciones}
::msgcat::mcset es {Maximum iterations} {Máximas iteraciones:}
::msgcat::mcset es {Maximum pressure iterations} {Número máximo de iteraciones de presión}
::msgcat::mcset es {Maximum velocity iterations} {Máximo iteraciones velocidad}
::msgcat::mcset es Membrane Membrana
::msgcat::mcset es {Membrane element} {Elemento de membrana}
::msgcat::mcset es {Membrane element type} {Tipo de elemento de membrana}
::msgcat::mcset es Membranes Membranas
::msgcat::mcset es {Min time variation} {Mínima variación tiempo}
::msgcat::mcset es {Min X} {Min X}
::msgcat::mcset es {Min Y} {Min Y}
::msgcat::mcset es {Min Z} {Min Z}
::msgcat::mcset es {GMRES-UP Block} Mezclados
::msgcat::mcset es {Model description} {Descripción del modelo}
::msgcat::mcset es {Model name} {Nombre del modelo}
::msgcat::mcset es {Moment of inertia Ix} {Momento de inercia Ix}
::msgcat::mcset es {Moment of inertia Iy} {Momento de inercia Iy}
::msgcat::mcset es Monolithic Monolítico
::msgcat::mcset es {Monolithic solver maximum iteration numbers} {Número máximo de iteraciones solucionador monolítico}
::msgcat::mcset es More Más
::msgcat::mcset es Negative Negativo
::msgcat::mcset es {New property} {Nueva propiedad}
::msgcat::mcset es newGroup {nuevo grupo}
::msgcat::mcset es {Newton-Raphson methods} {Métodos de Newton-Raphson}
::msgcat::mcset es {Newton-Raphson with line search} {Newton-Raphson con búsqueda línea}
::msgcat::mcset es {No function selected to remove.} {No hay función seleccionada para eliminar.}
::msgcat::mcset es Non-Linear {No lineal}
::msgcat::mcset es None Ninguno
::msgcat::mcset es {Nonlinear Darcy coefficient} {Coeficiente de Darcy no lineal}
::msgcat::mcset es {Normal to plane} {Normal al plano}
::msgcat::mcset es {Normal to the plane} {Normal al plano}
::msgcat::mcset es {Not available} {No disponible}
::msgcat::mcset es {Number of initial steps} {Número de pasos iniciales}
::msgcat::mcset es {Number of processors} {Número de procesadores}
::msgcat::mcset es {Number of threads} {Número de hilos}
::msgcat::mcset es Ok Aceptar
::msgcat::mcset es {On gauss points} {En los puntos de gauss}
::msgcat::mcset es {On nodes} {En los nodos}
::msgcat::mcset es OpenMP OpenMP
::msgcat::mcset es Options Opciones
::msgcat::mcset es Origin Origen
::msgcat::mcset es {Origin properties} {Propiedades de Origen}
::msgcat::mcset es Orthotropic Ortótropo
::msgcat::mcset es {Outlet pressure} {Presión de salida}
::msgcat::mcset es {Output delata time} {Salida incremento tiempo}
::msgcat::mcset es {Output delta time} {Salida incremento tiempo}
::msgcat::mcset es {Output file} {Archivo de salida}
::msgcat::mcset es {Output file Id} {Id del archivo de salida}
::msgcat::mcset es {Output file identifier} {Identificador de archivo de salida}
::msgcat::mcset es {Parallel MKL Pardiso} {MKL Pardiso Paralelo}
::msgcat::mcset es {Parallel type} {Tipo paralelo}
::msgcat::mcset es {Period. Activ.} {Período. Activ.}
::msgcat::mcset es Periode Periode
::msgcat::mcset es Periodic Periódico
::msgcat::mcset es PFEM PFEM
::msgcat::mcset es {PFEM Wall} {PFEM pared}
::msgcat::mcset es PFEM-Lagrangian PFEM-Lagrange
::msgcat::mcset es Plastic Plástico
::msgcat::mcset es {Please choose a new name} {Escoja un nuevo nombre}
::msgcat::mcset es {Please, choose a non-empty ID.'} {Por favor, elija un ID que no esté vacío.}
::msgcat::mcset es Points Puntos
::msgcat::mcset es {Poisson ratio} {Coeficiente Poisson}
::msgcat::mcset es {Poisson ratio v12} {Coeficiente Poisson v12}
::msgcat::mcset es {Poisson ratio v13} {Coeficiente Poisson v13}
::msgcat::mcset es {Poisson ratio v23} {Coeficiente Poisson v23}
::msgcat::mcset es Porosity Porosidad
::msgcat::mcset es {Porosity and darcy law data} {Porosidad y datos ley de Darcy}
::msgcat::mcset es {Porosity and diameter data} {Porosidad y datos diámetro}
::msgcat::mcset es {Porous zones} {Zonas porosas}
::msgcat::mcset es Positive Positivo
::msgcat::mcset es {Preconditioner type} {Tipo Precondicionador}
::msgcat::mcset es {Predictor corrector} {Corrector predictor}
::msgcat::mcset es {Prescribed velocity} {Velocidad prescrita}
::msgcat::mcset es Pressure Presión
::msgcat::mcset es {Pressure direct solver type} {Presión solucionador directo}
::msgcat::mcset es {Pressure iterative solver type} {Presión solucionador iterativo solver}
::msgcat::mcset es {Pressure linear solver type} {Presión solucionador lineal}
::msgcat::mcset es {Pressure preconditioner type} {Presión tipo precondicionador}
::msgcat::mcset es {Pressure solver maximum iteration} {Presión máxima número iteración}
::msgcat::mcset es {Pressure solver tolerance} {Presión tolerancia solucionador}
::msgcat::mcset es {Pressure value} {Valor de presión}
::msgcat::mcset es {Print in layer} {Imprimir en la capa}
::msgcat::mcset es {Project configuration} {Configuración del proyecto}
::msgcat::mcset es {Project information} {Información del proyecto}
::msgcat::mcset es {Project name} {Nombre del proyecto}
::msgcat::mcset es {Project number} {Número del proyecto}
::msgcat::mcset es Property Propiedad
::msgcat::mcset es {Property Name:} {Nombre de la propiedad:}
::msgcat::mcset es {Property type} {Tipo de propiedad}
::msgcat::mcset es Point Punto
::msgcat::mcset es Quadrilateral Cuadrilátero
::msgcat::mcset es Rankine Rankine
::msgcat::mcset es Reactions Reacciones
::msgcat::mcset es {Redistance frequency} {Frecuencia Redistancia}
::msgcat::mcset es {Relative pressure tolerance} {Tolerancia a la presión relativa}
::msgcat::mcset es {Relative velocity tolerance} {Tolerancia velocidad relativa}
::msgcat::mcset es Results Resultados
::msgcat::mcset es {Root folder can't be edited} {La carpeta raíz no puede editarse}
::msgcat::mcset es {Skyline LU factorization} {Skyline factorización LU}
::msgcat::mcset es SkylineLUFactorization {Skyline factorización LU
}
::msgcat::mcset es Static Estático
::msgcat::mcset es Structural Estructural
::msgcat::mcset es {Structural analysis} {Análisis estructural}
::msgcat::mcset es {SuperLU iterative solver} {SuperLU solver iterativo}
::msgcat::mcset es SuperLUIterativeSolver {SuperLU solver iterativo
}
::msgcat::mcset es Temperature Temperatura
::msgcat::mcset es Tetrahedra Tetraedro
::msgcat::mcset es {The simulation is not calculated yet or is currently being calculated} {La simulación no ha sido realizada o está en curso}
::msgcat::mcset es Thermal Térmico
::msgcat::mcset es {This function is assigned %s time%s in this project,
do you want to unassign %s and continue?} {Esta función se ha asignadod %s veces %s en este proyecto 
 ¿Desea cancelar la desasignación de %s y continuar?}
::msgcat::mcset es Time Tiempo
::msgcat::mcset es Triangle Triángulo
::msgcat::mcset es {Use dt in stabilization} {Usar dt en estabilización}
::msgcat::mcset es {Use Ergun equation} {Usar ecuación Ergun}
::msgcat::mcset es {Use orthogonal subscales} {Usae subescalas ortogonales}
::msgcat::mcset es {Validate model before calculate} {Validar modelo antes de calcular}
::msgcat::mcset es Value Valor
::msgcat::mcset es Values Valores
::msgcat::mcset es Variable Variable
::msgcat::mcset es {Variable to be plotted for this output point} {Variable a imprimir para este punto de salida}
::msgcat::mcset es Velocity Velocidad
::msgcat::mcset es {Velocity direct solver type} {Velocidad solucionador directo}
::msgcat::mcset es {Velocity iterative solver type} {Velocidad solucionador iterativo}
::msgcat::mcset es {Velocity linear solver type} {Velocidad solucionador lineal}
::msgcat::mcset es {Velocity preconditioner type} {Velocidad tipo precondicionador}
::msgcat::mcset es {Velocity solver maximum iteration} {Velocidad solucionador máximas iteraciones}
::msgcat::mcset es {Velocity solver tolerance} {Velocidad tolerancia solucionador}
::msgcat::mcset es Viscosity Viscosidad
::msgcat::mcset es {Volume output} {Salida volúmen}
::msgcat::mcset es Von-Mises Von-Mises
::msgcat::mcset es VonMisses Von-Mises
::msgcat::mcset es Vy Vy
::msgcat::mcset es Vz Vz
::msgcat::mcset es {Wall law} {Ley pared}
::msgcat::mcset es {Wall law nodaI data} {Ley pared datos nodal}
::msgcat::mcset es {Wall law value} {Valor ley pared}
::msgcat::mcset es Wall/Object Muro/Objeto
::msgcat::mcset es Water Agua
::msgcat::mcset es {Write conditions} {Escribir condiciones}
::msgcat::mcset es {Write deformed mesh} {Escrir malla deformada}
::msgcat::mcset es {Write the conditions or only element to the GiD result file} {Escribir las condiciones o solo elementos en el fichero de resultados de GiD}
::msgcat::mcset es {Write the GiD deformed or undeformed mesh} {Escribir la malla de GiD deformada o indeformada}
::msgcat::mcset es X X
::msgcat::mcset es {X active} {X activa}
::msgcat::mcset es {X coordinate} {Coordenada X}
::msgcat::mcset es {X coordinate of the output point} {Coordenada X en el punto salida}
::msgcat::mcset es {X fix} {X fijada}
::msgcat::mcset es {X initial velocity} {Velocidad inicial X}
::msgcat::mcset es {X Variable} {Variable X}
::msgcat::mcset es {X Vector} {Vector X}
::msgcat::mcset es {X Velocity} {Velocidad X}
::msgcat::mcset es {X velocity} {Velocidad X}
::msgcat::mcset es Y Y
::msgcat::mcset es {Y active} {Y activa}
::msgcat::mcset es {Y coordinate} {Coordenada Y}
::msgcat::mcset es {Y coordinate of the output point} {Coordenada Y en el punto salida}
::msgcat::mcset es {Y fix} {Y fijada}
::msgcat::mcset es {Y initial velocity} {Velocidad inicial Y}
::msgcat::mcset es {Y Variable} {Variable Y}
::msgcat::mcset es {Y Vector} {Vector Y}
::msgcat::mcset es {Y Velocity} {Velocidad Y}
::msgcat::mcset es {Y velocity} {Velocidad Y}
::msgcat::mcset es Yes Sí
::msgcat::mcset es {Yield criteria} {Criterio fluencia}
::msgcat::mcset es {Yield Stress} {Tensión fluencia}
::msgcat::mcset es {You can't use some reservate chars like:
  :   /   $   .   \\  %} {No se pueden utilizar algunos carácteres reservados como:
  :   /   $   .   \\  %}
::msgcat::mcset es {Young modulus} {Módulo Young}
::msgcat::mcset es {Young modulus E11} {Módulo Young E11}
::msgcat::mcset es {Young modulus E22} {Módulo Young E22}
::msgcat::mcset es {Young modulus E33} {Módulo Young E33}
::msgcat::mcset es YoungModulus {Módulo Young}
::msgcat::mcset es {Z active} {Z activa}
::msgcat::mcset es {Z coordinate} {Coordenada Z}
::msgcat::mcset es {Z coordinate of the output point} {Coordenada Z en el punto salida}
::msgcat::mcset es {Z fix} {Z fijada}
::msgcat::mcset es {Z initial velocity} {Velocidad inicial Z
}
::msgcat::mcset es {Z Vector} {Vector Z}
::msgcat::mcset es {Z Velocity} {Velocidad Z}
::msgcat::mcset es {Z velocity} {Velocidad Z}
::msgcat::mcset es Zones Zonas
::msgcat::mcset es {Max Dt} {Máximo incremento tiempo}
::msgcat::mcset es {Min Dt} {Mínimo incremento tiempo}
::msgcat::mcset es {Write one GiD result file or multiple files} {Escribie uno o multiples ficheros GiD de resultados}
::msgcat::mcset es 2D 2D
::msgcat::mcset es {2nd Piola - Kirchhoff stress tensor} {2nda Piola - tensor de stress Kirchhoff}
::msgcat::mcset es 3D 3D
::msgcat::mcset es A11 A11
::msgcat::mcset es A12 A12
::msgcat::mcset es A13 A13
::msgcat::mcset es A21 A21
::msgcat::mcset es A22 A22
::msgcat::mcset es A23 A23
::msgcat::mcset es A31 A31
::msgcat::mcset es A32 A32
::msgcat::mcset es A33 A33
::msgcat::mcset es {Absolute pressure tolerance} {Presión de tolerancia absoluta}
::msgcat::mcset es {Absolute velocity tolerance} {Velocidad de tolerancia absoluta}
::msgcat::mcset es Activate Activar
::msgcat::mcset es Activation Activación
::msgcat::mcset es {Add a new function} {Añadir nueva función}
::msgcat::mcset es {Add a new Property} {Añadir nueva propiedad}
::msgcat::mcset es Advanced Avanzado
::msgcat::mcset es Air Aire
::msgcat::mcset es Aluminium_7021 Aluminio
::msgcat::mcset es {An error has been detected when get a temporal directory} {Se ha detectado un error accediendo a un directorio temporal}
::msgcat::mcset es {Analysis Data} {Analisis de datos}
::msgcat::mcset es {Analysis data} {Analisis de datos}
::msgcat::mcset es {Analysis Type} {Tipo de análisis}
::msgcat::mcset es {Analysis type} {Tipo de análisis}
::msgcat::mcset es {Angular Velocity} {Velocidad angular}
::msgcat::mcset es {Application types} {Tipos de aplicación}
::msgcat::mcset es {Arc length methods} {Métodos de longitud de arco}
::msgcat::mcset es Ascii Ascii
::msgcat::mcset es ASGS ASGS
::msgcat::mcset es {Assign the defined properties} {Asignar las propiedades definidas}
::msgcat::mcset es {Assign the selection function and close editor} {Assign the selection function and close editor}
::msgcat::mcset es B11 B11
::msgcat::mcset es B12 B12
::msgcat::mcset es B13 B13
::msgcat::mcset es B21 B21
::msgcat::mcset es B22 B22
::msgcat::mcset es B23 B23
::msgcat::mcset es B31 B31
::msgcat::mcset es B32 B32
::msgcat::mcset es B33 B33
::msgcat::mcset es BC BC
::msgcat::mcset es {BiConjugate gradient stabilized} {Gradientes biconjugados estabilizado}
::msgcat::mcset es Binary Binario
::msgcat::mcset es Cancel Cancelar
::msgcat::mcset es {Cancel process} {Cancelar proceso}
::msgcat::mcset es {Cancel the defined properties} {Cancelar las propiedades definidas}
::msgcat::mcset es {Cannot write file %s. Permission denied} {No se puede escribir el fichero %s. Permiso denegado}
::msgcat::mcset es {Check problem type version} {Comprobar versión del problema tipo}
::msgcat::mcset es {Choose a new cut identifier} {Elija nuevo identificador de corte}
::msgcat::mcset es {Choose a new graph identifier} {Elija un nuevo identificador gráfico}
::msgcat::mcset es {Choose a new property identifier} {Elija un nuevo identificador de la propiedad}
::msgcat::mcset es Close Cerrar
::msgcat::mcset es {Close the report window} {Cerrar la ventana de informe}
::msgcat::mcset es {Collapse All} {Colapsar todos}
::msgcat::mcset es {Company name} {Nombre de comañia}
::msgcat::mcset es {Compressible fluids are not available in this version} {Fluidos compresibles no están disponibles en esta versión}
::msgcat::mcset es {Confirm values} {Confirmar valores}
::msgcat::mcset es {Convergence criteria} {Criterio de convergencia}
::msgcat::mcset es {Copy material} {Copiar material}
::msgcat::mcset es {Could not make a backup copy of Kratos interface data file (%s)} {No se puede hacer una copia del fichero de Kratos (%s)}
::msgcat::mcset es {Create automatic new group} {Crear grupo automáticamente}
::msgcat::mcset es {Create new material} {Crear nuevo material}
::msgcat::mcset es Curves Curvas
::msgcat::mcset es {Cut Id} {Corte Id}
::msgcat::mcset es Cx Cx
::msgcat::mcset es Cy Cy
::msgcat::mcset es Cz Cz
::msgcat::mcset es D11 D11
::msgcat::mcset es D12 D12
::msgcat::mcset es D13 D13
::msgcat::mcset es D21 D21
::msgcat::mcset es D22 D22
::msgcat::mcset es D23 D23
::msgcat::mcset es D31 D31
::msgcat::mcset es D32 D32
::msgcat::mcset es D33 D33
::msgcat::mcset es {Define the curve properties} {Define las propiedades de la curva}
::msgcat::mcset es {Define the group properties using the group editor} {Defina el grupo de propiedades con el editor de grupos}
::msgcat::mcset es {Define the material properties} {Define las propiedades del modelo}
::msgcat::mcset es {Define the model properties} {Define las propiedades del modelo}
::msgcat::mcset es Delete Eliminar
::msgcat::mcset es {Delete Material} {Borrar material}
::msgcat::mcset es {Delete material} {Borrar material}
::msgcat::mcset es {Delete the selected function} {Borrar la función seleccionada}
::msgcat::mcset es {Delta time} {Tiempo delta}
::msgcat::mcset es Density Densidad
::msgcat::mcset es Description Descripción
::msgcat::mcset es {Developing in process} {Proceso en desarrollo}
::msgcat::mcset es Diagonal Diagonal
::msgcat::mcset es {Dilatancy angle} {Ángulo de dilatación}
::msgcat::mcset es Direct Directo
::msgcat::mcset es {Direct solver type} {Tipo de solver directo}
::msgcat::mcset es Discrete Discreto
::msgcat::mcset es {Discrete with dt} {Discreto con dt}
::msgcat::mcset es Displacement Desplazamiento
::msgcat::mcset es {Displacement absolute tolerance} {Desplazamiento de tolerancia absoluto}
::msgcat::mcset es {Displacement and residual} {Desplazamiento y residual}
::msgcat::mcset es {Displacement convergence tolerance} {Tolerancia de convergencia del desplazamiento}
::msgcat::mcset es Distance Distancia
::msgcat::mcset es Domain Dominio
::msgcat::mcset es {Double click here to integrate the window} {Haga doble clic aquí para integrar la ventana}
::msgcat::mcset es {Double click here to tear off the window} {Haga doble clic aquí para hacer exterior la ventana}
::msgcat::mcset es {Double-click toggle window or inline visualization} {Doble clic cambia entre ventana o visualización en línea}
::msgcat::mcset es Drucker-Prager Drucker-Prager
::msgcat::mcset es Dynamic Dinámico
::msgcat::mcset es {EBST (formulation)} {EBST (formulación)}
::msgcat::mcset es Edit Editar
::msgcat::mcset es {Electrical permitivity} {Permitividad eléctrica}
::msgcat::mcset es {Element Type} {Tipo de elemento}
::msgcat::mcset es {Element type} {Tipo de elemento}
::msgcat::mcset es Elements Elementos
::msgcat::mcset es {End time} {Tiempo final}
::msgcat::mcset es Energy Energía
::msgcat::mcset es Engineer Ingeniero
::msgcat::mcset es {Entities group editor#C#menu} {Editor de grupos de entidades}
::msgcat::mcset es {Entity %s} {Entidad %s}
::msgcat::mcset es {Environment temperature} {Temperatura ambiente}
::msgcat::mcset es {Error reading file %s %s %s problem type has been not correctly installed} {Error leyendo archivo %s %s %s el problem type no está correctamente instalado}
::msgcat::mcset es {Expand All} {Expandir todos}
::msgcat::mcset es {Expansion coeff} {Coeficiente de expansión}
::msgcat::mcset es Exponential Exponencial
::msgcat::mcset es Face Cara
::msgcat::mcset es False Falso
::msgcat::mcset es Fix Fijar
::msgcat::mcset es {Fix coordinates} {Coordenadas fijas}
::msgcat::mcset es {Fix pressure} {Pressión fija}
::msgcat::mcset es Fluid Fluido
::msgcat::mcset es {Fluid structure interaction (FSI)} {Interacción de fluido y estructura (FSI)}
::msgcat::mcset es {Fluid type} {Tipo de fluido}
::msgcat::mcset es Forces Forces
::msgcat::mcset es {Function definition} {Function definition}
::msgcat::mcset es {Function editor#C#menu} {Editor de funciones}
::msgcat::mcset es {Function Id} {Function Id}
::msgcat::mcset es {Function manager} {Administrador de funciones}
::msgcat::mcset es Fx Fx
::msgcat::mcset es {Fx Vector} {Vector Fx}
::msgcat::mcset es Fy Fy
::msgcat::mcset es {Fy Vector} {Vector Fy}
::msgcat::mcset es Fz Fz
::msgcat::mcset es {Fz Vector} {Vector Fz}
::msgcat::mcset es GMRES GMRES
::msgcat::mcset es {Graph Id} {Gráfico Id}
::msgcat::mcset es {Gravity value} Gravedad
::msgcat::mcset es {Group Id} {Grupo id}
::msgcat::mcset es Group: Grupo:
::msgcat::mcset es HexPly_8551-7_IM7 HexPly_8551-7_IM7
::msgcat::mcset es ILU0 ILU0
::msgcat::mcset es Iterative Iterativo
::msgcat::mcset es K11 K11
::msgcat::mcset es K22 K22
::msgcat::mcset es K33 K33
::msgcat::mcset es Kratos#C#menu Kratos
::msgcat::mcset es {Kratos global settings} {Kratos global settings}
::msgcat::mcset es Linear Lineal
::msgcat::mcset es Material Material
::msgcat::mcset es {Material database#C#menu} {Base de datos de materiales}
::msgcat::mcset es Materials Materiales
::msgcat::mcset es Metal Meta
::msgcat::mcset es Model Modelo
::msgcat::mcset es {Model definition toolbar} {Toolbar de definición del modelo}
::msgcat::mcset es {Model properties#C#menu} {Propiedades del modelo}
::msgcat::mcset es {Model validation} {Validación del modelo}
::msgcat::mcset es Mohr-Coulomb Mohr-Coulomb
::msgcat::mcset es MPI MPI
::msgcat::mcset es Multiples Multiples
::msgcat::mcset es Mx Mx
::msgcat::mcset es {Mx Vector} {Mx Vector}
::msgcat::mcset es My My
::msgcat::mcset es {My Vector} {My Vector}
::msgcat::mcset es Mz Mz
::msgcat::mcset es {Mz Vector} {Mz Vector}
::msgcat::mcset es {Name id:} {Name id:}
::msgcat::mcset es New Nuevo
::msgcat::mcset es {New group} {Nuevo grupo}
::msgcat::mcset es {New Material} {Nuevo material}
::msgcat::mcset es No No
::msgcat::mcset es Off Oculto
::msgcat::mcset es {Open the process control window} {Abrir ventana de control de proceso}
::msgcat::mcset es {PFEM is not available in this version.
You need the GiD version 11.1.2d or higher.} {PFEM no está disponible en esta versión.
Necesita la versión GiD 11.1.2d o superior.}
::msgcat::mcset es {Please, select the function you want to assign to '%s'.} {Please, select the function you want to assign to '%s'.}
::msgcat::mcset es {Press 'Finish' to stop the entities selection} {Pulse 'Finalizar' para parar la selección de entidades}
::msgcat::mcset es Print Imprimir
::msgcat::mcset es {Print the report via a temporal file using notepad} {Imprimir informe vía archivo temporal en notepad}
::msgcat::mcset es {Printing is only supported under Windows} {Solo se puede imprimir en Windows}
::msgcat::mcset es {Project properties} {Propiedades de proyecto}
::msgcat::mcset es {Project settings#C#menu} {Propiedades proyecto}
::msgcat::mcset es Properties Propiedades
::msgcat::mcset es {Property Id} {Propiedad Id}
::msgcat::mcset es {Refresh Tree} {Refrescar árbol}
::msgcat::mcset es {Rename Error Window} {Cambiar el nombre de la ventana de error}
::msgcat::mcset es {Rename material} {Renombrar material}
::msgcat::mcset es Root Raíz
::msgcat::mcset es {Run the simulation} {Ejecutar la simulación}
::msgcat::mcset es {Save and Close} {Guardar y cerrar}
::msgcat::mcset es {The new group '%s' has not any usefull entity assigned.} {El nuevo grupo '%s' no tiene ningun entdad asignadaº}
::msgcat::mcset es {The project must be saved} {El proyecto tiene que estar guardado}
::msgcat::mcset es {The property name can not be empty} {El nombre de propiedad no puede ser vacío}
::msgcat::mcset es {This group it is already assigned to this condition.} {Este grupo ya esta asignado a esta condición.}
::msgcat::mcset es {This name property it is already assigned.} {Este nombre de propiedad ya está asignado.}
::msgcat::mcset es {This property it is assigned to %s groups.
Do you want to delete the property and all this groups?} {Esta propiedad esta asignada a %s.
Desea borrar la propiedad y todos sus grupos?}
::msgcat::mcset es {This property name already exist.} {El nombre de propiedad ya existe.}
::msgcat::mcset es {Unassign function} {Desasignar función}
::msgcat::mcset es {View group entities} {Ver entidades de grupo}
::msgcat::mcset es {View process info} {Ver información de proyecto}
::msgcat::mcset es {You have to choose one group
 (you can create a new one pushing the button on the right)} {Tiene que elegir un grupo (se puede crear uno con el botón de la izquierda)}
::msgcat::mcset es {You must define a Property before!} {Antes debe definir una propiedad.}
::msgcat::mcset es {You must define a Property before.} {Antes debe definir una propiedad.}
::msgcat::mcset es {You must define a valid Property for this element type.} {Debe definir una propiedad válida para este tipo de elemento}
::msgcat::mcset es {Kratos variables} {Variables Kratos}
::msgcat::mcset es {Mixed UP Krylov space dimension} {Mixed Up Krylov dimensión espacial}
::msgcat::mcset es {No Slip} {No Slip}
::msgcat::mcset es No-Slip No-Slip
::msgcat::mcset es {Pseudo-Dynamic} {Dinámica relajada}
::msgcat::mcset es Pseudo-Dynamic {Dinámica relajada}
::msgcat::mcset es {Quasi-Static} {Quasi estático}
::msgcat::mcset es Quasi-Static {Quasi estático}
::msgcat::mcset es Residual Residual
::msgcat::mcset es {Residual absolute tolerance} {Tolerancia absoluta Residual}
::msgcat::mcset es {Residual convergence tolerance} {Tolerancia de convergencia Residual}
::msgcat::mcset es {Result file} {Resultado archivo}
::msgcat::mcset es {Result format} {Formato de resultado}
::msgcat::mcset es {Revision number} {Número de revisión}
::msgcat::mcset es {Rotation Center} {Centro de rotación}
::msgcat::mcset es Rotations Rotaciones
::msgcat::mcset es {Safety factor} {Factor de seguridad}
::msgcat::mcset es {Select the activate option value} {Seleccione el valor de la opción de activación}
::msgcat::mcset es {Select the active tubulence model} {Seleccione el modelo tubulence activo}
::msgcat::mcset es {Select the Delta time option to be used} {Seleccione la opción de tiempo de Delta para ser utilizado}
::msgcat::mcset es {Select the flag value} {Seleccione el valor del indicador}
::msgcat::mcset es {Select the fluid 2D element type} {Seleccione el tipo de elemento 2D fluida}
::msgcat::mcset es {Select the group identifier} {Seleccione el identificador de grupo}
::msgcat::mcset es {Shear modulus} {Módulo de cizalladura}
::msgcat::mcset es {Shear modulus G12} {Módulo de cizalladura}
::msgcat::mcset es {Shear modulus G13} {Módulo de cizalladura}
::msgcat::mcset es {Shear modulus G23} {Módulo de cizalladura}
::msgcat::mcset es {Shell anisotropic} {Lámina anisotrópica
}
::msgcat::mcset es {Shell isotropic} {Lámina isotrópica}
::msgcat::mcset es ShellAnisotropic {Lámina anisotrópica}
::msgcat::mcset es ShellIsotropic {Lámina isotrópica
}
::msgcat::mcset es Shells {Lámina
}
::msgcat::mcset es Single Sencilla
::msgcat::mcset es Slip Deslizamiento
::msgcat::mcset es {Smagorinsky constant} {Smagorinsky constante}
::msgcat::mcset es Smagorinsky-Lilly Smagorinsky-Lilly
::msgcat::mcset es {Softening law} {Reblandecimiento ley}
::msgcat::mcset es Solids Sólido
::msgcat::mcset es {Solution method} {Método de solución}
::msgcat::mcset es {Solution Strategy} {Estrategia de Solución}
::msgcat::mcset es {Solution strategy} {Estrategia de solución}
::msgcat::mcset es {Solution type} {Tipo de solución}
::msgcat::mcset es {Solver maximum iterations} {Solver máximo de iteraciones}
::msgcat::mcset es {Solver tolerance} {Tolerancia Solver}
::msgcat::mcset es {Solver type} {Tipo de Solver}
::msgcat::mcset es SolverType SolverType
::msgcat::mcset es Spalart-Allmaras Spalart-Allmaras
::msgcat::mcset es {Spalart-Allmaras groups} {Grupos Spalart-Allmaras}
::msgcat::mcset es {Spatial Dimension} {Dimensión Espacial}
::msgcat::mcset es {Spatial dimension} {Dimensión espacial}
::msgcat::mcset es {Specific heat} {Calor específico}
::msgcat::mcset es {Stabilized convection factor} {Factor de convección estabilizada}
::msgcat::mcset es {Stabilized dt pressure factor} {Factor de presión dt estabilizada}
::msgcat::mcset es {Start time} Desde
::msgcat::mcset es Steel_AISI1059 Steel_AISI1059
::msgcat::mcset es Stresses Tensiones
::msgcat::mcset es {Structural simulation} {Simulación estructural}
::msgcat::mcset es {Structural Type} {Tipo Estructural}
::msgcat::mcset es {Structural type} {Tipo estructural}
::msgcat::mcset es {Super LU} {Súper LU}
::msgcat::mcset es Supervisor Supervisor
::msgcat::mcset es {Target CFL} {Target CFL}
::msgcat::mcset es {Tensile fracture energy} {Energía de rotura a la tracción}
::msgcat::mcset es {Tensile strength} {Resistencia a la tensión}
::msgcat::mcset es {The Smagorinsky constant usually has the value: Cs = 0.1 - 0.2} {La constante Smagorinsky por lo general tiene el valor: Cs = 0.1 - 0.2}
::msgcat::mcset es Thickness Espesor
::msgcat::mcset es {Time order} {Orden tiempo}
::msgcat::mcset es {Total Lagrangian} {Total de Lagrange}
::msgcat::mcset es Tresca Tresca
::msgcat::mcset es True Verdadero
::msgcat::mcset es Truss Celosía
::msgcat::mcset es {Turbulence model} {Modelo de turbulencia}
::msgcat::mcset es {Turbulent viscosity} {Viscosidad turbulenta}
::msgcat::mcset es {Type of curve} {Tipo de curva}
::msgcat::mcset es {Use Laplacian correction of pressure} {Utilizar corrección de Laplace de la presión}
