#include "compressible_potential_flow_application_variables.h"

namespace Kratos
{
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_INFINITY)

    KRATOS_CREATE_VARIABLE(double, VELOCITY_POTENTIAL)
    KRATOS_CREATE_VARIABLE(double, AUXILIARY_VELOCITY_POTENTIAL)
    KRATOS_CREATE_VARIABLE( double, WAKE_DISTANCE)
    KRATOS_CREATE_VARIABLE( double, LEVEL_SET_DISTANCE)


    KRATOS_CREATE_VARIABLE( double, ADJOINT_VELOCITY_POTENTIAL)
    KRATOS_CREATE_VARIABLE( double, ADJOINT_AUXILIARY_VELOCITY_POTENTIAL)
    KRATOS_CREATE_VARIABLE( double, DISTANCE_SENSITIVITY)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(COORDINATES_SENSITIVITY)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(COORDINATES)

}
