#include "compressible_potential_flow_application_variables.h"

namespace Kratos
{
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_INFINITY)
    KRATOS_CREATE_VARIABLE( double, POSITIVE_POTENTIAL)
    KRATOS_CREATE_VARIABLE( double, NEGATIVE_POTENTIAL)
    KRATOS_CREATE_VARIABLE( double, WAKE_DISTANCE)
    KRATOS_CREATE_VARIABLE( Vector, WAKE_ELEMENTAL_DISTANCES )
    KRATOS_CREATE_VARIABLE( double, LEVEL_SET_DISTANCE)
    KRATOS_CREATE_VARIABLE( Vector, LEVEL_SET_ELEMENTAL_DISTANCES )

}
