Per_node scalar values for the EnSight6 geometry. Nodal variable: BOUNDARY
        -1	        -1	        -1	        -1	        -1	        -1
        -1	        -1	        -1	        -1	        -1	        -1
        -1	        -1	        -1	        -1	        -1	        -1
        -1	        -1	        -1	        -1	        -1	        -1
        -1	        -1	        -1	        -1	        -1	        -1
        -1	        -1	        -1	        -1	