/*
==============================================================================
Kratos
A General Purpose Software for Multi-Physics Finite Element Analysis
Version 1.0 (Released on march 05, 2007).

Copyright 2007
Pooyan Dadvand, Riccardo Rossi
pooyan@cimne.upc.edu
rrossi@cimne.upc.edu
CIMNE (International Center for Numerical Methods in Engineering),
Gran Capita' s/n, 08034 Barcelona, Spain

Permission is hereby granted, free  of charge, to any person obtaining
a  copy  of this  software  and  associated  documentation files  (the
"Software"), to  deal in  the Software without  restriction, including
without limitation  the rights to  use, copy, modify,  merge, publish,
distribute,  sublicense and/or  sell copies  of the  Software,  and to
permit persons to whom the Software  is furnished to do so, subject to
the following condition:

Distribution of this code for  any  commercial purpose  is permissible
ONLY BY DIRECT ARRANGEMENT WITH THE COPYRIGHT OWNER.

The  above  copyright  notice  and  this permission  notice  shall  be
included in all copies or substantial portions of the Software.

THE  SOFTWARE IS  PROVIDED  "AS  IS", WITHOUT  WARRANTY  OF ANY  KIND,
EXPRESS OR  IMPLIED, INCLUDING  BUT NOT LIMITED  TO THE  WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT  SHALL THE AUTHORS OR COPYRIGHT HOLDERS  BE LIABLE FOR ANY
CLAIM, DAMAGES OR  OTHER LIABILITY, WHETHER IN AN  ACTION OF CONTRACT,
TORT  OR OTHERWISE, ARISING  FROM, OUT  OF OR  IN CONNECTION  WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

==============================================================================
*/
 
//   
//   Project Name:        Kratos       
//   Last Modified by:    $Author: mengmeng $
//   Date:                $Date: 2009-02-26 14:28:57 $
//   Revision:            $Revision: 1.16 $
//
//



// System includes
#include <string>
#include <iostream> 

// External includes 


// Project includes
#include "includes/define.h"
#include "includes/variables.h"
#include "includes/kernel.h"
#include "includes/node.h"
#include "includes/element.h"
#include "includes/condition.h"
#include "includes/constitutive_law.h"

//#include "geometries/triangle_2d_3.h"
#include "geometries/triangle_3d_3.h"
//#include "geometries/tetrahedra_3d_4.h"

namespace Kratos
{
    KRATOS_CREATE_VARIABLE(bool, IS_INACTIVE)

	KRATOS_CREATE_VARIABLE(int, OSS_SWITCH)
	KRATOS_CREATE_VARIABLE(int, DYNAMIC_TAU)

	KRATOS_CREATE_VARIABLE(vector<int>, NEIGHBOURS_INDICES)
	KRATOS_CREATE_VARIABLE(double, PARTITION_INDEX)
	KRATOS_CREATE_VARIABLE(double, ERASE_FLAG)
	KRATOS_CREATE_VARIABLE(int, NL_ITERATION_NUMBER)
	KRATOS_CREATE_VARIABLE(int, FRACTIONAL_STEP)
	KRATOS_CREATE_VARIABLE(double, TIME)
	KRATOS_CREATE_VARIABLE(int, TIME_STEPS)
	KRATOS_CREATE_VARIABLE(double, START_TIME)
	KRATOS_CREATE_VARIABLE(double, END_TIME)
	KRATOS_CREATE_VARIABLE(double, DELTA_TIME)
	KRATOS_CREATE_VARIABLE(double, TEMPERATURE)
	KRATOS_CREATE_VARIABLE(double, PRESSURE)
	KRATOS_CREATE_VARIABLE(double, DENSITY)
	KRATOS_CREATE_VARIABLE(double, VISCOSITY)
	KRATOS_CREATE_VARIABLE(double, ERROR_RATIO)

	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_ACCELERATION)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_VELOCITY)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION)
  	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY)
  	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ROTATION)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM)
  	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(REACTION)
  	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(BODY_FORCE)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SEEPAGE_DRAG)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MESH_VELOCITY)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(NORMAL)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FORCE)
		  KRATOS_CREATE_VARIABLE( double, MU )


    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FORCE_CM)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM_CM)
    KRATOS_CREATE_VARIABLE(double, TAU)

	KRATOS_CREATE_VARIABLE(Matrix, INERTIA )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ADVPROJ)

	//NEIGHBOUR_NODES  is defined in Node.h
	KRATOS_CREATE_VARIABLE(WeakPointerVector<Node<3> >, NEIGHBOUR_NODES)

	//NEIGHBOR_ELEMENTS is defined in element.h
	KRATOS_CREATE_VARIABLE(WeakPointerVector<Element >, NEIGHBOUR_ELEMENTS)

	//NEIGHBOR_CONDITIONS is defined in condition.h
	KRATOS_CREATE_VARIABLE(WeakPointerVector<Condition >, NEIGHBOUR_CONDITIONS)

	//for structural application TO BE REMOVED
        KRATOS_CREATE_VARIABLE(Vector, MATERIAL_PARAMETERS)
	KRATOS_CREATE_VARIABLE(int, WRINKLING_APPROACH )
	KRATOS_CREATE_VARIABLE(Matrix, GREEN_LAGRANGE_STRAIN_TENSOR )
	KRATOS_CREATE_VARIABLE(Matrix, PK2_STRESS_TENSOR )
    KRATOS_CREATE_VARIABLE(Matrix, CAUCHY_STRESS_TENSOR )
	KRATOS_CREATE_VARIABLE(Matrix, AUXILIARY_MATRIX_1 )
	KRATOS_CREATE_VARIABLE(double, YOUNG_MODULUS )
	KRATOS_CREATE_VARIABLE(double, POISSON_RATIO )
	KRATOS_CREATE_VARIABLE(double, THICKNESS )
	KRATOS_CREATE_VARIABLE(double, NEGATIVE_FACE_PRESSURE )
	KRATOS_CREATE_VARIABLE(double, POSITIVE_FACE_PRESSURE )
	KRATOS_CREATE_VARIABLE( double, INITIAL_PENALTY )
	KRATOS_CREATE_VARIABLE(ConstitutiveLaw<Node<3> >::Pointer, CONSTITUTIVE_LAW)
        KRATOS_CREATE_VARIABLE(Vector, INTERNAL_VARIABLES)
	KRATOS_CREATE_VARIABLE(double, DP_EPSILON)
	KRATOS_CREATE_VARIABLE(Vector, INSITU_STRESS )
	KRATOS_CREATE_VARIABLE(double, DP_ALPHA1 )
	KRATOS_CREATE_VARIABLE(double, DP_K )
	KRATOS_CREATE_VARIABLE(int, CALCULATE_INSITU_STRESS )
	//CONTACT_LINK_MASTER is defined in condition.h
// 	KRATOS_CREATE_VARIABLE( Condition::Pointer, CONTACT_LINK_MASTER )
	//CONTACT_LINK_SLAVE is defined in condition.h
// 	KRATOS_CREATE_VARIABLE( Condition::Pointer, CONTACT_LINK_SLAVE )
	
	KRATOS_CREATE_VARIABLE(int, CONTACT_RAMP )
	KRATOS_CREATE_VARIABLE(Vector, PENALTY )
	KRATOS_CREATE_VARIABLE(Vector, PENALTY_T )
	KRATOS_CREATE_VARIABLE(double, FRICTION_COEFFICIENT )
    KRATOS_CREATE_VARIABLE(double, LAMBDA )
    KRATOS_CREATE_VARIABLE(double, MIU )
    KRATOS_CREATE_VARIABLE(Vector, LAMBDAS )
	KRATOS_CREATE_VARIABLE(Matrix, LAMBDAS_T )
	KRATOS_CREATE_VARIABLE(Vector, GAPS )
	KRATOS_CREATE_VARIABLE(Vector, DELTA_LAMBDAS )
	KRATOS_CREATE_VARIABLE(Matrix, DELTA_LAMBDAS_T )
	KRATOS_CREATE_VARIABLE(int, CONTACT_SLAVE_INTEGRATION_POINT_INDEX )
	KRATOS_CREATE_VARIABLE( Matrix, CONTACT_LINK_M )
	KRATOS_CREATE_VARIABLE( int, CONTACT_DOUBLE_CHECK )
	KRATOS_CREATE_VARIABLE( int, IS_CONTACT_MASTER )
	KRATOS_CREATE_VARIABLE( int, IS_CONTACT_SLAVE )
	KRATOS_CREATE_VARIABLE( Vector, STICK )
	KRATOS_CREATE_VARIABLE( int, FIRST_TIME_STEP )
	KRATOS_CREATE_VARIABLE( int, QUASI_STATIC_ANALYSIS )
	KRATOS_CREATE_VARIABLE( Vector, NORMAL_STRESS )
	KRATOS_CREATE_VARIABLE( Vector, TANGENTIAL_STRESS )
	KRATOS_CREATE_VARIABLE( double, NORMAL_CONTACT_STRESS )
	KRATOS_CREATE_VARIABLE( double, TANGENTIAL_CONTACT_STRESS )
	KRATOS_CREATE_VARIABLE( double, CONTACT_STICK )
			
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE )
	KRATOS_CREATE_VARIABLE( double, REACTION_WATER_PRESSURE )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_DT )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_ACCELERATION )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_NULL )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_NULL_DT )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_NULL_ACCELERATION )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_EINS )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_EINS_DT )
	KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_EINS_ACCELERATION )
		
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE )
	KRATOS_CREATE_VARIABLE( double, REACTION_AIR_PRESSURE )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_DT )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_ACCELERATION )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_NULL )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_NULL_DT )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_NULL_ACCELERATION )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_EINS )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_EINS_DT )
	KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_EINS_ACCELERATION )
    KRATOS_CREATE_VARIABLE( double, SUCTION )
	
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_OLD)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_DT)
// 	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_NULL)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_NULL_DT)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION_NULL)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_EINS)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_EINS_DT)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION_EINS)
	KRATOS_CREATE_VARIABLE( Matrix, ELASTIC_LEFT_CAUCHY_GREEN_OLD )
	
	KRATOS_CREATE_VARIABLE(int, ACTIVATION_LEVEL)
	KRATOS_CREATE_VARIABLE(double, FLAG_VARIABLE )
	KRATOS_CREATE_VARIABLE(double, DISTANCE )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( LAGRANGE_DISPLACEMENT )
    KRATOS_CREATE_VARIABLE( double, LAGRANGE_AIR_PRESSURE )
    KRATOS_CREATE_VARIABLE( double, LAGRANGE_WATER_PRESSURE )
    KRATOS_CREATE_VARIABLE( double, LAGRANGE_TEMPERATURE )

	
	//for ALE application TO BE REMOVED
	KRATOS_CREATE_VARIABLE(double, IS_INTERFACE )
            
    //for electric_application
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_DT )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_DT2 )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_NULL )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_EINS )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_NULL_DT )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_EINS_DT )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_NULL_DT2 )
    KRATOS_CREATE_VARIABLE(double, ELECTRIC_POTENTIAL_EINS_DT2 )
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_ELECTRIC_POTENTIAL)
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_DT )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_DT2 )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_NULL )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_EINS )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_NULL_DT )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_EINS_DT )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_NULL_DT2 )
    KRATOS_CREATE_VARIABLE(double, CONCENTRATION_EINS_DT2 )
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_CONCENTRATION)


	
	//for PFEM application TO BE REMOVED
	KRATOS_CREATE_VARIABLE(double,  NODAL_AREA)
	KRATOS_CREATE_VARIABLE(double,  NODAL_H)
	KRATOS_CREATE_VARIABLE(double,  IS_STRUCTURE)
	KRATOS_CREATE_VARIABLE(double,  IS_POROUS)
	KRATOS_CREATE_VARIABLE(double,  IS_WATER)
	KRATOS_CREATE_VARIABLE(double,  IS_FLUID)
	KRATOS_CREATE_VARIABLE(double,  IS_BOUNDARY)
	KRATOS_CREATE_VARIABLE(double,  IS_FREE_SURFACE)
	KRATOS_CREATE_VARIABLE(double,  IS_LAGRANGIAN_INLET)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(NORMAL_TO_WALL)
	KRATOS_CREATE_VARIABLE(double,  IS_WATER_ELEMENT)


	KRATOS_CREATE_VARIABLE(double, BULK_MODULUS)	
	KRATOS_CREATE_VARIABLE(double, SATURATION )	
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( GRAVITY )	
	KRATOS_CREATE_VARIABLE(double, DENSITY_WATER )
	KRATOS_CREATE_VARIABLE(double, VISCOSITY_WATER)
	KRATOS_CREATE_VARIABLE(double, DENSITY_AIR )
	KRATOS_CREATE_VARIABLE(double, VISCOSITY_AIR)
	KRATOS_CREATE_VARIABLE(double, POROSITY )
	KRATOS_CREATE_VARIABLE(double, AIR_ENTRY_VALUE )
	KRATOS_CREATE_VARIABLE(double, FIRST_SATURATION_PARAM )
	KRATOS_CREATE_VARIABLE(double, SECOND_SATURATION_PARAM )
	KRATOS_CREATE_VARIABLE(double, PERMEABILITY_WATER )
	KRATOS_CREATE_VARIABLE(double, PERMEABILITY_AIR )
	KRATOS_CREATE_VARIABLE(double, BULK_AIR )
	KRATOS_CREATE_VARIABLE(int, SCALE )
        KRATOS_CREATE_VARIABLE(int, IS_JACK_LINK )
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( FACE_LOAD )

	KRATOS_CREATE_VARIABLE(double, DIVPROJ)
	KRATOS_CREATE_VARIABLE(double, THAWONE)
	KRATOS_CREATE_VARIABLE(double, THAWTWO)
			
        KRATOS_CREATE_VARIABLE(double, BASE)
        KRATOS_CREATE_VARIABLE(double, HEIGHT)
        KRATOS_CREATE_VARIABLE(double, CONCRETE_YOUNG_MODULUS_C)
        KRATOS_CREATE_VARIABLE(double, CONCRETE_YOUNG_MODULUS_T)
        KRATOS_CREATE_VARIABLE(double, FC )
        KRATOS_CREATE_VARIABLE(double, FT)
	KRATOS_CREATE_VARIABLE(double, FRACTURE_ENERGY)	
        KRATOS_CREATE_VARIABLE(double, YIELD_STRESS)	
        KRATOS_CREATE_VARIABLE(double, LAMNDA) // Load factor
      	KRATOS_CREATE_VARIABLE( double, DAMAGE )
      	KRATOS_CREATE_VARIABLE( Vector, VECTOR_DAMAGE)
	KRATOS_CREATE_VARIABLE( Vector, ORTHOTROPIC_YOUNG_MODULUS_2D) // [E1 E2 G12]
	KRATOS_CREATE_VARIABLE( Vector, ORTHOTROPIC_POISSON_RATIO_2D) // [v12 v21]
	KRATOS_CREATE_VARIABLE( double, ORTHOTROPIC_ANGLE)
        KRATOS_CREATE_VARIABLE( double, VOLUMEN_FRACTION)
        KRATOS_CREATE_VARIABLE( double, FRICTION_INTERNAL_ANGLE)
        KRATOS_CREATE_VARIABLE( double, COHESION)
	KRATOS_CREATE_VARIABLE( Vector, ORTHOTROPIC_ELASTIC_LIMIT)
	KRATOS_CREATE_VARIABLE( double, ISOTROPIC_ELASTIC_LIMIT)


	KRATOS_CREATE_VARIABLE(double, ARRHENIUS)
	KRATOS_CREATE_VARIABLE(double, ARRHENIUSAUX)
	KRATOS_CREATE_VARIABLE(double,  PRESSUREAUX)
	KRATOS_CREATE_VARIABLE(double,  NODAL_MAUX)
	KRATOS_CREATE_VARIABLE(double,  NODAL_PAUX)


	KRATOS_CREATE_VARIABLE(double,SOUND_VELOCITY)	
	KRATOS_CREATE_VARIABLE(double,AIR_SOUND_VELOCITY)
	KRATOS_CREATE_VARIABLE(double,WATER_SOUND_VELOCITY)
			
	KRATOS_CREATE_VARIABLE(double, IS_VISITED )	

	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FRACT_VEL)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(PRESS_PROJ)
	KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CONV_PROJ)
         KRATOS_CREATE_VARIABLE( double, NODAL_MASS)
	 KRATOS_CREATE_VARIABLE( double,  AUX_INDEX)
	 KRATOS_CREATE_VARIABLE( double,  EXTERNAL_PRESSURE)
         KRATOS_CREATE_VARIABLE( double, PRESSURE_OLD_IT )
	KRATOS_CREATE_VARIABLE( Vector, BDF_COEFFICIENTS )


	// for mengmeng application
	KRATOS_CREATE_VARIABLE( double, TEMPERATURE_NULL )
	KRATOS_CREATE_VARIABLE( double, TEMPERATURE_EINS )
	KRATOS_CREATE_VARIABLE( double, SURFACE_FLOW_HEAT )
	KRATOS_CREATE_VARIABLE( double, SURFACE_FLOW_WATER )
	KRATOS_CREATE_VARIABLE( double, ICE_VOLUME_FRACTION )
	KRATOS_CREATE_VARIABLE( double, ICE_VOLUME_FRACTION_NULL )
	KRATOS_CREATE_VARIABLE( double, ICE_VOLUME_FRACTION_EINS )

	//for xfem application
	KRATOS_CREATE_VARIABLE(double, CRACK_OPENING)
	KRATOS_CREATE_VARIABLE(double, CRACK_TRANSLATION)

	 //for level set application
	 KRATOS_CREATE_VARIABLE(double, IS_DIVIDED)

	  KratosApplication::KratosApplication() :
		  	mCondition3D(0, Element::GeometryType::Pointer(new Triangle3D3<Node<3> >(Element::GeometryType::PointsArrayType(3, Node<3>())))),
			mCondition2D(0, Element::GeometryType::Pointer(new Geometry<Node<3> >(Element::GeometryType::PointsArrayType(2, Node<3>())))),
			mpVariableData(KratosComponents<VariableData>::pGetComponents()),
			mpDoubleVariables(KratosComponents<Variable<double> >::pGetComponents()),
			mpArray1DVariables(KratosComponents<Variable<array_1d<double, 3> > >::pGetComponents()),
			mpVectorVariables(KratosComponents<Variable<Vector> >::pGetComponents()),
			mpMatrixVariables(KratosComponents<Variable<Matrix> >::pGetComponents()),
			mpArray1DVariableComponents(KratosComponents<VariableComponent<VectorComponentAdaptor<array_1d<double, 3> > > >::pGetComponents()),
			mpElements(KratosComponents<Element>::pGetComponents()), 
			mpConditions(KratosComponents<Condition>::pGetComponents())
	  {}

  void KratosApplication::RegisterVariables()
    {
        KRATOS_REGISTER_VARIABLE(IS_INACTIVE)

        KRATOS_REGISTER_VARIABLE(OSS_SWITCH)
	KRATOS_REGISTER_VARIABLE(DYNAMIC_TAU)

	KRATOS_REGISTER_VARIABLE(NEIGHBOURS_INDICES)
	KRATOS_REGISTER_VARIABLE(PARTITION_INDEX)
	KRATOS_REGISTER_VARIABLE(ERASE_FLAG)
	KRATOS_REGISTER_VARIABLE(NL_ITERATION_NUMBER)
	KRATOS_REGISTER_VARIABLE(FRACTIONAL_STEP)

	KRATOS_REGISTER_VARIABLE(TIME)
	KRATOS_REGISTER_VARIABLE(TIME_STEPS)
	KRATOS_REGISTER_VARIABLE(START_TIME)
	KRATOS_REGISTER_VARIABLE(END_TIME)
	KRATOS_REGISTER_VARIABLE(DELTA_TIME)
	KRATOS_REGISTER_VARIABLE(TEMPERATURE)
	KRATOS_REGISTER_VARIABLE(PRESSURE)
	KRATOS_REGISTER_VARIABLE(DENSITY)
	KRATOS_REGISTER_VARIABLE(VISCOSITY)
	KRATOS_REGISTER_VARIABLE(ERROR_RATIO)
    KRATOS_REGISTER_VARIABLE(TAU)

	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_ACCELERATION)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_VELOCITY)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION)
  	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY)
  	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ROTATION)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM)
  	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(REACTION)
  	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(BODY_FORCE)
  	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(SEEPAGE_DRAG)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MESH_VELOCITY)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(NORMAL)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FORCE)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FORCE_CM)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM_CM)


	KRATOS_REGISTER_VARIABLE(NEIGHBOUR_NODES);
	KRATOS_REGISTER_VARIABLE(NEIGHBOUR_ELEMENTS);
	KRATOS_REGISTER_VARIABLE(NEIGHBOUR_CONDITIONS);

	KRATOS_REGISTER_VARIABLE( INERTIA )

	//for structural application TO BE REMOVED
        KRATOS_REGISTER_VARIABLE(MATERIAL_PARAMETERS)
	KRATOS_REGISTER_VARIABLE(WRINKLING_APPROACH )
	KRATOS_REGISTER_VARIABLE(GREEN_LAGRANGE_STRAIN_TENSOR )
	KRATOS_REGISTER_VARIABLE(PK2_STRESS_TENSOR )
    KRATOS_REGISTER_VARIABLE(CAUCHY_STRESS_TENSOR )
	KRATOS_REGISTER_VARIABLE(AUXILIARY_MATRIX_1 )
	KRATOS_REGISTER_VARIABLE(YOUNG_MODULUS )
	KRATOS_REGISTER_VARIABLE(POISSON_RATIO )
	KRATOS_REGISTER_VARIABLE(THICKNESS )
	KRATOS_REGISTER_VARIABLE(NEGATIVE_FACE_PRESSURE )
	KRATOS_REGISTER_VARIABLE(POSITIVE_FACE_PRESSURE )
	KRATOS_REGISTER_VARIABLE(INITIAL_PENALTY)
	KRATOS_REGISTER_VARIABLE(CONSTITUTIVE_LAW)
	KRATOS_REGISTER_VARIABLE(DP_EPSILON)
	KRATOS_REGISTER_VARIABLE(INSITU_STRESS)
	KRATOS_REGISTER_VARIABLE(DP_ALPHA1)
	KRATOS_REGISTER_VARIABLE(DP_K)
	KRATOS_REGISTER_VARIABLE(CALCULATE_INSITU_STRESS)
	//CONTACT_LINK_MASTER is defined in condition.h
// 	KRATOS_REGISTER_VARIABLE(CONTACT_LINK_MASTER )
 	//CONTACT_LINK_SLAVE is defined in condition.h
	KRATOS_REGISTER_VARIABLE(CONTACT_RAMP )
	KRATOS_REGISTER_VARIABLE(PENALTY )
	KRATOS_REGISTER_VARIABLE(PENALTY_T )
	KRATOS_REGISTER_VARIABLE(FRICTION_COEFFICIENT )
    KRATOS_REGISTER_VARIABLE(LAMBDA )
    KRATOS_REGISTER_VARIABLE(MIU )
    KRATOS_REGISTER_VARIABLE(LAMBDAS )
	KRATOS_REGISTER_VARIABLE(LAMBDAS_T )
	KRATOS_REGISTER_VARIABLE(GAPS )
	KRATOS_REGISTER_VARIABLE(DELTA_LAMBDAS )
	KRATOS_REGISTER_VARIABLE(DELTA_LAMBDAS_T )
	KRATOS_REGISTER_VARIABLE(CONTACT_SLAVE_INTEGRATION_POINT_INDEX )
	KRATOS_REGISTER_VARIABLE(CONTACT_LINK_M )
	KRATOS_REGISTER_VARIABLE(CONTACT_DOUBLE_CHECK )
	KRATOS_REGISTER_VARIABLE(IS_CONTACT_MASTER )
	KRATOS_REGISTER_VARIABLE(IS_CONTACT_SLAVE )
	KRATOS_REGISTER_VARIABLE(STICK)
	KRATOS_REGISTER_VARIABLE(FIRST_TIME_STEP)
	KRATOS_REGISTER_VARIABLE(QUASI_STATIC_ANALYSIS )
	KRATOS_REGISTER_VARIABLE( NORMAL_STRESS )
	KRATOS_REGISTER_VARIABLE( TANGENTIAL_STRESS )
	KRATOS_REGISTER_VARIABLE( NORMAL_CONTACT_STRESS )
	KRATOS_REGISTER_VARIABLE( TANGENTIAL_CONTACT_STRESS )
	KRATOS_REGISTER_VARIABLE( CONTACT_STICK )
			
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE)
	KRATOS_REGISTER_VARIABLE(REACTION_WATER_PRESSURE)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_DT)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_ACCELERATION)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_NULL)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_NULL_DT)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_NULL_ACCELERATION)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_EINS)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_EINS_DT)
	KRATOS_REGISTER_VARIABLE(WATER_PRESSURE_EINS_ACCELERATION)
				
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE)
	KRATOS_REGISTER_VARIABLE(REACTION_AIR_PRESSURE)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_DT)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_ACCELERATION)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_NULL)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_NULL_DT)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_NULL_ACCELERATION)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_EINS)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_EINS_DT)
	KRATOS_REGISTER_VARIABLE(AIR_PRESSURE_EINS_ACCELERATION)
    KRATOS_REGISTER_VARIABLE(SUCTION)
		
	KRATOS_REGISTER_VARIABLE(DISPLACEMENT_OLD)
	KRATOS_REGISTER_VARIABLE(DISPLACEMENT_DT)
// 	KRATOS_REGISTER_VARIABLE(ACCELERATION)
	KRATOS_REGISTER_VARIABLE(DISPLACEMENT_NULL)
	KRATOS_REGISTER_VARIABLE(DISPLACEMENT_NULL_DT)
	KRATOS_REGISTER_VARIABLE(ACCELERATION_NULL)
	KRATOS_REGISTER_VARIABLE(DISPLACEMENT_EINS)
	KRATOS_REGISTER_VARIABLE(DISPLACEMENT_EINS_DT)
	KRATOS_REGISTER_VARIABLE(ACCELERATION_EINS)
	KRATOS_REGISTER_VARIABLE(ELASTIC_LEFT_CAUCHY_GREEN_OLD)
		
	KRATOS_REGISTER_VARIABLE(ACTIVATION_LEVEL)
	KRATOS_REGISTER_VARIABLE(FLAG_VARIABLE )
	KRATOS_REGISTER_VARIABLE(DISTANCE )
    KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( LAGRANGE_DISPLACEMENT )
    KRATOS_REGISTER_VARIABLE( LAGRANGE_AIR_PRESSURE )
    KRATOS_REGISTER_VARIABLE( LAGRANGE_WATER_PRESSURE )
    KRATOS_REGISTER_VARIABLE( LAGRANGE_TEMPERATURE )


	//for ALE application TO BE REMOVED
	KRATOS_REGISTER_VARIABLE(IS_INTERFACE )
	KRATOS_REGISTER_VARIABLE(IS_VISITED)

            
    //for electric_application
    KRATOS_REGISTER_VARIABLE( ELECTRIC_POTENTIAL )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_DT )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_DT2 )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_NULL )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_EINS )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_NULL_DT )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_EINS_DT )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_NULL_DT2 )
    KRATOS_REGISTER_VARIABLE(ELECTRIC_POTENTIAL_EINS_DT2 )
    KRATOS_REGISTER_VARIABLE(LAGRANGE_ELECTRIC_POTENTIAL)
    KRATOS_REGISTER_VARIABLE(CONCENTRATION )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_DT )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_DT2 )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_NULL )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_EINS )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_NULL_DT )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_EINS_DT )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_NULL_DT2 )
    KRATOS_REGISTER_VARIABLE(CONCENTRATION_EINS_DT2 )
    KRATOS_REGISTER_VARIABLE(LAGRANGE_CONCENTRATION)

    KRATOS_REGISTER_VARIABLE( INERTIA )
    KRATOS_REGISTER_VARIABLE( FC )
    KRATOS_REGISTER_VARIABLE( FT )
    KRATOS_REGISTER_VARIABLE( FRACTURE_ENERGY ) 
    KRATOS_REGISTER_VARIABLE( CONCRETE_YOUNG_MODULUS_C)
    KRATOS_REGISTER_VARIABLE( CONCRETE_YOUNG_MODULUS_T)
    KRATOS_REGISTER_VARIABLE( BASE )
    KRATOS_REGISTER_VARIABLE( HEIGHT)
    KRATOS_REGISTER_VARIABLE( YIELD_STRESS)
    KRATOS_REGISTER_VARIABLE(LAMNDA)   
    KRATOS_REGISTER_VARIABLE(DAMAGE )
    KRATOS_REGISTER_VARIABLE(VECTOR_DAMAGE)
    KRATOS_REGISTER_VARIABLE(ORTHOTROPIC_YOUNG_MODULUS_2D) // [E1 E2 G12]
    KRATOS_REGISTER_VARIABLE(ORTHOTROPIC_POISSON_RATIO_2D) // [v12 v21]
    KRATOS_REGISTER_VARIABLE(ORTHOTROPIC_ANGLE)
    KRATOS_REGISTER_VARIABLE(VOLUMEN_FRACTION)
    KRATOS_REGISTER_VARIABLE(FRICTION_INTERNAL_ANGLE)
    KRATOS_REGISTER_VARIABLE(COHESION)
    KRATOS_REGISTER_VARIABLE(ORTHOTROPIC_ELASTIC_LIMIT)
    KRATOS_REGISTER_VARIABLE(ISOTROPIC_ELASTIC_LIMIT) 



	//for PFEM application TO BE REMOVED
	KRATOS_REGISTER_VARIABLE( NODAL_AREA)
	KRATOS_REGISTER_VARIABLE( NODAL_H)
	KRATOS_REGISTER_VARIABLE( IS_STRUCTURE)
	KRATOS_REGISTER_VARIABLE( IS_POROUS)
	KRATOS_REGISTER_VARIABLE( IS_WATER)
	KRATOS_REGISTER_VARIABLE( IS_FLUID)
	KRATOS_REGISTER_VARIABLE( IS_BOUNDARY)
	KRATOS_REGISTER_VARIABLE( IS_FREE_SURFACE)
	KRATOS_REGISTER_VARIABLE( IS_LAGRANGIAN_INLET)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(NORMAL_TO_WALL)
	KRATOS_REGISTER_VARIABLE( IS_WATER_ELEMENT)

	KRATOS_REGISTER_VARIABLE( BULK_MODULUS )
	KRATOS_REGISTER_VARIABLE( SATURATION )	
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( GRAVITY)	
	KRATOS_REGISTER_VARIABLE( DENSITY_WATER )
	KRATOS_REGISTER_VARIABLE(VISCOSITY_WATER)
	KRATOS_REGISTER_VARIABLE( DENSITY_AIR )
	KRATOS_REGISTER_VARIABLE(VISCOSITY_AIR)
	KRATOS_REGISTER_VARIABLE( POROSITY )
	KRATOS_REGISTER_VARIABLE( AIR_ENTRY_VALUE )
	KRATOS_REGISTER_VARIABLE( FIRST_SATURATION_PARAM )
	KRATOS_REGISTER_VARIABLE( SECOND_SATURATION_PARAM )
	KRATOS_REGISTER_VARIABLE( PERMEABILITY_WATER )
	KRATOS_REGISTER_VARIABLE( PERMEABILITY_AIR )
	KRATOS_REGISTER_VARIABLE( BULK_AIR )
	KRATOS_REGISTER_VARIABLE( SCALE )
        KRATOS_REGISTER_VARIABLE( IS_JACK_LINK )
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( FACE_LOAD )
	KRATOS_REGISTER_VARIABLE(SOUND_VELOCITY)
	KRATOS_REGISTER_VARIABLE(AIR_SOUND_VELOCITY)
	KRATOS_REGISTER_VARIABLE(WATER_SOUND_VELOCITY)

	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FRACT_VEL)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(PRESS_PROJ)
	KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(CONV_PROJ)
         KRATOS_REGISTER_VARIABLE(NODAL_MASS)
	 KRATOS_REGISTER_VARIABLE(AUX_INDEX)
	 KRATOS_REGISTER_VARIABLE(EXTERNAL_PRESSURE)
         KRATOS_REGISTER_VARIABLE( PRESSURE_OLD_IT )
	KRATOS_REGISTER_VARIABLE( BDF_COEFFICIENTS )

	KRATOS_REGISTER_VARIABLE( DIVPROJ)
	KRATOS_REGISTER_VARIABLE( THAWONE)
	KRATOS_REGISTER_VARIABLE(THAWTWO)
 KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ADVPROJ)

	//for xfem application
	KRATOS_REGISTER_VARIABLE(CRACK_OPENING)
	KRATOS_REGISTER_VARIABLE(CRACK_TRANSLATION)

	// MINE VM!
	  KRATOS_REGISTER_VARIABLE( MU )

	KRATOS_REGISTER_VARIABLE(ARRHENIUS)
	KRATOS_REGISTER_VARIABLE(ARRHENIUSAUX)
	KRATOS_REGISTER_VARIABLE(PRESSUREAUX)
	KRATOS_REGISTER_VARIABLE( NODAL_MAUX )	
        KRATOS_REGISTER_VARIABLE( NODAL_PAUX )
	// Registering elements and conditions here
	KRATOS_REGISTER_CONDITION("Condition3D", mCondition3D)
	KRATOS_REGISTER_CONDITION("Condition2D", mCondition2D)


	// for mengmeng application
	KRATOS_REGISTER_VARIABLE(TEMPERATURE_NULL )
	KRATOS_REGISTER_VARIABLE(TEMPERATURE_EINS )
	KRATOS_REGISTER_VARIABLE(SURFACE_FLOW_HEAT )
	KRATOS_REGISTER_VARIABLE(SURFACE_FLOW_WATER )
	KRATOS_REGISTER_VARIABLE(ICE_VOLUME_FRACTION )
	KRATOS_REGISTER_VARIABLE(ICE_VOLUME_FRACTION_NULL )
	KRATOS_REGISTER_VARIABLE(ICE_VOLUME_FRACTION_EINS )



	 //for level set application
	 KRATOS_REGISTER_VARIABLE(IS_DIVIDED )
    }

	// Specialize array of compenents for VariableData
	 KratosComponents<VariableData>::ComponentsContainerType KratosComponents<VariableData>::msComponents;

	// Initializing static members
/*	const Condition  KratosApplication::msCondition3D(0, Element::GeometryType::Pointer(new Triangle3D<Node<3> >(Element::GeometryType::PointsArrayType(3, Node<3>()))));
	const Condition  KratosApplication::msCondition2D(0, Element::GeometryType::Pointer(new Geometry<Node<3> >(Element::GeometryType::PointsArrayType(2, Node<3>()))));
*/

}  // namespace Kratos.



