/*
//  KRATOS  _____________
//         /  _/ ____/   |
//         / // / __/ /| |
//       _/ // /_/ / ___ |
//      /___/\____/_/  |_| Application
//
//  Main authors:   Thomas Oberbichler
*/

#if !defined(KRATOS_IGA_APPLICATION_VARIABLES_H_INCLUDED)
#define  KRATOS_IGA_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "includes/variables.h"

namespace Kratos
{

<<<<<<< HEAD

KRATOS_DEFINE_VARIABLE(int, BREP_ID)

KRATOS_DEFINE_VARIABLE(double, NURBS_CONTROL_POINT_WEIGHT)

KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(COORDINATES)
KRATOS_DEFINE_VARIABLE(Vector, LOCAL_COORDINATES)
KRATOS_DEFINE_VARIABLE(Vector, TANGENTS)
KRATOS_DEFINE_VARIABLE(Vector, TANGENTS_SLAVE)

KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, double, CROSS_AREA)
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, double, PRESTRESS_CAUCHY)

KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, Vector, SHAPE_FUNCTION_VALUES)
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, Matrix, SHAPE_FUNCTION_LOCAL_DERIVATIVES)
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, Matrix, SHAPE_FUNCTION_LOCAL_SECOND_DERIVATIVES)

<<<<<<< HEAD
KRATOS_DEFINE_VARIABLE(Vector, SHAPE_FUNCTION_VALUES_SLAVE)
KRATOS_DEFINE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_DERIVATIVES_SLAVE)
KRATOS_DEFINE_VARIABLE(Matrix, SHAPE_FUNCTION_LOCAL_SECOND_DERIVATIVES_SLAVE)

KRATOS_DEFINE_VARIABLE(double, RAYLEIGH_ALPHA)
KRATOS_DEFINE_VARIABLE(double, RAYLEIGH_BETA)
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(NODAL_INERTIA)

//Postprocessing variables
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(STRESS_RESULTANT_FORCE)
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(STRESS_RESULTANT_MOMENT)

//Condition Variables
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(POINT_LOAD)
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(LINE_LOAD)
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(SURFACE_LOAD)

KRATOS_DEFINE_VARIABLE(double, PENALTY_FACTOR)
=======
=======
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, double, CROSS_AREA)
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, double, PRESTRESS_CAUCHY)

>>>>>>> origin/master
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, double, RAYLEIGH_ALPHA)
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, double, RAYLEIGH_BETA)

//Load Condition Variables
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(IGA_APPLICATION, POINT_LOAD)
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(IGA_APPLICATION, LINE_LOAD)
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(IGA_APPLICATION, SURFACE_LOAD)

KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(IGA_APPLICATION, DEAD_LOAD)

//Penalty Variables
KRATOS_DEFINE_APPLICATION_VARIABLE(IGA_APPLICATION, double, PENALTY_FACTOR)
>>>>>>> origin/master

} // namespace Kratos

#endif // !defined(KRATOS_IGA_APPLICATION_VARIABLES_H_INCLUDED)
