#include "meshless_application_variables.h"

namespace Kratos
{
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( PRESSURE_ACC );
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( VISCOUS_ACC );
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( BODYFORCE_ACC );
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( BOUNDARY_ACC );
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( XSPH_VELOCITY );

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( TEMP_POS );
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( TEMP_VEL );
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( TEMP_RHS );
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( TEMP_DISP );


KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( OLD_VEL );

KRATOS_CREATE_VARIABLE(double, EFFECTIVE_RADIUS);

KRATOS_CREATE_VARIABLE(double, DENSITY_NORM_PARAM);
KRATOS_CREATE_VARIABLE(double, DIV_OF_VEL);

KRATOS_CREATE_VARIABLE(double, OLD_DENSITY);

KRATOS_CREATE_VARIABLE(double, DENS_VARIATION);
KRATOS_CREATE_VARIABLE(double, DENS_DIFF);
KRATOS_CREATE_VARIABLE(double, IS_WET);
KRATOS_CREATE_VARIABLE(double, INI_PRESSURE);

KRATOS_CREATE_VARIABLE(double, OUT_OF_SYSTEM);




KRATOS_CREATE_VARIABLE(double, VER_WALL_LEFT);
KRATOS_CREATE_VARIABLE(double, VER_WALL_RIGHT);
KRATOS_CREATE_VARIABLE(double, HOR_WALL_BOTTOM);



KRATOS_CREATE_VARIABLE(double, DUMMY_NORMALIZE_RHS);
KRATOS_CREATE_VARIABLE(double, DUMMY_APPLY_XSPH);
KRATOS_CREATE_VARIABLE(double, DUMMY_BOUNDARY_PRESSURES);
KRATOS_CREATE_VARIABLE(double, DUMMY_CATCH_FREESURFACE);
KRATOS_CREATE_VARIABLE(double, DUMMY_INTERMEDIATE_RHS);
KRATOS_CREATE_VARIABLE(double, DELTA_TIME_ISPH);

}
