@startuml
'https://plantuml.com/class-diagram

class Element

'UPW
class UPwBaseElement

class UPwSmallStrainElement
class TransientPwElement
class SteadyStatePwElement
class UPwSmallStrainFICElement

class UPwSmallStrainInterfaceElement

Element <|-- UPwBaseElement
UPwBaseElement <|-- UPwSmallStrainElement

UPwSmallStrainElement <|-- TransientPwElement
TransientPwElement <|-- SteadyStatePwElement
UPwSmallStrainElement <|-- UPwSmallStrainFICElement

'
'
'Diff Order
class SmallStrainUPwDiffOrderElement

UPwBaseElement <|-- SmallStrainUPwDiffOrderElement

UPwBaseElement <|-- UPwSmallStrainInterfaceElement

class InterfaceElement
Element <|-- InterfaceElement

'Pw Elements
class PwElement
class GeoSteadyStatePwPipingElement

Element <|-- PwElement
Element <|-- GeoSteadyStatePwPipingElement

''Thermal
class TransientThermalElement
Element <|-- TransientThermalElement
'
'
'Structural
class CrBeamElement2D2N_Structural
class CrBeamElementLinear2D2N_Structural
class GeoCrBeamElementLinear2D2N

Element <|-- CrBeamElement2D2N_Structural
CrBeamElement2D2N_Structural <|-- CrBeamElementLinear2D2N_Structural
CrBeamElementLinear2D2N_Structural <|-- GeoCrBeamElementLinear2D2N

@enduml
