//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Ignasi de Pouplana
//

#include "laserdrilling_application_variables.h"

namespace Kratos
{
// TODO: Describe what these variables are and check which ones are in use
KRATOS_CREATE_VARIABLE(double, THERMAL_ENERGY)
KRATOS_CREATE_VARIABLE(double, THERMAL_ENERGY_PER_VOLUME)
KRATOS_CREATE_VARIABLE(double, MATERIAL_THERMAL_ENERGY_PER_VOLUME)
KRATOS_CREATE_VARIABLE(double, THERMAL_DECOMPOSITION)
KRATOS_CREATE_VARIABLE(double, THERMAL_ENERGY_PER_VOLUME_THRESHOLD)
KRATOS_CREATE_VARIABLE(double, ALPHA_THRESHOLD)
KRATOS_CREATE_VARIABLE(int, THERMAL_COUNTER)
KRATOS_CREATE_VARIABLE(std::string, DECOMPOSITION_LAW)
KRATOS_CREATE_VARIABLE(double, DECOMPOSED_ELEMENTAL_VOLUME)
KRATOS_CREATE_VARIABLE(double, ELEMENTAL_VOLUME)
KRATOS_CREATE_VARIABLE(double, A_COEFFICIENT)
KRATOS_CREATE_VARIABLE(double, EA_COEFFICIENT)
KRATOS_CREATE_VARIABLE(double, R_GAS_CONSTANT)
KRATOS_CREATE_VARIABLE(double, M_COEFFICIENT)
KRATOS_CREATE_VARIABLE(double, N_COEFFICIENT)
KRATOS_CREATE_VARIABLE(double, DECOMPOSITION_LAW_REFERENCE_TEMPERATURE)
KRATOS_CREATE_VARIABLE(double, DECOMPOSITION_LAW_CONSTANT_1)
KRATOS_CREATE_VARIABLE(double, DECOMPOSITION_LAW_CONSTANT_2)
KRATOS_CREATE_VARIABLE(double, DECOMPOSED_NODE)
KRATOS_CREATE_VARIABLE(double, IONIZATION_ALPHA)
KRATOS_CREATE_VARIABLE(double, THERMAL_DEPTH)
KRATOS_CREATE_VARIABLE(double, ABLATION_THRESHOLD)
KRATOS_CREATE_VARIABLE(double, PENETRATION_DEPTH)
KRATOS_CREATE_VARIABLE(double, PRE_EVAPORATION_TEMPERATURE)
KRATOS_CREATE_VARIABLE(double, OPTICAL_PENETRATION_DEPTH)
KRATOS_CREATE_VARIABLE(double, ENERGY_PER_VOLUME_THRESHOLD)
KRATOS_CREATE_VARIABLE(double, ENERGY_PER_VOLUME)
KRATOS_CREATE_VARIABLE(double, ENTHALPY_ENERGY_PER_VOLUME)
KRATOS_CREATE_VARIABLE(double, IONIZATION_ENERGY_PER_VOLUME)
KRATOS_CREATE_VARIABLE(double, REFRACTIVE_INDEX)

}
