//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Ignasi de Pouplana
//

#if !defined(KRATOS_LASER_DRILLING_APPLICATION_VARIABLES_H_INCLUDED)
#define KRATOS_LASER_DRILLING_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "includes/variables.h"
#include "convection_diffusion_application_variables.h"

namespace Kratos
{

// Variables definition
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, THERMAL_ENERGY)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, THERMAL_ENERGY_PER_VOLUME)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, THERMAL_DECOMPOSITION)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, DECOMPOSITION_LAW_REFERENCE_TEMPERATURE)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, DECOMPOSITION_LAW_CONSTANT_1)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, DECOMPOSITION_LAW_CONSTANT_2)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, THERMAL_ENERGY_PER_VOLUME_THRESHOLD)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, ALPHA_THRESHOLD)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, int, THERMAL_COUNTER)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, std::string, DECOMPOSITION_LAW)
KRATOS_DEFINE_APPLICATION_VARIABLE(LASER_DRILLING_APPLICATION, double, DECOMPOSED_ELEMENTAL_VOLUME)

}

#endif /* KRATOS_LASER_DRILLING_APPLICATION_VARIABLES_H_INCLUDED */
