#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es {Model validation} {Validación del modelo}
::msgcat::mcset es Close Cerrar
::msgcat::mcset es {Close the report window} {Cerrar la ventana de informe}
::msgcat::mcset es Print Imprimir
::msgcat::mcset es {Print the report via a temporal file using notepad} {Imprimir informe vía archivo temporal en notepad}
::msgcat::mcset es {Could not make a backup copy of Kratos interface data file (%s)} {No se puede hacer una copia del fichero de Kratos (%s)}
::msgcat::mcset es {Cannot write file %s. Permission denied} {No se puede escribir el fichero %s. Permiso denegado}
::msgcat::mcset es {Error reading file %s %s %s problem type has been not correctly installed} {Error leyendo archivo %s %s %s el problem type no está correctamente instalado}
::msgcat::mcset es Kratos#C#menu Kratos
::msgcat::mcset es {Entities group editor#C#menu} {Editor de grupos de entidades}
::msgcat::mcset es {Model properties#C#menu} {Propiedades del modelo}
::msgcat::mcset es {Material database#C#menu} {Base de datos de materiales}
::msgcat::mcset es {Function editor#C#menu} {Editor de funciones}
::msgcat::mcset es {Project settings#C#menu} {Propiedades proyecto}
::msgcat::mcset es {Define the group properties using the group editor} {Defina el grupo de propiedades con el editor de grupos}
::msgcat::mcset es {Define the model properties} {Define las propiedades del modelo}
::msgcat::mcset es {Define the material properties} {Define las propiedades del modelo}
::msgcat::mcset es {Open the process control window} {Abrir ventana de control de proceso}
::msgcat::mcset es {Run the simulation} {Ejecutar la simulación}
::msgcat::mcset es {View process info} {Ver información de proyecto}
::msgcat::mcset es {Cancel process} {Cancelar proceso}
::msgcat::mcset es {Model definition toolbar} {Toolbar de definición del modelo}
::msgcat::mcset es {Kratos global settings} {Kratos global settings}
::msgcat::mcset es {Save and Close} {Guardar y cerrar}
::msgcat::mcset es {The project must be saved} {El proyecto tiene que estar guardado}
::msgcat::mcset es {Printing is only supported under Windows} {Solo se puede imprimir en Windows}
::msgcat::mcset es {An error has been detected when get a temporal directory} {Se ha detectado un error accediendo a un directorio temporal}
::msgcat::mcset es Model Modelo
::msgcat::mcset es Materials Materiales
::msgcat::mcset es Properties Propiedades
::msgcat::mcset es Root Raíz
::msgcat::mcset es {Entity %s} {Entidad %s}
::msgcat::mcset es {Entity $command} {Entidad $command}
::msgcat::mcset es {Create automatic new group} {Crear grupo automáticamente}
::msgcat::mcset es {The new group '%s' has not any usefull entity assigned.} {El nuevo grupo '%s' no tiene ningun entdad asignadaº}
::msgcat::mcset es {The property name can not be empty} {El nombre de propiedad no puede ser vacío}
::msgcat::mcset es {This name property it is already assigned.} {Este nombre de propiedad ya está asignado.}
::msgcat::mcset es {You have to choose one group
 (you can create a new one pushing the button on the right)} {Tiene que elegir un grupo (se puede crear uno con el botón de la izquierda)}
::msgcat::mcset es {This group it is already assigned to this condition.} {Este grupo ya esta asignado a esta condición.}
::msgcat::mcset es Group: Grupo:
::msgcat::mcset es {Confirm values} {Confirmar valores}
::msgcat::mcset es {This property name already exist.} {El nombre de propiedad ya existe.}
::msgcat::mcset es New Nuevo
::msgcat::mcset es Delete Eliminar
::msgcat::mcset es Edit Editar
::msgcat::mcset es {Collapse All} {Colapsar todos}
::msgcat::mcset es {Expand All} {Expandir todos}
::msgcat::mcset es {You must define a valid Property for this element type.} {Debe definir una propiedad válida para este tipo de elemento}
::msgcat::mcset es %s %s
::msgcat::mcset es {Function manager} {Administrador de funciones}
::msgcat::mcset es newGroup {nuevo grupo}
::msgcat::mcset es Cancel Cancelar
::msgcat::mcset es {You must define a Property before!} {Antes debe definir una propiedad.}
::msgcat::mcset es {You must define a Property before.} {Antes debe definir una propiedad.}
::msgcat::mcset es {This property it is assigned to %s groups.
Do you want to delete the property and all this groups?} {Esta propiedad esta asignada a %s.
Desea borrar la propiedad y todos sus grupos?}
::msgcat::mcset es {Add a new function} {Añadir nueva función}
::msgcat::mcset es {Delete the selected function} {Borrar la función seleccionada}
::msgcat::mcset es {Assign the selection function and close editor} {Assign the selection function and close editor}
::msgcat::mcset es {Please, select the function you want to assign to '%s'.} {Please, select the function you want to assign to '%s'.}
::msgcat::mcset es {Function Id} {Function Id}
::msgcat::mcset es {Function definition} {Function definition}
::msgcat::mcset es {Name id:} {Name id:}
::msgcat::mcset es {$cmbPid:} {$cmbPid:}
::msgcat::mcset es {$cmbTooltip} {$cmbTooltip}
::msgcat::mcset es {Kratos variables:} {Variables Kratos:}
::msgcat::mcset es {Create new material} {Crear nuevo material}
::msgcat::mcset es {Delete material} {Borrar material}
::msgcat::mcset es {Refresh Tree} {Refrescar árbol}
::msgcat::mcset es {New Material} {Nuevo material}
::msgcat::mcset es {Delete Material} {Borrar material}
::msgcat::mcset es {Rename material} {Renombrar material}
::msgcat::mcset es {Copy material} {Copiar material}
::msgcat::mcset es {Unassign function} {Desasignar función}
::msgcat::mcset es {Project properties} {Propiedades de proyecto}
::msgcat::mcset es {Press 'Finish' to stop the entities selection} {Pulse 'Finalizar' para parar la selección de entidades}
::msgcat::mcset es {Group Id} {Grupo id}
::msgcat::mcset es {Define the curve properties} {Define las propiedades de la curva}
::msgcat::mcset es {Compressible fluids are not available in this version} {Fluidos compresibles no están disponibles en esta versión}
::msgcat::mcset es {PFEM is not available in this version.
You need the GiD version 11.1.2d or higher.} {PFEM no está disponible en esta versión.
Necesita la versión GiD 11.1.2d o superior.}
::msgcat::mcset es {Cut Id} {Corte Id}
::msgcat::mcset es {Choose a new cut identifier} {Elija nuevo identificador de corte}
::msgcat::mcset es {Graph Id} {Gráfico Id}
::msgcat::mcset es {Choose a new graph identifier} {Elija un nuevo identificador gráfico}
::msgcat::mcset es {Property Id} {Propiedad Id}
::msgcat::mcset es {Choose a new property identifier} {Elija un nuevo identificador de la propiedad}
::msgcat::mcset es {Assign the defined properties} {Asignar las propiedades definidas}
::msgcat::mcset es {Cancel the defined properties} {Cancelar las propiedades definidas}
::msgcat::mcset es {You can't use some reservate chars like:
  :   /   $   .   \\  %} {No se pueden utilizar algunos carácteres reservados:

  :   /   $   .   \\  %}
::msgcat::mcset es Curves Curvas
::msgcat::mcset es {Double-click toggle window or inline visualization} {Doble clic cambia entre ventana o visualización en línea}
::msgcat::mcset es {Double click here to tear off the window} {Haga doble clic aquí para hacer exterior la ventana}
::msgcat::mcset es {Double click here to integrate the window} {Haga doble clic aquí para integrar la ventana}
::msgcat::mcset es {Rename Error Window} {Cambiar el nombre de la ventana de error}
::msgcat::mcset es {View group entities} {Ver entidades de grupo}
::msgcat::mcset es 0 0
::msgcat::mcset es 0.0 0.0
::msgcat::mcset es 0.001 0.001
::msgcat::mcset es 0.01 0.01
::msgcat::mcset es 0.1 0.1
::msgcat::mcset es 1 1
::msgcat::mcset es 1.0 1.0
::msgcat::mcset es 2 2
::msgcat::mcset es 2D 2D
::msgcat::mcset es {2nd Piola - Kirchhoff stress tensor} {2nda Piola - tensor de stress Kirchhoff}
::msgcat::mcset es 3D 3D
::msgcat::mcset es A11 A11
::msgcat::mcset es A12 A12
::msgcat::mcset es A13 A13
::msgcat::mcset es A21 A21
::msgcat::mcset es A22 A22
::msgcat::mcset es A23 A23
::msgcat::mcset es A31 A31
::msgcat::mcset es A32 A32
::msgcat::mcset es A33 A33
::msgcat::mcset es ASGS ASGS
::msgcat::mcset es {Absolute pressure tolerance} {Presión de tolerancia absoluta}
::msgcat::mcset es {Absolute velocity tolerance} {Velocidad de tolerancia absoluta}
::msgcat::mcset es Activate Activar
::msgcat::mcset es Activation Activación
::msgcat::mcset es {Add a new Property} {Añadir nueva propiedad}
::msgcat::mcset es Advanced Avanzado
::msgcat::mcset es Air Aire
::msgcat::mcset es Aluminium_7021 Aluminio
::msgcat::mcset es {Analysis Data} {Analisis de datos}
::msgcat::mcset es {Analysis Type} {Tipo de análisis}
::msgcat::mcset es {Analysis data} {Analisis de datos}
::msgcat::mcset es {Analysis type} {Tipo de análisis}
::msgcat::mcset es {Angular Velocity} {Velocidad angular}
::msgcat::mcset es {Application types} {Tipos de aplicación}
::msgcat::mcset es {Arc length methods} {Métodos de longitud de arco}
::msgcat::mcset es Area Area
::msgcat::mcset es Ascii Ascii
::msgcat::mcset es Automatic Automático
::msgcat::mcset es {Automatic delta time} {Auto de hora delta}
::msgcat::mcset es B11 B11
::msgcat::mcset es B12 B12
::msgcat::mcset es B13 B13
::msgcat::mcset es B21 B21
::msgcat::mcset es B22 B22
::msgcat::mcset es B23 B23
::msgcat::mcset es B31 B31
::msgcat::mcset es B32 B32
::msgcat::mcset es B33 B33
::msgcat::mcset es BC BC
::msgcat::mcset es {Beam element} {Elemento viga}
::msgcat::mcset es {Beam element type} {Tipo de elemento de viga}
::msgcat::mcset es {Beam total Lagrangian} {Viga total Lagrangiana}
::msgcat::mcset es Beams Beams
::msgcat::mcset es {BiConjugate gradient stabilized} {Gradientes biconjugados estabilizado}
::msgcat::mcset es Binary Binario
::msgcat::mcset es {Body forces} {Fuerzas cuerpo}
::msgcat::mcset es {Bounding Box} {Caja delimitadora}
::msgcat::mcset es Boundingbox {Caja delimitadora}
::msgcat::mcset es {Bulk Modulus} {Módulo Bulk}
::msgcat::mcset es {Check problem type version} {Comprobar versión del problema tipo}
::msgcat::mcset es {Company name} {Nombre de comañia}
::msgcat::mcset es {Convergence criteria} {Criterio de convergencia}
::msgcat::mcset es {Cross section area} {Sección transversal}
::msgcat::mcset es {Curve Id} {Curva Id}
::msgcat::mcset es {Curve Identifier} {Identificador Curve}
::msgcat::mcset es {Curve Type} {Tipo de curva}
::msgcat::mcset es {Curve definition} {Definición de la curva}
::msgcat::mcset es {Cut plane postprocess options} {Opciones de plano de corte}
::msgcat::mcset es {Cut planes} {Planos de corte}
::msgcat::mcset es {Cut properties} {Propiedades corte}
::msgcat::mcset es Cx Cx
::msgcat::mcset es Cy Cy
::msgcat::mcset es Cz Cz
::msgcat::mcset es D11 D11
::msgcat::mcset es D12 D12
::msgcat::mcset es D13 D13
::msgcat::mcset es D21 D21
::msgcat::mcset es D22 D22
::msgcat::mcset es D23 D23
::msgcat::mcset es D31 D31
::msgcat::mcset es D32 D32
::msgcat::mcset es D33 D33
::msgcat::mcset es {Define the diameter value} {Definir el valor del diámetro}
::msgcat::mcset es {Define the divergence cleareance step value} {Defina el valor del paso despacho de divergencia}
::msgcat::mcset es {Define the flag variable properties} {Defina las propiedades de la variable bandera}
::msgcat::mcset es {Define the linear Darcy coefficient value} {Defina el valor del coeficiente de Darcy lineal}
::msgcat::mcset es {Define the nonlinear Darcy coefficient value} {Defina el valor del coeficiente de Darcy no lineal}
::msgcat::mcset es {Define the porosity value} {Defina el valor de porosidad}
::msgcat::mcset es {Define the positive or negative pressure} {Definir la presión positiva o negativa}
::msgcat::mcset es {Define the positive or negative shell pressure} {Definir la presión shell positivo o negativo}
::msgcat::mcset es {Define the turbulent viscosity value} {Defina el valor de la viscosidad turbulenta}
::msgcat::mcset es {Define the value} {Definir el valor}
::msgcat::mcset es {Defines which side of the face that matches the direction of the normal to the surface, positive or negative} {Define qué lado de la cara que coincide con la dirección de la normal a la superficie, positivo o negativo}
::msgcat::mcset es {Delta time} {Tiempo delta}
::msgcat::mcset es Density Densidad
::msgcat::mcset es Description Descripción
::msgcat::mcset es {Developing in process} {Proceso en desarrollo}
::msgcat::mcset es Diagonal Diagonal
::msgcat::mcset es Diameter Diámetro
::msgcat::mcset es {Dilatancy angle} {Ángulo de dilatación}
::msgcat::mcset es Direct Directo
::msgcat::mcset es {Direct solver type} {Tipo de solver directo}
::msgcat::mcset es Discrete Discreto
::msgcat::mcset es {Discrete with dt} {Discreto con dt}
::msgcat::mcset es Displacement Desplazamiento
::msgcat::mcset es {Displacement absolute tolerance} {Desplazamiento de tolerancia absoluto}
::msgcat::mcset es {Displacement and residual} {Desplazamiento y residual}
::msgcat::mcset es {Displacement convergence tolerance} {Tolerancia de convergencia del desplazamiento}
::msgcat::mcset es {Displacement or residual} {Displazamiento o residual}
::msgcat::mcset es Displacements DEsplazamientos
::msgcat::mcset es Distance Distancia
::msgcat::mcset es {Distance variable for the free surface using level set method} {Variable de Distancia de la superficie libre utilizando el método de conjunto de nivel}
::msgcat::mcset es {Divergence cleareance step} {Paso despacho de divergencia}
::msgcat::mcset es Domain Dominio
::msgcat::mcset es {Drag calculation} {Arrastre cálculo}
::msgcat::mcset es {Drag calculation properties} {Arrastre Cálculo propiedades}
::msgcat::mcset es Drucker-Prager Drucker-Prager
::msgcat::mcset es Dynamic Dinámico
::msgcat::mcset es {EBST (formulation)} {EBST (formulación)}
::msgcat::mcset es {Electrical permitivity} {Permitividad eléctrica}
::msgcat::mcset es {Element Type} {Tipo de elemento}
::msgcat::mcset es {Element type} {Tipo de elemento}
::msgcat::mcset es Elements Elementos
::msgcat::mcset es {End time} {Tiempo final}
::msgcat::mcset es Energy Energía
::msgcat::mcset es Engineer Ingeniero
::msgcat::mcset es {Environment temperature} {Temperatura ambiente}
::msgcat::mcset es Eulerian Eulerian
::msgcat::mcset es {Expansion coeff} {Coeficiente de expansión}
::msgcat::mcset es Exponential Exponencial
::msgcat::mcset es {Extrapolation layers} {Capas de extrapolación}
::msgcat::mcset es Face Cara
::msgcat::mcset es {Face type} {Tipo de Cara}
::msgcat::mcset es False Falso
::msgcat::mcset es Fix Fijar
::msgcat::mcset es {Fix X velocity} {Fijar la velocidad X}
::msgcat::mcset es {Fix Y velocity} {Fijar la velocidad Y}
::msgcat::mcset es {Fix Z velocity} {Fijar la velocidad Z}
::msgcat::mcset es {Fix coordinates} {Coordenadas fijas}
::msgcat::mcset es {Fix pressure} {Pressión fija}
::msgcat::mcset es Fixed Fijo
::msgcat::mcset es Fixity Fijeza
::msgcat::mcset es Flag Flag
::msgcat::mcset es {Flag variable} {Variables Flag}
::msgcat::mcset es Flag-Variable Bandera-Variable
::msgcat::mcset es Fluid Fluido
::msgcat::mcset es {Fluid Approach} {Enfoque Fluid}
::msgcat::mcset es {Fluid Inlet} {Entrada de fluido}
::msgcat::mcset es {Fluid approach} {Enfoque Fluid}
::msgcat::mcset es {Fluid dynamics} {Dinámicas de fluidos}
::msgcat::mcset es {Fluid structure interaction (FSI)} {Interacción de fluido y estructura (FSI)}
::msgcat::mcset es {Fluid type} {Tipo de fluido}
::msgcat::mcset es Forces Forces
::msgcat::mcset es Fx Fx
::msgcat::mcset es {Fx Vector} {Vector Fx}
::msgcat::mcset es Fy Fy
::msgcat::mcset es {Fy Vector} {Vector Fy}
::msgcat::mcset es Fz Fz
::msgcat::mcset es {Fz Vector} {Vector Fz}
::msgcat::mcset es GMRES GMRES
::msgcat::mcset es {General application data} {General application data}
::msgcat::mcset es {GiD postprocess options} {Opciones postproceso GiD}
::msgcat::mcset es {Gravity value} Gravedad
::msgcat::mcset es HexPly_8551-7_IM7 HexPly_8551-7_IM7
::msgcat::mcset es {History graph} {Historia gráfica}
::msgcat::mcset es {History graph properties} {Historia propiedades del gráfico}
::msgcat::mcset es {History output on points} {Historia de salida en los puntos}
::msgcat::mcset es {History output on points properties} {Salida de Historia de las propiedades puntos}
::msgcat::mcset es ILU0 ILU0
::msgcat::mcset es {Inertia Ix} {La inercia Ix}
::msgcat::mcset es {Inertia Iy} {La inercia Iy}
::msgcat::mcset es {Is boundary} {Es límites}
::msgcat::mcset es {Is fluid} {Es fluido}
::msgcat::mcset es Is-Boundary Es-Boundary
::msgcat::mcset es Is-Fluid Es-Fluid
::msgcat::mcset es Is-Slip Es-Slip
::msgcat::mcset es {Is-Slip conditional data} {Es-Slip datos condicionales}
::msgcat::mcset es {Is-boundary conditional data} {Datos condicional es-frontera}
::msgcat::mcset es Isotropic Isotrópic
::msgcat::mcset es {Isotropic + Kinematic} {Isotrípic + Cinemático}
::msgcat::mcset es Iterative Iterativo
::msgcat::mcset es {Iterative solver type options} {Iterativo opciones de tipo de solucionador}
::msgcat::mcset es K11 K11
::msgcat::mcset es K22 K22
::msgcat::mcset es K33 K33
::msgcat::mcset es {Krylov space dimension} {Krylov dimensión espacial}
::msgcat::mcset es {Laplacian correction of pressure} {Corrección de Laplace de la presión}
::msgcat::mcset es {Laplacian form} {Forma Laplaciano}
::msgcat::mcset es {Level set distance data} {Datos de distancia de ajuste de nivel}
::msgcat::mcset es Linear Lineal
::msgcat::mcset es {Linear Darcy coefficient} {Coeficiente de Darcy Lineal}
::msgcat::mcset es MPI MPI
::msgcat::mcset es Material Material
::msgcat::mcset es {Max X} {Max X}
::msgcat::mcset es {Max Y} {Max Y}
::msgcat::mcset es {Max Z} {Max Z}
::msgcat::mcset es {Max time variation} {Variación en el tiempo máximo de}
::msgcat::mcset es {Max ?t} {Max? T}
::msgcat::mcset es Membrane Membrana
::msgcat::mcset es {Membrane element} {Elemento de membrana}
::msgcat::mcset es {Membrane element type} {Tipo de elemento de membrana}
::msgcat::mcset es Membranes Membrana
::msgcat::mcset es Metal Meta
::msgcat::mcset es {Min X} {Min X}
::msgcat::mcset es {Min Y} {Min Y}
::msgcat::mcset es Mohr-Coulomb Mohr-Coulomb
::msgcat::mcset es Multiples Multiples
::msgcat::mcset es Mx Mx
::msgcat::mcset es {Mx Vector} {Mx Vector}
::msgcat::mcset es My My
::msgcat::mcset es {My Vector} {My Vector}
::msgcat::mcset es Mz Mz
::msgcat::mcset es {Mz Vector} {Mz Vector}
::msgcat::mcset es {New group} {Nuevo grupo}
::msgcat::mcset es No No
::msgcat::mcset es Off Oculto
::msgcat::mcset es Z Z
::msgcat::mcset es {Z Vector} {Z Vector}
::msgcat::mcset es {Z active} {Z active}
::msgcat::mcset es {Z coordinate} {Z coordinate}
::msgcat::mcset es {Z fix} {Z fix}
::msgcat::mcset es {alfa 11} {alfa 11}
::msgcat::mcset es {alfa 22} {alfa 22}
::msgcat::mcset es {alfa 33} {alfa 33}
