// ==============================================================================
//  KratosShapeOptimizationApplication
//
//  License:         BSD License
//                   license: ShapeOptimizationApplication/license.txt
//
//  Main authors:    Baumgaertner Daniel, https://github.com/dbaumgaertner
//
// ==============================================================================

#if defined(KRATOS_PYTHON)

// ------------------------------------------------------------------------------
// System includes
// ------------------------------------------------------------------------------
#include <pybind11/pybind11.h>

// ------------------------------------------------------------------------------
// External includes
// ------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// Project includes
// ------------------------------------------------------------------------------
#include "includes/define_python.h"
#include "shape_optimization_application.h"
#include "custom_python/add_custom_utilities_to_python.h"

// ==============================================================================

namespace Kratos {
namespace Python {

PYBIND11_MODULE(KratosShapeOptimizationApplication, m)
{
    namespace py = pybind11;

    py::class_<KratosShapeOptimizationApplication,
        KratosShapeOptimizationApplication::Pointer,
        KratosApplication >(m, "KratosShapeOptimizationApplication")
        .def(py::init<>())
        ;

    AddCustomUtilitiesToPython(m);

    //registering variables in python

    // Geometry variables
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, NORMALIZED_SURFACE_NORMAL);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, INITIAL_NORMALIZED_SURFACE_NORMAL);

    // Optimization variables
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DF1DX);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DF1DX_MAPPED);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC1DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC2DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC3DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC4DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC5DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC6DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC7DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC8DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC9DX);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC1DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC2DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC3DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC4DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC5DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC6DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC7DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC8DX_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC9DX_MAPPED);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, SEARCH_DIRECTION);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INV_HESSIAN);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, CORRECTION);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, PROJECTION);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, CONTROL_POINT_UPDATE);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, CONTROL_POINT_CHANGE);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, SHAPE_UPDATE);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, SHAPE_CHANGE);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, MESH_CHANGE);

    // For thickness
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_SENSITIVITY);

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DF1DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DF1DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DF1DT_ACTIVE);

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, LB_values);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, LB_buffer_coeff);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DLBDT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DLBDT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, UB_values);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, UB_buffer_coeff);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DLBDT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DLBDT_MAPPED);

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC1DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC1DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC1DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC2DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC2DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC2DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC3DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC3DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC3DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC4DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC4DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC4DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC5DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC5DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC5DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC6DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC6DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC6DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC7DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC7DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC7DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC8DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC8DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC8DT_ACTIVE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC9DT);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC9DT_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DC9DT_ACTIVE);

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, INV_HESSIAN_THICKNESS);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_SEARCH_DIRECTION);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_CORRECTION);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_PROJECTION);

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_CONTROL);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_CONTROL_UPDATE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_CONTROL_CHANGE);

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_ELEMENTAL);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_ELEMENTAL_INITIAL);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_UPDATE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_CHANGE);

    // for thickness optimization with change as design variable
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_INITIAL);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_CHANGE_CONTROL);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, THICKNESS_CHANGE_CONTROL_PROJECTED);

    // For edge damping
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DAMPING_FACTOR);

    // For thickness damping
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DAMPING_FACTOR_T);

    // For mapping
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MAPPING_ID);

    // For adaptive filter
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, VERTEX_MORPHING_RADIUS);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, VERTEX_MORPHING_RADIUS_RAW);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, GAUSSIAN_CURVATURE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MAX_NEIGHBOUR_DISTANCE);

    // Bead optimization
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ALPHA);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ALPHA_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DF1DALPHA);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DF1DALPHA_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DPDALPHA);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DPDALPHA_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DLDALPHA);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, BEAD_DIRECTION);

    // For shape fraction optimization
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DP1DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DPF1DX);

    // For auxiliary operations
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SCALAR_VARIABLE);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SCALAR_VARIABLE_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, VECTOR_VARIABLE);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, VECTOR_VARIABLE_MAPPED);

    // For in plane mapping operations
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, BACKGROUND_COORDINATE);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, BACKGROUND_NORMAL);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, OUT_OF_PLANE_DELTA);

    // For sensitivity heatmap
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DF1DX);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, HEATMAP_DF1DALPHA);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC1DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC2DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC3DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC4DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC5DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC6DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC7DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC8DX);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, HEATMAP_DC9DX);

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, HEATMAP_MAX);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, HEATMAP_L2);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DF1DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DF1DALPHA_WEIGHTED);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC1DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC2DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC3DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC4DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC5DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC6DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC7DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC8DX_WEIGHTED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC9DX_WEIGHTED);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DF1DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DF1DALPHA_WEIGHTED_MAPPED);

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC1DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC2DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC3DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC4DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC5DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC6DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC7DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC8DX_WEIGHTED_MAPPED);
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m, DC9DX_WEIGHTED_MAPPED);

  }

}  // namespace Python.
}  // namespace Kratos.

#endif // KRATOS_PYTHON defined
