#include "lagrangian_mpm_application_variables.h"

namespace Kratos
{
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( GAUSS_DISPLACEMENT )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( GAUSS_POINT_COORDINATES )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MP_VOLUME_ACCELERATION )
KRATOS_CREATE_VARIABLE(  double, GAUSS_AREA )
KRATOS_CREATE_VARIABLE(  double, EFFECTIVE_RADIUS )
KRATOS_CREATE_VARIABLE(  Vector, SHAPE_FUNCTIONS )
KRATOS_CREATE_VARIABLE(  Matrix, SHAPE_FUNCTIONS_DERIVATIVES )

KRATOS_CREATE_VARIABLE(double, INCREMENTAL_DISP )

KRATOS_CREATE_VARIABLE(  double, NODAL_RADIUS )
KRATOS_CREATE_VARIABLE(  double, NODAL_SPACING )
KRATOS_CREATE_VARIABLE( Matrix, NODAL_STRESS )
KRATOS_CREATE_VARIABLE( Matrix, NODAL_STRAIN )
//KRATOS_CREATE_VARIABLE( double,NODAL_AREA)

KRATOS_CREATE_VARIABLE( int, CENTER_ID )
//KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( LAGRANGE_DISPLACEMENT )

}
