#include "lagrangian_mpm_application_variables.h"

namespace Kratos
{
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( GAUSS_POINT_COORDINATES )
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( MP_VOLUME_ACCELERATION )
KRATOS_CREATE_VARIABLE(  double, GAUSS_AREA )
KRATOS_CREATE_VARIABLE(  double, EFFECTIVE_RADIUS )
KRATOS_CREATE_VARIABLE(  Vector, SHAPE_FUNCTIONS )
KRATOS_CREATE_VARIABLE(  Matrix, SHAPE_FUNCTIONS_DERIVATIVES )

}
