FROM centos:centos7

USER root

ENV HOME /root

#RUN python --version
RUN yum -y --quiet install wget git cmake gcc-c++ unzip python-pip make gcc-gfortran zlib-devel bzip2-devel openssl-devel samba-client openmpi-devel hdf5-openmpi-devel boost-devel


# compiling python3.5.4 to be compatible with HW
RUN cd /usr/src
RUN wget https://www.python.org/ftp/python/3.5.4/Python-3.5.4.tgz
RUN tar xzf Python-3.5.4.tgz -C /usr/src
RUN ls /usr/src/Python-3.5.4
RUN sh /usr/src/Python-3.5.4/configure --enable-optimizations --with-lto --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
RUN make altinstall
RUN rm Python-3.5.4.tgz
RUN python3.5 -m pip install 'cx_Freeze==6.1'

# Setting the needed environment variables for being able to run/compile
ENV PYTHON_EXECUTABLE /usr/local/bin/python3.5
# ENV  AMS_EXTERNAL_LIBRARIES_INSTALL_PATH /usr/local/

# Installing cmake3
RUN wget https://cmake.org/files/v3.17/cmake-3.17.3.tar.gz &&  tar zxvf cmake-3.* && cd cmake-3.* \
    && ./bootstrap --prefix=/usr/local && gmake  -j$(nproc) && make install
RUN rm cmake-3* -rf

# COPY external_libraries /external_libraries
# RUN source /etc/profile.d/modules.sh && module load mpi/openmpi-x86_64 \
#     && cd /external_libraries && export AMS_EXTERNAL_LIBRARIES_INSTALL_PATH=/usr/local && sh  build_external_libraries.sh

# Converting the library links to copy of the file
# RUN cd /usr/local/lib && mkdir /tmp/lib && cp -L *.so* /tmp/lib/ && rm *.so* -f && yes | cp /tmp/lib/* .

CMD [ "/bin/bash" ]

WORKDIR $HOME

#In case of dns problem please check https://forums.centos.org/viewtopic.php?t=74270P
# For build please run the following command from the DockerFile folder
# docker build ../../../ --file DockerFile --tag ams/ams-centos7-python35-build
# For python compilation: https://www.workaround.cz/howto-compile-install-latest-python-37-38-39-centos-7-8/
