- test the GetSubSolver
- test access to the model => should be redirected to the subsolvers, the coupled solvers should not have Models
- test when an existing Model is passed to the CoSimAnalysis => # MultiStage