#include "adjoint_fluid_application_variables.h"

namespace Kratos
{
// Create variables
// Moved to Kratos Core for trilinos_application
//KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VELOCITY )
//KRATOS_CREATE_VARIABLE(double, ADJOINT_PRESSURE )
//KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( PRIMAL_VELOCITY )
//KRATOS_CREATE_VARIABLE(double, PRIMAL_PRESSURE )
//KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( SHAPE_SENSITIVITY )
//KRATOS_CREATE_VARIABLE(double, NORMAL_SENSITIVITY )
}
