"MainRestart"
"BaseClass"
"Size"
1
"Variable Name"
"AMBIENT_TEMPERATURE"
"Data"
250
"BaseClass"
"IsDefined"
0
"Flags"
0
"Name"
"MainRestart"
"Buffer Size"
1
1
0x1849d70
"ProcessInfo"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
"Is Time Step"
1
"Solution Step Index"
0
0
0
"Tables"
"size"
1
"Key"
1
1
0x17066a0
"Data"
"size"
3
"Argument"
200
"Column"
2e-06
"Argument"
300
"Column"
3e-06
"Argument"
400
"Column"
4e-06
"Sorted Part Size"
1
"Max Buffer Size"
100
1
0x170bd40
"Variables List"
"Size"
2
"Variable Name"
"DISPLACEMENT"
"Variable Name"
"VISCOSITY"
"Meshes"
"size"
1
1
0x1866440
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
1
0x1867410
"Nodes"
"size"
6
1
0x7ff118001600
"E"
"BaseClass"
"BaseClass"
"BaseClass"
"E"
16
"E"
0
"E"
0
"BaseClass"
"Id"
1
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x7ff118001698
"Solution Steps Nodal Data"
1
0x170bd40
"QueueSize"
1
"QueueIndex"
0
"Data"
"E"
0.1
"E"
0
"E"
0
"Data"
0.01
"Initial Position"
"BaseClass"
"BaseClass"
"E"
16
"E"
0
"E"
0
"Data"
"size"
3
1
0x1844990
"E"
"BaseClass"
"Id"
1
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001698
"Variable"
"DISPLACEMENT_X"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x1707690
"E"
"BaseClass"
"Id"
1
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001698
"Variable"
"DISPLACEMENT_Y"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x18666c0
"E"
"BaseClass"
"Id"
1
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001698
"Variable"
"DISPLACEMENT_Z"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
"Sorted Part Size"
3
"Max Buffer Size"
1
1
0x7ff118001990
"E"
"BaseClass"
"BaseClass"
"BaseClass"
"E"
16
"E"
0.4
"E"
0
"BaseClass"
"Id"
2
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x7ff118001a28
"Solution Steps Nodal Data"
1
0x170bd40
"QueueSize"
1
"QueueIndex"
0
"Data"
"E"
0.2
"E"
0
"E"
0
"Data"
0.01
"Initial Position"
"BaseClass"
"BaseClass"
"E"
16
"E"
0.4
"E"
0
"Data"
"size"
3
1
0x17805e0
"E"
"BaseClass"
"Id"
2
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001a28
"Variable"
"DISPLACEMENT_X"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x1708500
"E"
"BaseClass"
"Id"
2
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001a28
"Variable"
"DISPLACEMENT_Y"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x18633a0
"E"
"BaseClass"
"Id"
2
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001a28
"Variable"
"DISPLACEMENT_Z"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
"Sorted Part Size"
3
"Max Buffer Size"
1
1
0x7ff118001730
"E"
"BaseClass"
"BaseClass"
"BaseClass"
"E"
15.6
"E"
0
"E"
0
"BaseClass"
"Id"
3
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x7ff1180017c8
"Solution Steps Nodal Data"
1
0x170bd40
"QueueSize"
1
"QueueIndex"
0
"Data"
"E"
0
"E"
0
"E"
0
"Data"
0
"Initial Position"
"BaseClass"
"BaseClass"
"E"
15.6
"E"
0
"E"
0
"Data"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x7ff1180012c0
"E"
"BaseClass"
"BaseClass"
"BaseClass"
"E"
0
"E"
7.2
"E"
0
"BaseClass"
"Id"
972
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x7ff118001358
"Solution Steps Nodal Data"
1
0x170bd40
"QueueSize"
1
"QueueIndex"
0
"Data"
"E"
0
"E"
0
"E"
0
"Data"
0
"Initial Position"
"BaseClass"
"BaseClass"
"E"
0
"E"
7.2
"E"
0
"Data"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x7ff118001b20
"E"
"BaseClass"
"BaseClass"
"BaseClass"
"E"
0
"E"
7.6
"E"
0
"BaseClass"
"Id"
973
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x7ff118001bb8
"Solution Steps Nodal Data"
1
0x170bd40
"QueueSize"
1
"QueueIndex"
0
"Data"
"E"
0
"E"
0.000973
"E"
0
"Data"
0.01
"Initial Position"
"BaseClass"
"BaseClass"
"E"
0
"E"
7.6
"E"
0
"Data"
"size"
3
1
0x1844280
"E"
"BaseClass"
"Id"
973
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001bb8
"Variable"
"DISPLACEMENT_X"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x1845410
"E"
"BaseClass"
"Id"
973
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001bb8
"Variable"
"DISPLACEMENT_Y"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x1621430
"E"
"BaseClass"
"Id"
973
"Is Fixed"
1
"Equation Id"
0
1
0x7ff118001bb8
"Variable"
"DISPLACEMENT_Z"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
"Sorted Part Size"
3
"Max Buffer Size"
1
1
0x7ff118001160
"E"
"BaseClass"
"BaseClass"
"BaseClass"
"E"
0
"E"
8
"E"
0
"BaseClass"
"Id"
974
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x7ff1180011f8
"Solution Steps Nodal Data"
1
0x170bd40
"QueueSize"
1
"QueueIndex"
0
"Data"
"E"
0
"E"
0.000974
"E"
0
"Data"
0.01
"Initial Position"
"BaseClass"
"BaseClass"
"E"
0
"E"
8
"E"
0
"Data"
"size"
3
1
0x1723060
"E"
"BaseClass"
"Id"
974
"Is Fixed"
1
"Equation Id"
0
1
0x7ff1180011f8
"Variable"
"DISPLACEMENT_X"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x184b6e0
"E"
"BaseClass"
"Id"
974
"Is Fixed"
1
"Equation Id"
0
1
0x7ff1180011f8
"Variable"
"DISPLACEMENT_Y"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
1
0x164f680
"E"
"BaseClass"
"Id"
974
"Is Fixed"
1
"Equation Id"
0
1
0x7ff1180011f8
"Variable"
"DISPLACEMENT_Z"
"Reaction"
"NONE"
"Variable Type"
1
"Reaction Type"
0
"Sorted Part Size"
3
"Max Buffer Size"
1
"Sorted Part Size"
6
"Max Buffer Size"
1
1
0x1868c80
"Properties"
"size"
1
1
0x1705e60
"E"
"BaseClass"
"Id"
1
"Data"
"Size"
4
"Variable Name"
"DENSITY"
"Data"
3.4e-05
"Variable Name"
"THICKNESS"
"Data"
19.5
"Variable Name"
"VOLUME_ACCELERATION"
"Data"
"E"
0
"E"
0
"E"
9.8
"Variable Name"
"LOCAL_INERTIA_TENSOR"
"Data"
3
3
0
0.27
0.27
0.087
0
0.27
0.075
0.23
0
"Tables"
"size"
1
"E"
"First"
4496830760049
"Second"
"size"
3
"Argument"
200
"Column"
2e-06
"Argument"
300
"Column"
3e-06
"Argument"
400
"Column"
4e-06
"Sorted Part Size"
1
"Max Buffer Size"
1
1
0x1867470
"Elements"
"size"
4
1
0x1849f00
"E"
"BaseClass"
"BaseClass"
"Id"
1
2
0x18501a0
"Triangle2D3"
"Geometry"
"BaseClass"
"BaseClass"
"size"
3
1
0x7ff118001600
1
0x7ff118001990
1
0x7ff118001730
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
1
0x1660040
"E"
"BaseClass"
"BaseClass"
"Id"
2
2
0x184b3c0
"Triangle2D3"
"Geometry"
"BaseClass"
"BaseClass"
"size"
3
1
0x7ff118001990
1
0x7ff118001730
1
0x7ff1180012c0
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
1
0x170a420
"E"
"BaseClass"
"BaseClass"
"Id"
3
2
0x1709920
"Triangle2D3"
"Geometry"
"BaseClass"
"BaseClass"
"size"
3
1
0x7ff118001730
1
0x7ff1180012c0
1
0x7ff118001b20
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
1
0x16cf770
"E"
"BaseClass"
"BaseClass"
"Id"
1796
2
0x18446d0
"Triangle2D3"
"Geometry"
"BaseClass"
"BaseClass"
"size"
3
1
0x7ff1180012c0
1
0x7ff118001b20
1
0x7ff118001160
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
"Sorted Part Size"
4
"Max Buffer Size"
1
1
0x1705f30
"Conditions"
"size"
5
1
0x161fe30
"E"
"BaseClass"
"BaseClass"
"Id"
1
2
0x170adf0
"Line2D2"
"Geometry"
"BaseClass"
"BaseClass"
"size"
2
1
0x7ff118001600
1
0x7ff118001990
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
1
0x17047e0
"E"
"BaseClass"
"BaseClass"
"Id"
1800
2
0x175def0
"Line2D2"
"Geometry"
"BaseClass"
"BaseClass"
"size"
2
1
0x7ff118001990
1
0x7ff118001730
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
1
0x1708410
"E"
"BaseClass"
"BaseClass"
"Id"
1801
2
0x1760200
"Line2D2"
"Geometry"
"BaseClass"
"BaseClass"
"size"
2
1
0x7ff118001730
1
0x7ff1180012c0
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
1
0x1844d70
"E"
"BaseClass"
"BaseClass"
"Id"
1947
2
0x1706740
"Line2D2"
"Geometry"
"BaseClass"
"BaseClass"
"size"
2
1
0x7ff1180012c0
1
0x7ff118001b20
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
1
0x16249d0
"E"
"BaseClass"
"BaseClass"
"Id"
1948
2
0x18634a0
"Line2D2"
"Geometry"
"BaseClass"
"BaseClass"
"size"
2
1
0x7ff118001b20
1
0x7ff118001160
"BaseClass"
"IsDefined"
0
"Flags"
0
"Data"
"Size"
0
1
0x1705e60
"Sorted Part Size"
5
"Max Buffer Size"
1
"SubModelParts"
"size"
2
1
0x16cbc60
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
"Name"
"Outlet"
"Buffer Size"
1
1
0x1849d70
"Tables"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
100
1
0x170bd40
"Meshes"
"size"
1
1
0x170a810
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
1
0x170a670
"Nodes"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x170a6d0
"Properties"
"size"
1
1
0x1705e60
"Sorted Part Size"
1
"Max Buffer Size"
1
1
0x170a730
"Elements"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x170a790
"Conditions"
"size"
1
1
0x16249d0
"Sorted Part Size"
1
"Max Buffer Size"
1
"SubModelParts"
"size"
0
1
0x1707730
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
"Name"
"Inlets"
"Buffer Size"
1
1
0x1849d70
"Tables"
"size"
1
"Key"
1
1
0x17066a0
"Sorted Part Size"
1
"Max Buffer Size"
100
1
0x170bd40
"Meshes"
"size"
1
1
0x18448a0
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
1
0x170b5a0
"Nodes"
"size"
3
1
0x7ff118001600
1
0x7ff118001990
1
0x7ff118001730
"Sorted Part Size"
3
"Max Buffer Size"
1
1
0x17063a0
"Properties"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x1706400
"Elements"
"size"
1
1
0x1849f00
"Sorted Part Size"
1
"Max Buffer Size"
1
1
0x170beb0
"Conditions"
"size"
3
1
0x161fe30
1
0x17047e0
1
0x1708410
"Sorted Part Size"
3
"Max Buffer Size"
1
"SubModelParts"
"size"
2
1
0x17080d0
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
"Name"
"Inlet2"
"Buffer Size"
1
1
0x1849d70
"Tables"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
100
1
0x170bd40
"Meshes"
"size"
1
1
0x1775770
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
1
0x1851ee0
"Nodes"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x1851f40
"Properties"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x1775690
"Elements"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x17756f0
"Conditions"
"size"
2
1
0x17047e0
1
0x1708410
"Sorted Part Size"
2
"Max Buffer Size"
1
"SubModelParts"
"size"
0
1
0x1707d30
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
"Name"
"Inlet1"
"Buffer Size"
1
1
0x1849d70
"Tables"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
100
1
0x170bd40
"Meshes"
"size"
1
1
0x18674d0
"E"
"BaseClass"
"Size"
0
"BaseClass"
"IsDefined"
0
"Flags"
0
1
0x1848710
"Nodes"
"size"
2
1
0x7ff118001600
1
0x7ff118001730
"Sorted Part Size"
2
"Max Buffer Size"
1
1
0x1709af0
"Properties"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x170a100
"Elements"
"size"
0
"Sorted Part Size"
0
"Max Buffer Size"
1
1
0x170a160
"Conditions"
"size"
2
1
0x161fe30
1
0x17047e0
"Sorted Part Size"
2
"Max Buffer Size"
1
"SubModelParts"
"size"
0
