name: Build Docker Images with Kratos

on:
  push:
    branches:
      - 'master'
    paths:
    - 'scripts/docker_files/docker_file_kratos_ubuntu_20_04/DockerFile'
    - '.github/workflows/build_docker_images_with_kratos.yml'

  schedule:
    - cron: '0 0 * * *' # update it every night

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_ci_ubuntu_20_04/DockerFile --tag kratosmultiphysics/kratos-image-ubuntu-20-04
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      run: docker push kratosmultiphysics/kratos-image-ubuntu-20-04
