name: Build Docker Images with compilers

on: push

jobs:
  build-docker-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_compilers_ubuntu_20_04/DockerFile --tag kratosmultiphysics/kratos-image-compilers-ubuntu-20-04