#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es {Error when preparing data for analysis (%s)} {Error preparando datos para análisis (%s)}
::msgcat::mcset es {General application data} {Datos generales aplicación}
::msgcat::mcset es {Project information} {Información del proyecto}
::msgcat::mcset es {Company name} {Nombre de comañia}
::msgcat::mcset es {Project name} {Nombre del proyecto}
::msgcat::mcset es {Project number} {Número del proyecto}
::msgcat::mcset es {Model name} {Nombre del modelo}
::msgcat::mcset es {Model description} {Descripción del modelo}
::msgcat::mcset es {Revision number} {Número de revisión}
::msgcat::mcset es Engineer Ingeniero
::msgcat::mcset es Supervisor Supervisor
::msgcat::mcset es {Project configuration} {Configuración del proyecto}
::msgcat::mcset es {Kratos path} {Ruta Kratos}
::msgcat::mcset es Domain Dominio
::msgcat::mcset es Helptext {Texto ayuda}
::msgcat::mcset es {Spatial dimension} {Dimensión espacial}
::msgcat::mcset es 3D 3D
::msgcat::mcset es 2D 2D
::msgcat::mcset es {Spatial Dimension} {Dimensión Espacial}
::msgcat::mcset es Yes Sí
::msgcat::mcset es No No
::msgcat::mcset es {Application types} {Tipos de aplicación}
::msgcat::mcset es {Structural analysis} {Análisis estructural}
::msgcat::mcset es Fluid Fluido
::msgcat::mcset es {Fluid dynamics} {Dinámica de fluidos}
::msgcat::mcset es PFEM PFEM
::msgcat::mcset es {Fluid structure interaction (FSI)} {Interacción de fluido y estructura (FSI)}
::msgcat::mcset es {Convection diffusion} {Convección difusión}
::msgcat::mcset es DEM DEM
::msgcat::mcset es {Structural simulation} {Simulación estructural}
::msgcat::mcset es {Analysis type} {Tipo de análisis}
::msgcat::mcset es {Analysis Data} {Analisis de datos}
::msgcat::mcset es {Solution type} {Tipo de solución}
::msgcat::mcset es Static Estático
::msgcat::mcset es Dynamic Dinámico
::msgcat::mcset es Linear Lineal
::msgcat::mcset es Non-Linear {No lineal}
::msgcat::mcset es {Analysis Type} {Tipo de análisis}
::msgcat::mcset es {Solution strategy} {Estrategia de solución}
::msgcat::mcset es {Solution Strategy} {Estrategia de Solución}
::msgcat::mcset es {Parallel type} {Tipo de paralelismo}
::msgcat::mcset es OpenMP OpenMP
::msgcat::mcset es MPI MPI
::msgcat::mcset es {Number of processors} {Número de procesadores}
::msgcat::mcset es {Number of threads} {Número de hilos}
::msgcat::mcset es {Linear solver} {Solver lineal}
::msgcat::mcset es {Linear solver type} {Tipo de solver lineal}
::msgcat::mcset es {Solver tolerance} {Tolerancia del solver}
::msgcat::mcset es None Ninguno
::msgcat::mcset es Diagonal Diagonal
::msgcat::mcset es {Time parameters} {Parámetros de tiempo}
::msgcat::mcset es {Start time} {Tiempo de inicio}
::msgcat::mcset es {Time step} {Paso de tiempo}
::msgcat::mcset es {Total time} {Tiempo total}
::msgcat::mcset es {Number of Steps} {Número de pasos}
::msgcat::mcset es {Solution method} {Método de solución}
::msgcat::mcset es Displacement Desplazamiento
::msgcat::mcset es {Residual convergence tolerance} {Tolerancia de convergencia Residual}
::msgcat::mcset es {Residual absolute tolerance} {Tolerancia absoluta Residual}
::msgcat::mcset es {Displacement convergence tolerance} {Tolerancia de convergencia del desplazamiento}
::msgcat::mcset es {Displacement absolute tolerance} {Desplazamiento de tolerancia absoluto}
::msgcat::mcset es {Maximum iterations} {Iteraciones máximas}
::msgcat::mcset es Properties Propiedades
::msgcat::mcset es {Add a new Property} {Añadir nueva propiedad}
::msgcat::mcset es Elements Elementos
::msgcat::mcset es {Solid Element} {Elemento sólido}
::msgcat::mcset es {Beam Element type} {Tipo de elemento de viga}
::msgcat::mcset es {Crisfield truss element} {Elemento barra Crisfield}
::msgcat::mcset es {Shell isotropic} {Lámina isotrópica}
::msgcat::mcset es ShellAnisotropic {Lámina anisotrópica}
::msgcat::mcset es {Total Lagrangian} {Total de Lagrange}
::msgcat::mcset es {Membrane element type} {Tipo de elemento de membrana}
::msgcat::mcset es Loads Cargas
::msgcat::mcset es {Self weight} {Peso propio}
::msgcat::mcset es {Gravity (Body Force)} {Gravedad (Fuerza Másica)}
::msgcat::mcset es Load Cargar
::msgcat::mcset es {External Load} {Carga Externa}
::msgcat::mcset es {Point Load} {Carga puntual}
::msgcat::mcset es {Define Surface Load} {Defina la Carga de Superficie}
::msgcat::mcset es {Pressure Load} {Carga de Presión}
::msgcat::mcset es {Define Surface Pressure} {Defina la presión de superficie}
::msgcat::mcset es Incremental Incremental
::msgcat::mcset es {Incremental Loads} {Cargas Incrementales}
::msgcat::mcset es {Boundary conditions} {Condiciones de contorno}
::msgcat::mcset es {Boundary Conditions} {Condiciones contorno}
::msgcat::mcset es Displacements Desplazamientos
::msgcat::mcset es Rotations Rotaciones
::msgcat::mcset es Results Resultados
::msgcat::mcset es {Output delta time} {Salida incremento tiempo}
::msgcat::mcset es {On nodes} {En los nodos}
::msgcat::mcset es Velocities Velocidades
::msgcat::mcset es Accelerations Aceleraciones
::msgcat::mcset es Reactions Reacciones
::msgcat::mcset es {On gauss points} {En los puntos de gauss}
::msgcat::mcset es {Green Lagrange strain tensor} {Tensor tensión Green Lagrange}
::msgcat::mcset es {Cauchy stress tensor} {Tensor de tensiones de Cauchy}
::msgcat::mcset es {Von Mises Criterion} {Criterio de Von Mises}
::msgcat::mcset es Options Opciones
::msgcat::mcset es {GiD postprocess options} {Opciones postproceso GiD}
::msgcat::mcset es {Result format} {Formato de resultados}
::msgcat::mcset es Ascii Ascii
::msgcat::mcset es Binary Binario
::msgcat::mcset es {GiD result file format} {Formato de archivo de resultados GiD}
::msgcat::mcset es {Write deformed mesh} {Escribir la malla deformada}
::msgcat::mcset es {Write the GiD deformed or undeformed mesh} {Escribir la malla de GiD deformada o indeformada}
::msgcat::mcset es {Write conditions} {Escribir condiciones}
::msgcat::mcset es {Write the conditions or only element to the GiD result file} {Escribir las condiciones o solo elementos en el fichero de resultados de GiD}
::msgcat::mcset es {Write particles} {Escribir las partículas}
::msgcat::mcset es {Write the particles or only element to the GiD result file} {Escribir las partículas o sólo elemento en el archivo de resultados de GiD}
::msgcat::mcset es {Result file} {Archivo de resultados}
::msgcat::mcset es Single Único
::msgcat::mcset es Multiples Múltiples
::msgcat::mcset es {Write one GiD result file or multiple files} {Escribir uno o multiples ficheros GiD de resultados}
::msgcat::mcset es {Analysis data} {Analisis de datos}
::msgcat::mcset es {Fluid type} {Tipo de fluido}
::msgcat::mcset es Incompressible Incompresible
::msgcat::mcset es Eulerian Euleriano
::msgcat::mcset es {Fluid approach} {Enfoque Fluido}
::msgcat::mcset es {Free surface} {Superficie libre}
::msgcat::mcset es {Solver type} {Tipo de solver}
::msgcat::mcset es {Fractional step} {Paso fraccional}
::msgcat::mcset es Monolithic Monolítico
::msgcat::mcset es SolverType SolverType
::msgcat::mcset es {Turbulence model} {Modelo de turbulencia}
::msgcat::mcset es Off Apagado
::msgcat::mcset es {Select the active tubulence model} {Seleccione el modelo tubulence activo}
::msgcat::mcset es {Turbulent viscosity} {Viscosidad turbulenta}
::msgcat::mcset es {Define the turbulent viscosity value} {Definir el valor de la viscosidad turbulenta}
::msgcat::mcset es {Select the group identifier} {Seleccione el identificador de grupo}
::msgcat::mcset es Parallelization Paralelización
::msgcat::mcset es {Solver types} {Tipos de solver}
::msgcat::mcset es Solver Solver
::msgcat::mcset es {Iterative solver type options} {Opciones de tipo de solucionador iterativo}
::msgcat::mcset es {Monolithic solver maximum iteration numbers} {Número máximo de iteraciones solucionador monolítico}
::msgcat::mcset es {Mixed UP Krylov space dimension} {Mixed Up Krylov dimensión espacial}
::msgcat::mcset es {Conjugate gradient} {Gradientes conjugados}
::msgcat::mcset es {Pressure solver} {Solver para la presión}
::msgcat::mcset es {Pressure preconditioner type} {Tipo de precondicionador de la presión}
::msgcat::mcset es Advanced Avanzado
::msgcat::mcset es {Advanced Solver Parameters} {Parámetros del solver avanzados}
::msgcat::mcset es {Predictor corrector} {Predictor corrector}
::msgcat::mcset es True Verdadero
::msgcat::mcset es False Falso
::msgcat::mcset es {Relative velocity tolerance} {Tolerancia velocidad relativa}
::msgcat::mcset es {Absolute velocity tolerance} {Velocidad de tolerancia absoluta}
::msgcat::mcset es {Maximum velocity iterations} {Iteraciones máximas para la velocidad}
::msgcat::mcset es {Relative pressure tolerance} {Tolerancia a la presión relativa}
::msgcat::mcset es {Absolute pressure tolerance} {Presión de tolerancia absoluta}
::msgcat::mcset es {Maximum pressure iterations} {Iteraciones máximas para la presión}
::msgcat::mcset es Continuous Continuo
::msgcat::mcset es Discrete Discreto
::msgcat::mcset es {Redistance frequency} {Frecuencia Redistancia}
::msgcat::mcset es {Extrapolation layers} {Capas extrapolación}
::msgcat::mcset es {Stabilized dt pressure factor} {Factor de presión dt estabilizada}
::msgcat::mcset es {Stabilized convection factor} {Factor de convección estabilizada}
::msgcat::mcset es {Wall law value} {Valor ley pared}
::msgcat::mcset es {Safety factor} {Factor de seguridad}
::msgcat::mcset es {Number of initial steps} {Número de pasos iniciales}
::msgcat::mcset es {Use Laplacian correction of pressure} {Utilizar corrección de Laplace de la presión}
::msgcat::mcset es {Bounding Box} {Caja delimitadora}
::msgcat::mcset es {Max X} {Max X}
::msgcat::mcset es {Max Y} {Max Y}
::msgcat::mcset es {Max Z} {Max Z}
::msgcat::mcset es {Min X} {Min X}
::msgcat::mcset es {Min Y} {Min Y}
::msgcat::mcset es {Min Z} {Min Z}
::msgcat::mcset es {Body force} {Fuerza másica}
::msgcat::mcset es {Body forces} {Fuerzas cuerpo}
::msgcat::mcset es {Gravity value} Gravedad
::msgcat::mcset es Cx Cx
::msgcat::mcset es {X Vector} {Vector X}
::msgcat::mcset es Cy Cy
::msgcat::mcset es {Y Vector} {Vector Y}
::msgcat::mcset es Cz Cz
::msgcat::mcset es {Z Vector} {Vector Z}
::msgcat::mcset es {Porous zones} {Zonas porosas}
::msgcat::mcset es {Use Ergun equation} {Usar ecuación Ergun}
::msgcat::mcset es Zones Zonas
::msgcat::mcset es {Problem parameters} {Parámetros del problema}
::msgcat::mcset es {End time} {Tiempo final}
::msgcat::mcset es {Automatic delta time} {Incremento de tiempo automático}
::msgcat::mcset es Fixed Fijo
::msgcat::mcset es Automatic Automático
::msgcat::mcset es {Select the Delta time option to be used} {Seleccione la opción de incremento de tiempo a usar}
::msgcat::mcset es {Delta time} {Incremento de tiempo}
::msgcat::mcset es {Define the divergence cleareance step value} {Defina el valor del paso de reinicio de divergencia}
::msgcat::mcset es {Environment temperature} {Temperatura ambiente}
::msgcat::mcset es {Max Dt} {Paso de tiempo máximo}
::msgcat::mcset es {Max time variation} {Máx variación tiempo}
::msgcat::mcset es {Min Dt} {Paso de tiempo mínimo}
::msgcat::mcset es {Min time variation} {Mínima variación tiempo}
::msgcat::mcset es ASGS ASGS
::msgcat::mcset es {Select the fluid 2D element type} {Seleccione el tipo de elemento 2D fluido}
::msgcat::mcset es {Initial conditions} {Condiciones iniciales}
::msgcat::mcset es {Initial Conditions} {Condiciones iniciales}
::msgcat::mcset es {Initial velocity} {Velocidad inicial}
::msgcat::mcset es {Initial temperature} {Temperatura inicial}
::msgcat::mcset es {Initial pressure} {Presión inicial}
::msgcat::mcset es {Inlet velocity} {Velocidad de entrada}
::msgcat::mcset es {Prescribed velocity} {Velocidad prescrita}
::msgcat::mcset es {Outlet pressure} {Presión de salida}
::msgcat::mcset es Slip Deslizamiento
::msgcat::mcset es {Wall law} {Ley pared}
::msgcat::mcset es Distance Distancia
::msgcat::mcset es {Distance variable for the free surface using level set method} {Distancia variable de superficie libre utilizando el método 'level set'}
::msgcat::mcset es No-Slip No-Slip
::msgcat::mcset es {Define the flag variable properties} {Define las propiedades de la variable}
::msgcat::mcset es {Fixed Wall} {Pared fija}
::msgcat::mcset es {Fluid Inlet} {Entrada de fluido}
::msgcat::mcset es {Volume output} {Salida volúmen}
::msgcat::mcset es {Print in layer} {Imprimir en la capa}
::msgcat::mcset es Velocity Velocidad
::msgcat::mcset es Pressure Presión
::msgcat::mcset es Stresses Tensiones
::msgcat::mcset es {History output on points} {Historia salida en puntos}
::msgcat::mcset es {Cut plane postprocess options} {Opciones de plano de corte}
::msgcat::mcset es {Drag calculation} {Cálculo del rozamiento}
::msgcat::mcset es {Drag calculation properties} {Cálculo propiedades arrastre}
::msgcat::mcset es {Problem Parameters} {Parámetros del problema}
::msgcat::mcset es {Is fluid} {Es fluido}
::msgcat::mcset es {Is boundary} {Es contorno}
::msgcat::mcset es {Not available} {No disponible}
::msgcat::mcset es {Developing in process} {Proceso en desarrollo}
::msgcat::mcset es {Base variable type} {Tipo de variable base}
::msgcat::mcset es Temperature Temperatura
::msgcat::mcset es {Parallelization type} {Tipo de paralelismo}
::msgcat::mcset es {Prescribed temperature} {Temperatura prescrita}
::msgcat::mcset es {DEM application} {Aplicación DEM}
::msgcat::mcset es Wizards Wizards
::msgcat::mcset es {Compression Test} {Test de compresión}
::msgcat::mcset es {Cutting Test} {Test de cutting}
::msgcat::mcset es {Constitutive parameters} {Parámetros constitutivos}
::msgcat::mcset es {Material model} {Material del modelo}
::msgcat::mcset es Hertz Hertz
::msgcat::mcset es 1DPlasticity Plasticidad1D
::msgcat::mcset es {1D Plasticity} {Plasticidad 1D}
::msgcat::mcset es {Exponential Hardening} {Endurecimiento exponencial}
::msgcat::mcset es Elasticity Elasticidad
::msgcat::mcset es {1D Plasticity and damage} {Plasticidad y daño 1D}
::msgcat::mcset es LCS1 LCS1
::msgcat::mcset es LCS2 LCS2
::msgcat::mcset es LCS3 LCS3
::msgcat::mcset es YRC1 YRC1
::msgcat::mcset es YRC2 YRC2
::msgcat::mcset es YRC3 YRC3
::msgcat::mcset es {Plastic young modulus} {Módulo de Young plástico}
::msgcat::mcset es {Plastic young modulus ratio} {Ratio del Módulo de Young plástico}
::msgcat::mcset es {Plastic Yield Stress} {Tensión de Fluencia Plástica}
::msgcat::mcset es {Damage deformation factor} {Factor de deformación del daño}
::msgcat::mcset es {Exponential hardening} {Endurecimiento exponencial}
::msgcat::mcset es {Gamma 1} {Gamma 1}
::msgcat::mcset es {Gamma 2} {Gamma 2}
::msgcat::mcset es {Gamma 3} {Gamma 3}
::msgcat::mcset es {Max Deformation} {Deformación Máxima}
::msgcat::mcset es Damping Amortiguamiento
::msgcat::mcset es {Local contact damping} {Amortiguamiento local}
::msgcat::mcset es Normal Normal
::msgcat::mcset es Tangential Tangencial
::msgcat::mcset es Both Ambos
::msgcat::mcset es {Local damping factor} {Factor de amortiguamiento local}
::msgcat::mcset es {Global dynamics damping} {Amortiguamiento global dinámico}
::msgcat::mcset es {Global force reduction} {Reduccion de la fuerza global}
::msgcat::mcset es {Failure criteria} {Criterio de rotura}
::msgcat::mcset es {Tangential strength} {Resistencia tangencial}
::msgcat::mcset es {Normal tensile strength} {Resistencia a tracción }
::msgcat::mcset es {Internal friction angle} {Ángulo de fricción interna}
::msgcat::mcset es {Material test} {Test de material}
::msgcat::mcset es {Test type} {Tipo de test}
::msgcat::mcset es UCS UCS
::msgcat::mcset es Triaxial Triaxial
::msgcat::mcset es Oedometric Edométrico
::msgcat::mcset es Hydrostatic Hidrostático
::msgcat::mcset es BTS BTS
::msgcat::mcset es {Load velocity} {Velocidad de carga}
::msgcat::mcset es {Confinement pressure} {Presión de confinamiento}
::msgcat::mcset es {Mesh type} {Tipo de Malla}
::msgcat::mcset es Predefined Predefinido
::msgcat::mcset es {Specimen length} {Longitud de la muestra}
::msgcat::mcset es {Specimen diameter} {Diámetro de la muestra}
::msgcat::mcset es {Top measuring group} {Grupo de medición superior}
::msgcat::mcset es {Top layer measure group} {Grupo con la capa superior de medida}
::msgcat::mcset es {Bottom measuring group} {Grupo de medición inferior}
::msgcat::mcset es {Bottom layer measure group} {Grupo con la capa inferior de medida}
::msgcat::mcset es {Cohesive groups} {Grupos cohesivos}
::msgcat::mcset es {Confinement Pressure} {Presión de confinamiento}
::msgcat::mcset es {Pressure Increment} {Incremento de presión}
::msgcat::mcset es {Pressure Increment Per Time Unit} {Incremento de presión por unidad de tiempo}
::msgcat::mcset es {Loading Velocity} {Velocidad de Carga}
::msgcat::mcset es {Elements assignation} {Asignación de Elementos}
::msgcat::mcset es {DEM Element} {Elemento DEM}
::msgcat::mcset es {Assign this atribute to a group containing Volumes which will be meshed as Spheres or to a group containing Spheres of the Mesh. Only the Spheres tagged with this attribute as DEM Element will be actually calculated.} {Asigne este atributo a un Grupo que contenga volúmenes que será mallado como Esferas o a un grupo conteniendo Esferas de la Malla. Sólo las esferas marcadas con este atributo como Elemento DEM se calcularán como tal.}
::msgcat::mcset es {Boundary Conditions, including inlets and moving walls} {Condiciones de contorno, incluyendo entradas y paredes móviles}
::msgcat::mcset es {Prescribed velocities} {Velocidades prescritas}
::msgcat::mcset es {DEM velocity boundary condition} {Condición de contorno en velocidades DEM}
::msgcat::mcset es Inlet Entrada
::msgcat::mcset es {It allows the insertion of new DEM elements into the domain} {Permite la inyección de nuevos Elementos DEM en el dominio}
::msgcat::mcset es {DEM-FEM wall} {Pared DEM-FEM}
::msgcat::mcset es {Apply this attribute to a Group containung Surfaces or Triangles of  Mesh. It will work as a wall which cannot be crossed by the DEM Elements} {Asigne este atributo a un Grupo que contenga Superficies o Triangulos de la Malla. Actuará como una pared que no puede ser atravesada por los Elementos DEM}
::msgcat::mcset es {General options} {Opciones generales}
::msgcat::mcset es {DEM general options} {Opciones generales del DEM}
::msgcat::mcset es {Bounding box} {Caja delimitadora}
::msgcat::mcset es {Any Discrete Element going outside of the Bounding Box will be deleted} {Cualquier Elemento Discreto que salga de la caja delimitadora será eliminado}
::msgcat::mcset es Active Activo
::msgcat::mcset es NotActive Desactivado
::msgcat::mcset es {Not active} Desactivado
::msgcat::mcset es {Any Discrete element going out of the bounding box will be deleted} {Cualquier Elemento Discreto que salga de la caja delimitadora será eliminado}
::msgcat::mcset es {Bounding box type} {Tipo de caja delimitadora}
::msgcat::mcset es {If Automatic is chosen, the bounding box will be created using the existing entities at the beginning of the computation} {Si se elije Automático, la Caja Delimitadora se creará usando las entidades existentes al principio del cálculo}
::msgcat::mcset es {Enlargement factor} {Factor de agrandamiento}
::msgcat::mcset es {Physical options} {Opciones físicas}
::msgcat::mcset es {DEM general physical options} {Opciones físicas generales del DEM}
::msgcat::mcset es Gx Gx
::msgcat::mcset es Gy Gy
::msgcat::mcset es Gz Gz
::msgcat::mcset es {Advanced options} {Opciones avanzadas}
::msgcat::mcset es {More advanced options that modify the computation} {Más opciones avanzadas que modifican el cálculo}
::msgcat::mcset es {Clean initial indentations} {Limpiar penetraciones iniciales}
::msgcat::mcset es {If activated, initial indentations between spheres and between spheres and walls are eliminated to avoid explosions (reducing the radius of the spheres accordigly)} {Si se activa, las penetraciones iniciales entre esferas y entre esferas y paredes son eliminadas para evitar explosiones (reduciendo el radio de las esferas de forma acorde)}
::msgcat::mcset es {Tangency tolerance} {Tolerancia en la tangencia}
::msgcat::mcset es Absolute Absoluta
::msgcat::mcset es Coordination_Number {Número de coordinación}
::msgcat::mcset es {Coordination Number} {Número de coordinación}
::msgcat::mcset es {Tangency tolerance value} {Valor de tolerancia en la tangencia}
::msgcat::mcset es {Coordination number} {Número de coordinación}
::msgcat::mcset es {Export model data information} {Exportar información de datos del modelo}
::msgcat::mcset es {Not Active} Desactivado
::msgcat::mcset es {Export Model Data Information} {Exportar Información de Datos del Modelo}
::msgcat::mcset es {Virtual mass coefficient} {Coeficiente de masa virtual}
::msgcat::mcset es {Virtual Mass} {Masa virtual}
::msgcat::mcset es {Calculate rotations} {Calcular rotaciones}
::msgcat::mcset es {If activated, torques and rotations will be calculated on the Discrete Elements. Will increase computation time slightly.} {Si se activa, momentos y fuerzas se calcularán en los Elementos Discretos. El tiempo de cálculo aumentará ligeramente.}
::msgcat::mcset es {Rolling friction} {Fricción de rodadura}
::msgcat::mcset es Activate Activar
::msgcat::mcset es NotActivate Desactivado
::msgcat::mcset es {If activated, the Rolling Friction parameter set in the Materials Tree will be taken into account. Otherwise it will be ignored. Will increase computation time slightly} {Si se activa, el parámetro de Fricción de Rodadura fijado en el Árbol de Materiales se tendrá en cuenta. Si no, se ignorará. Aumentará el tiempo de cálculo ligeramente}
::msgcat::mcset es Show Mostrar
::msgcat::mcset es Hide Esconder
::msgcat::mcset es {Show or Hide Material Test} {Mostrar o Esconder el Test de Material}
::msgcat::mcset es {Don't search until failure} {No buscar vecinos hasta rotura}
::msgcat::mcset es ON Encendido
::msgcat::mcset es OFF Apagado
::msgcat::mcset es {Remove DEM elements inside embedded} {Eliminar Elementos DEM dentro de la pared embebida}
::msgcat::mcset es {Removes DEM elements that are inside an embedded DEM-FEM wall} {Elimina Elementos DEM que se encuentran en el interior de una pared DEM-FEM embebida.}
::msgcat::mcset es {DEM-Fluid interaction} {Interacción DEM-Fluido}
::msgcat::mcset es {Options that affect the interaction between DEM and the Fluid} {Opciones que afectan la interacción entre el DEM y el Fluido}
::msgcat::mcset es {Drag correction} {Corrección del rozamiento}
::msgcat::mcset es Chien Chien
::msgcat::mcset es Hayder Hayder
::msgcat::mcset es {Select the method used for the drag correction due to sphericity} {Seleccione el método usado para la corrección del rozamiento debida a la Esfericidad}
::msgcat::mcset es {Two-way coupling} {Acoplamiento bidireccional}
::msgcat::mcset es {If activated, the particles affect the flow} {Si se activa, las partículas afectan al fluido}
::msgcat::mcset es {Consider Lift Force} {Considerar fuerzas de sustentación}
::msgcat::mcset es {If activated, the fluid will add a lift force to the particle, apart from the drag} {Si se activa, el fluido añadirá una fuerza de sustentación a la partícula, aparte del rozamiento}
::msgcat::mcset es {Options and parameters that change the numerical strategy} {Opciones y parámetros que cambian la estrategia numérica}
::msgcat::mcset es {Time integration scheme} {Esquema de integración temporal}
::msgcat::mcset es Forward_Euler {Forward Euler}
::msgcat::mcset es Mid_Point_Rule {Regla del Punto Medio}
::msgcat::mcset es {Forward Euler} {Forward Euler}
::msgcat::mcset es {Mid Point Rule} {Regla del Punto Medio}
::msgcat::mcset es {Time Integration Scheme} {Esquema de integración temporal}
::msgcat::mcset es {Locked to OpenMP (MPI will be available in the future)} {Bloqueado en OpenMP (MPI estará disponible en el futuro)}
::msgcat::mcset es {Set the number of threads you want to use for this computation. Do not choose more than the available threads on your computer or the computation will be slower} {Fije el número de procesadores que quiera usar para este cálculo. No escoja más de los disponibles en su ordenador o el cálculo será más lento}
::msgcat::mcset es {Options and parameters related with time} {Opciones y parámetros relacionados con el tiempo}
::msgcat::mcset es {Delta time selection} {Selección del paso de tiempo}
::msgcat::mcset es {Select the type of Delta time to be used} {Selecciones el tipo de incremento de Tiempo que se usará}
::msgcat::mcset es {Delta time (s)} {Incremento de tiempo (s)}
::msgcat::mcset es {Delta time used by DEM} {Paso de tiempo usado por el DEM}
::msgcat::mcset es {Delta time safety factor} {Factor de seguridad del paso de tiempo}
::msgcat::mcset es {Total time (s)} {Tiempo total (s)}
::msgcat::mcset es {Total Time} {Tiempo total}
::msgcat::mcset es {Info screen output} {Salida de información por pantalla}
::msgcat::mcset es {How often the user gets information on the running process (in seconds)} {Con qué frecuencia el usuario recibe información sobre el proceso en ejecución (en segundos)}
::msgcat::mcset es {Neighbour search frequency} {Frecuencia de búsqueda de vecinos}
::msgcat::mcset es {choose how often the neighbours are searched. 1 means every time step, 10 means 1 out of 10 steps} {Elija con qué frecuencia se buscan vecinos. 1 significa cada paso de tiempo, 10 significa 1 vez cada 10 pasos.}
::msgcat::mcset es {Adjust the level of detail, frequency and type of the results that must be printed on disk during the computation} {Ajuste el nivel de detalle, frecuencia y tipo de resultados que se imprimirán en disco durante el cálculo}
::msgcat::mcset es {Output time step (s)} {Paso de tiempo de salida (s)}
::msgcat::mcset es {Set here the time increment between prints of results for GiD (in seconds)} {Fije aquí el incremento de tiempo entre impresiones de resultados para GiD (en segundos)}
::msgcat::mcset es {Print in Post-Process} {Imprimir en Post-Proceso}
::msgcat::mcset es {Results on DEM elements that can be colored or shown as vectors on GiD, among other options} {Resultados en los Elementos DEM que se pueden colorear o mostrar en forma de vectores, entre otras opciones}
::msgcat::mcset es Radius Radio
::msgcat::mcset es {Angular velocity} {Velocidad Angular}
::msgcat::mcset es {Elastic Forces} {Fuerzas Elásticas}
::msgcat::mcset es {Contact Forces} {Fuerzas de Contacto}
::msgcat::mcset es {Rigid Element Forces} {Fuerzas en Elemento Rígido}
::msgcat::mcset es {Tangential Elastic Forces} {Fuerzas Elásticas Tangenciales}
::msgcat::mcset es {Total forces} {Fuerzas totales}
::msgcat::mcset es {Total Forces} {Fuerzas Totales}
::msgcat::mcset es {Shear Stress} {Tensión Cortante}
::msgcat::mcset es Wear Desgaste
::msgcat::mcset es {It computes the volume of removed material due to wear} {Calcula el volumen de material arrancado debido al desgaste}
::msgcat::mcset es {Nodal Area} {Área Nodal}
::msgcat::mcset es {Damp forces} {Fuerzas de amortiguamiento}
::msgcat::mcset es {Applied forces} {Fuerzas aplicadas}
::msgcat::mcset es GroupId IdGrupo
::msgcat::mcset es {Export Id} {Exportar Id}
::msgcat::mcset es {Export skin sphere} {Exportar esferas de la piel}
::msgcat::mcset es {Particle moment} {Momento en la partícula}
::msgcat::mcset es {Euler angles} {Ángulos de Euler}
::msgcat::mcset es {On FEM elements} {En los elementos FEM}
::msgcat::mcset es {Results on FEM elements} {Resultados en los elementos FEM}
::msgcat::mcset es Graphs Gráficos
::msgcat::mcset es {Options for printing graphs from the computed results} {Opciones para imprimir gráficos a partir del cálculo}
::msgcat::mcset es {Force evolution with time} {Evolución de la fuerza con el tiempo}
::msgcat::mcset es {Printing delta time (s)} {Imprimiendo incremento de tiempo (s)}
::msgcat::mcset es {Printing delta time} {Imprimiendo incremento de tiempo}
::msgcat::mcset es {Force integration group} {Grupo donde integrar fuerzas}
::msgcat::mcset es {Force Integration Group} {Grupo donde integrar fuerzas}
::msgcat::mcset es {Show bond elements} {Mostrar elementos de enlace}
::msgcat::mcset es {Show Bond Elements} {Mostra los Elementos de Enlace}
::msgcat::mcset es {On bond elements} {En los elementos de enlace}
::msgcat::mcset es {Results on bond elements} {Resultados en los enlaces entre elementos}
::msgcat::mcset es {Contact sigma} {Sigma en el contacto}
::msgcat::mcset es {Contact tau} {Tau en el contacto}
::msgcat::mcset es {Local contact force} {Fuerza local en el contacto}
::msgcat::mcset es {Failure criterion state} {Estado de criterio de rotura}
::msgcat::mcset es {Failure id} {Id de rotura}
::msgcat::mcset es {Mean contact area} {Área de contacto media}
::msgcat::mcset es {Velocity trap} {Trampa de velocidad}
::msgcat::mcset es {If activated, this option creates a Box in which some measurements are done: average velocity of the particles, entering flux of particles, entering flux of mass,...} {Si se activa, esta opción crea una Caja en la que se hacen mediciones: media de la velocidad de las partículas, flujo de partículas entrantes, flujo de masa entrante,...}
::msgcat::mcset es {Active velocity trap} {Activar trampa de velocidad}
::msgcat::mcset es {Printing time step (s)} {Imprimiendo paso de tiempo (s)}
::msgcat::mcset es {Printing delta time for the velocity trap} {Imprimiendo incremento de tiempo para la trampa de velocidad}
::msgcat::mcset es {GiD postprocess additional options} {Opciones adicionales para el PostProceso en GiD}
::msgcat::mcset es {GiD result file format. Choose Binary or Ascii. Ascii takes more hard disk space, but is human readable} {Formato de los archivos resultados de GiD. Elija Binario o Ascii. Ascii consume más espacio en disco, pero se puede leer por una persona}
::msgcat::mcset es {Multiple files} {Múltiples archivos}
::msgcat::mcset es {Single file} {Archivo único}
::msgcat::mcset es Curves Curvas
::msgcat::mcset es {Curve definition} {Definición de la curva}
::msgcat::mcset es {2D element} {Elemento 2D}
::msgcat::mcset es {Element Properties} {Propiedades del Elemento}
::msgcat::mcset es {Element type} {Tipo de elemento}
::msgcat::mcset es Triangle Triángulo
::msgcat::mcset es Quadrilateral Cuadrilátero
::msgcat::mcset es {Element Type} {Tipo de elemento}
::msgcat::mcset es Property Propiedad
::msgcat::mcset es {Beam total Lagrangian} {Viga total Lagrangiana}
::msgcat::mcset es Tetrahedra Tetraedros
::msgcat::mcset es {Membrane element} {Elemento de membrana}
::msgcat::mcset es Activation Activación
::msgcat::mcset es Values Valores
::msgcat::mcset es {Set the values} {Fije los valores}
::msgcat::mcset es {X coordinate} {Coordenada X}
::msgcat::mcset es {Y coordinate} {Coordenada Y}
::msgcat::mcset es {Z coordinate} {Coordenada Z}
::msgcat::mcset es {X velocity} {Velocidad X}
::msgcat::mcset es {Y velocity} {Velocidad Y}
::msgcat::mcset es {Z velocity} {Velocidad Z}
::msgcat::mcset es Fixity Fijo
::msgcat::mcset es {Fix X velocity} {Fijar velocidad X}
::msgcat::mcset es {Fix Y velocity} {Fijar velocidad Y}
::msgcat::mcset es {Fix Z velocity} {Fijar velocidad Z}
::msgcat::mcset es {No Slip} {No Slip}
::msgcat::mcset es {PFEM Wall} {PFEM pared}
::msgcat::mcset es {Linear Velocity} {Velocidad Lineal}
::msgcat::mcset es Periodic Periódico
::msgcat::mcset es {Angular Velocity} {Velocidad angular}
::msgcat::mcset es {Rotation Center} {Centro de rotación}
::msgcat::mcset es {X displacement} {Desplazamiento X}
::msgcat::mcset es {Y displacement} {Desplazamiento Y}
::msgcat::mcset es {Z displacement} {Desplazamiento Z}
::msgcat::mcset es Boundingbox {Caja delimitadora}
::msgcat::mcset es {DEM inlet boundary condition} {Condición de entrada de DEM}
::msgcat::mcset es {New property} {Nueva Propiedad}
::msgcat::mcset es SphericParticle3D SphericParticle3D
::msgcat::mcset es Cluster3D Cluster3D
::msgcat::mcset es {Choose if you want this Inlet to insert spheres or clusters} {Escoja si quiere que esta Entrada inyecte Esferas o Clusters}
::msgcat::mcset es Sphere Esfera
::msgcat::mcset es Cluster Cluster
::msgcat::mcset es {Cluster Type} {Tipo de Cluster}
::msgcat::mcset es Rock1Cluster3D ClusterRoca
::msgcat::mcset es Rock2Cluster3D ClusterRoca2
::msgcat::mcset es Ballast1Cluster3D ClusterBalasto
::msgcat::mcset es Ballast2Cluster3D ClusterBalasto2
::msgcat::mcset es Ballast3Cluster3D ClusterBalasto3
::msgcat::mcset es Ballast4Cluster3D ClusterBalasto4
::msgcat::mcset es Ballast5Cluster3D ClusterBalasto5
::msgcat::mcset es Ballast6Cluster3D ClusterBalasto6
::msgcat::mcset es LineCluster3D ClusterLínea
::msgcat::mcset es CubeCluster3D ClusterCubo
::msgcat::mcset es PillCluster3D ClusterPastilla
::msgcat::mcset es EllipsoidCluster3D ClusterElipsoide
::msgcat::mcset es RingCluster3D ClusterAnillo
::msgcat::mcset es SoyBeanCluster3D ClusterSoja
::msgcat::mcset es SoyBean3Cluster3D ClusterSoja3
::msgcat::mcset es CornKernelCluster3D ClusterMaíz
::msgcat::mcset es Wheat5Cluster3D ClusterTrigo5
::msgcat::mcset es {Choose the shape of the particle or cluster of particles} {Escoja la forma de la partícula o clúster de partículas}
::msgcat::mcset es {Velocity modulus (m/s)} {Módulo de la velocidad (m/s)}
::msgcat::mcset es {Velocity modulus of the particles} {Módulo de velocidad de las partículas}
::msgcat::mcset es {Direction vector X} {Vector de dirección X}
::msgcat::mcset es {Direction vector X. The vector does not have to be unitary} {Vector de dirección X. No tiene por qué ser unitario}
::msgcat::mcset es {Direction vector Y} {Vector de dirección Y}
::msgcat::mcset es {Direction vector Y. The vector does not have to be unitary} {Vector de dirección Y. No tiene por qué ser unitario}
::msgcat::mcset es {Direction vector Z} {Vector de dirección Z}
::msgcat::mcset es {Direction vector Z. The vector does not have to be unitary} {Vector de dirección Z. No tiene por qué ser unitario}
::msgcat::mcset es {Max random velocity deviation (deg)} {Máxima desviación aleatoria de la velocidad (grados)}
::msgcat::mcset es {The maximum value for the added deviation to the given velocity} {El máximo valor para la desviación añadida a la velocidad dada}
::msgcat::mcset es {Number of particles} {Número de partículas}
::msgcat::mcset es {Number of particles per second generated by this inlet} {Número de partículas por segundo generadas por esta entrada}
::msgcat::mcset es {Inlet start time (s)} {Tiempo de inicio de la entrada (s)}
::msgcat::mcset es {Inlet start time} {Tiempo de inicio de la entrada}
::msgcat::mcset es {Inlet stop time (s)} {Tiempo final de la entrada (s)}
::msgcat::mcset es {Inlet stop time} {Tiempo final de la entrada}
::msgcat::mcset es Material Material
::msgcat::mcset es {Exclude boundaries} {Excluir bordes}
::msgcat::mcset es {If active, the nodes on the boundary will not generate elements, only the inner nodes} {Si se activa, los nodos en el contorno no generarán elementos, sólo los interiores}
::msgcat::mcset es {Diameter (m)} {Diámetro (m)}
::msgcat::mcset es {Particle diameter} {Diámetro de la partícula}
::msgcat::mcset es {Probability Distribution} {Distribución de Probabilidad}
::msgcat::mcset es normal normal
::msgcat::mcset es lognormal lognormal
::msgcat::mcset es {Choose the probablility distribution of the diameter} {Escoja la distribución de probabilidad del diámetro}
::msgcat::mcset es {Standard Deviation} {Desviación estándar}
::msgcat::mcset es {Standard Deviation of the Diameter, assuming Normal Distribution. If 0.0 is chosen, a uniform diameter distribution will be created} {Desviación Estándar del diámetro, asumiendo Distribución Normal. Si se escoge 0.0, se creará una distribución de diámetros uniforme }
::msgcat::mcset es {Random Euler Angles} {Ángulos de Euler aleatorios}
::msgcat::mcset es {Euler Angle X (rad)} {Ángulo de Euler X (rad)}
::msgcat::mcset es {Euler Angle X} {Ángulo de Euler X}
::msgcat::mcset es {Euler Angle Y (rad)} {Ángulo de Euler Y (rad)}
::msgcat::mcset es {Euler Angle Y} {Ángulo de Euler Y}
::msgcat::mcset es {Euler Angle Z (rad)} {Ángulo de Euler Z (rad)}
::msgcat::mcset es {Euler Angle Z} {Ángulo de Euler Z}
::msgcat::mcset es Fix Fijar
::msgcat::mcset es {Fix linear and/or angular velocities} {Fijar la velocidad lineal y/o angular}
::msgcat::mcset es {Fix Velocity X} {Fijar Velocidad X}
::msgcat::mcset es {Fix Velocity Y} {Fijar Velocidad Y}
::msgcat::mcset es {Fix Velocity Z} {Fijar Velocidad Z}
::msgcat::mcset es {Fix Angular Velocity X} {Fijar la Velocidad Angular X}
::msgcat::mcset es {Fix Angular Velocity Y} {Fijar la Velocidad Angular Y}
::msgcat::mcset es {Fix Angular Velocity Z} {Fijar la Velocidad Angular Z}
::msgcat::mcset es {Velocities Values} {Valores de Velocidad}
::msgcat::mcset es {Velocity X} {Velocidad X}
::msgcat::mcset es {X Velocity} {Velocidad X}
::msgcat::mcset es {Velocity Y} {Velocidad Y}
::msgcat::mcset es {Y Velocity} {Velocidad Y}
::msgcat::mcset es {Velocity Z} {Velocidad Z}
::msgcat::mcset es {Z Velocity} {Velocidad Z}
::msgcat::mcset es {Angular Velocity X} {Velocidad Angular X}
::msgcat::mcset es {X Angular Velocity} {Velocidad angular X}
::msgcat::mcset es {Angular Velocity Y} {Velocidad Angular Y}
::msgcat::mcset es {Y Angular Velocity} {Velocidad angular Y}
::msgcat::mcset es {Angular Velocity Z} {Velocidad Angular Z}
::msgcat::mcset es {Z Angular Velocity} {Velocidad angular Z}
::msgcat::mcset es {DEM swimming sphere} {Esfera nadadora DEM}
::msgcat::mcset es DEM-Cohesivegroups {Grupos cohesivos DEM}
::msgcat::mcset es {Cohesive group} {Grupo cohesivo}
::msgcat::mcset es {Forces and torques will be integrated and printed to a file for the selected Groups} {Fuerzas y momentos se integrarán y se imprimirán en un archivo para los grupos seleccionados}
::msgcat::mcset es {Print total force on this group} {Imprimir la fuerza total sobre este grupo}
::msgcat::mcset es {Print total torque on this group} {Imprimir momento total sobre este grupo}
::msgcat::mcset es {DEM-FEM wall boundary condition} {Condición de contorno de pared DEM-FEM}
::msgcat::mcset es {Linear velocity} {Velocidad lineal}
::msgcat::mcset es {This velocity will be imposed to the group. It is the maximum linear velocity if it is chosen to be periodic} {Esta velocidad será impuesta sobre el grupo. Es la máxima velocidad lineal si se escoge que sea periódica}
::msgcat::mcset es {Vx (m/s)} {Vx (m/s)}
::msgcat::mcset es {Component X of the Linear Velocity} {Componente X de la Velocidad Lineal}
::msgcat::mcset es {Vy (m/s)} {Vy (m/s)}
::msgcat::mcset es {Component Y of the Linear Velocity} {Componente Y de la Velocidad Lineal}
::msgcat::mcset es {Vz (m/s)} {Vz (m/s)}
::msgcat::mcset es {Component Z of the Linear Velocity} {Componente Z de la Velocidad Lineal}
::msgcat::mcset es {If activated, the imposed velocity values are the maximum during a harmonic oscillation with a given period} {Si se activa, los valores de velocidad impuesta son el máximo de una oscilación harmónica con un periodo dado}
::msgcat::mcset es {Period (s)} {Periodo (s)}
::msgcat::mcset es {in seconds} {en segundos}
::msgcat::mcset es {Start time (s)} {Tiempo de inicio (s)}
::msgcat::mcset es {End time (s)} {Tiempo final (s)}
::msgcat::mcset es {This angular velocity will be imposed to the group. It is the maximum angular velocity if it is chosen to be periodic} {Esta velocidad angular se impondrá sobre el Grupo. Es la máxima velocidad angular si se escoge que sea periódica}
::msgcat::mcset es {Component X of the Angular Velocity} {Componente X de la Velocidad Angular}
::msgcat::mcset es {Component Y of the Angular Velocity} {Componente Y de la Velocidad Angular}
::msgcat::mcset es {Component Z of the Angular Velocity} {Componente Z de la Velocidad Angular}
::msgcat::mcset es {CenterX (m)} {CentroX (m)}
::msgcat::mcset es {Component X of the position of the Rotation Center. If a linear velocity is imposed to this group, it will affect this center} {Componente X de la posición del Centro de Rotación. Si una velocidad lineal se impone sobre este Grupo, afectará a este Centro}
::msgcat::mcset es {CenterY (m)} {CentroY (m)}
::msgcat::mcset es {Component Y of the position of the Rotation Center. If a linear velocity is imposed to this group, it will affect this center} {Componente Y de la posición del Centro de Rotación. Si una velocidad lineal se impone sobre este grupo, afectará a este Centro}
::msgcat::mcset es {CenterZ (m)} {CentroZ (m)}
::msgcat::mcset es {Component Z of the position of the Rotation Center. If a linear velocity is imposed to this group, it will affect this center} {Componente Y de la posición del Centro de Rotación. Si una velocidad lineal se impone sobre este grupo, afectará a este Centro}
::msgcat::mcset es Settings Ajustes
::msgcat::mcset es {Options that will affect the behaviour during the contact bewteen Discrete Elements and this wall} {Opciones que afectan al comportamiento durante el contacto entre los Elementos Discretos y esta pared}
::msgcat::mcset es {Update velocity, not displacements} {Actualizar velocidades, no los desplazamientos}
::msgcat::mcset es {If activated, the wall will not move and will just have an imposed velocity field} {Si se activa, la pared no se moverá y simplemente tendrá un campo de velocidades impuesto}
::msgcat::mcset es {Friction angle (deg)} {Ángulo de fricción (grados)}
::msgcat::mcset es {Coulomb friction coefficient} {Coeficiente de fricción de Coulomb}
::msgcat::mcset es {Cohesive Wall} {Pared Cohesiva}
::msgcat::mcset es {Specify if the wall presents a cohesive behaviour} {Especifique si la pared presenta un comportamiento cohesivo}
::msgcat::mcset es {Wall Cohesion (Pa)} {Cohesión de la pared (Pa)}
::msgcat::mcset es {JKR cohesion parameter} {Parámetro de cohesión JKR}
::msgcat::mcset es {Compute Wear} {Calcular desgaste}
::msgcat::mcset es {If activated, wear will be computed on this wall. It can increase computation time} {Si se activa, el desgaste se calculará en esta pared. Puede aumentar el tiempo de cálculo}
::msgcat::mcset es {Severity of Abrasion} {Severidad de la Abrasión}
::msgcat::mcset es {Archard's abrasion K parameter} {Parámetro K de abrasión de Archard}
::msgcat::mcset es {Severity of Impact} {Severidad de Impacto}
::msgcat::mcset es {Archard's impact K parameter} {Parámetro K de impacto Archard}
::msgcat::mcset es {Brinell Hardness (HB)} {Dureza Brinell}
::msgcat::mcset es {Brinell hardness value} {Valor de dureza Brinell}
::msgcat::mcset es {Embed this Wall in the fluid} {Embeber esta pared en el fluido}
::msgcat::mcset es {If activated, the fluid will also feel this group as a wall} {Si se activa, el fluido también verá este Grupo como una pared}
::msgcat::mcset es {Fix coordinates} {Coordenadas fijas}
::msgcat::mcset es {Property type} {Tipo de Propiedad}
::msgcat::mcset es {Constitutive law} {Ley constitutiva}
::msgcat::mcset es Thickness Espesor
::msgcat::mcset es {Select the profile from the list} {Seleccione un perfil de la lista}
::msgcat::mcset es Area Área
::msgcat::mcset es {Cross section area} {Sección transversal}
::msgcat::mcset es {Inertia Ix} {Inercia Ix}
::msgcat::mcset es {Moment of inertia Ix} {Momento de inercia Ix}
::msgcat::mcset es {Inertia Iy} {Inercia Iy}
::msgcat::mcset es {Moment of inertia Iy} {Momento de inercia Iy}
::msgcat::mcset es Height Altura
::msgcat::mcset es {Height value} {Valor de altura}
::msgcat::mcset es Width Ancho
::msgcat::mcset es {Width value} Anchura
::msgcat::mcset es Diameter Diámetro
::msgcat::mcset es {Diameter value} {Valor del diámetro}
::msgcat::mcset es {Fix value} {Fijar valor}
::msgcat::mcset es {Fix the temperature value} {Fijar el valor de temperatura}
::msgcat::mcset es Value Valor
::msgcat::mcset es BodyForce {Fuerza cuerpo}
::msgcat::mcset es Fx Fx
::msgcat::mcset es {Fx Vector} {Vector Fx}
::msgcat::mcset es Fy Fy
::msgcat::mcset es {Fy Vector} {Vector Fy}
::msgcat::mcset es Fz Fz
::msgcat::mcset es {Fz Vector} {Vector Fz}
::msgcat::mcset es Mx Mx
::msgcat::mcset es {Mx Vector} {Mx Vector}
::msgcat::mcset es My My
::msgcat::mcset es {My Vector} {My Vector}
::msgcat::mcset es Mz Mz
::msgcat::mcset es {Mz Vector} {Mz Vector}
::msgcat::mcset es {Point Moment} {Momento Puntual}
::msgcat::mcset es {Line load values} {Valores de carga}
::msgcat::mcset es {Fix pressure} {Pressión fija}
::msgcat::mcset es Negative Negativo
::msgcat::mcset es {Defines which side of the face that matches the direction of the normal to the surface, positive or negative} {Define qué lado de la cara coincide con la dirección de la normal a la superficie, positivo o negativo}
::msgcat::mcset es {Pressure value} {Valor de presión}
::msgcat::mcset es Vx Vx
::msgcat::mcset es {X initial velocity} {Velocidad inicial X}
::msgcat::mcset es Vy Vy
::msgcat::mcset es {Y initial velocity} {Velocidad inicial Y}
::msgcat::mcset es Vz Vz
::msgcat::mcset es {Z initial velocity} {Velocidad inicial Z
}
::msgcat::mcset es {Flag variable} {Variables Flag}
::msgcat::mcset es {Select the flag value} {Seleccione el valor del indicador}
::msgcat::mcset es {Is-Slip conditional data} {Es-Slip datos condicionales}
::msgcat::mcset es {Select the activate option value} {Seleccione el valor de la opción de activación}
::msgcat::mcset es {Define the value} {Definir el valor}
::msgcat::mcset es {Is-boundary conditional data} {Datos condicional es contorno}
::msgcat::mcset es {New group} {Nuevo Grupo}
::msgcat::mcset es {Level set distance data} {Distancia datos 'level set'}
::msgcat::mcset es {Porosity and diameter data} {Porosidad y datos diámetro}
::msgcat::mcset es {Define the porosity value} {Definir el valor de porosidad}
::msgcat::mcset es {Define the diameter value} {Definir el valor del diámetro}
::msgcat::mcset es {Porosity and darcy law data} {Porosidad y datos ley de Darcy}
::msgcat::mcset es {Define the linear Darcy coefficient value} {Definir el valor del coeficiente de Darcy lineal}
::msgcat::mcset es {Define the nonlinear Darcy coefficient value} {Definir el valor del coeficiente de Darcy no lineal}
::msgcat::mcset es {Cut properties} {Propiedades corte}
::msgcat::mcset es Origin Origen
::msgcat::mcset es {Origin properties} {Propiedades de Origen}
::msgcat::mcset es {Normal to plane} {Normal al plano}
::msgcat::mcset es {Normal to the plane} {Normal al plano}
::msgcat::mcset es {History output on points properties} {Historia salid propiedades puntos}
::msgcat::mcset es {History graph properties} {Historia propiedades del gráfico}
::msgcat::mcset es {X coordinate of the output point} {Coordenada X en el punto salida}
::msgcat::mcset es {Y coordinate of the output point} {Coordenada Y en el punto salida}
::msgcat::mcset es {Z coordinate of the output point} {Coordenada Z en el punto salida}
::msgcat::mcset es Variable Variable
::msgcat::mcset es {Variable to be plotted for this output point} {Variable a imprimir para este punto de salida}
::msgcat::mcset es {Output file} {Archivo de salida}
::msgcat::mcset es {Output file identifier} {Identificador de archivo de salida}
::msgcat::mcset es {Output file Id} {Id del archivo de salida}
::msgcat::mcset es {Curve Identifier} {Identificador curva}
::msgcat::mcset es {Type of curve} {Tipo de curva}
::msgcat::mcset es Time Tiempo
::msgcat::mcset es YoungModulus {Módulo de Young}
::msgcat::mcset es More Más
::msgcat::mcset es Points Puntos
::msgcat::mcset es {Curve Points} {Puntos curva}
::msgcat::mcset es {Check problem type version} {Compruebe la versión del Problem Type}
::msgcat::mcset es {Write all GiD groups} {Escribir todos los grupos de GiD}
::msgcat::mcset es Solid Sólido
::msgcat::mcset es General General
::msgcat::mcset es Description Descripción
::msgcat::mcset es Density Densidad
::msgcat::mcset es Structural Estructural
::msgcat::mcset es {Young modulus} {Módulo de Young}
::msgcat::mcset es {Shear modulus} {Módulo de Corte}
::msgcat::mcset es {Poisson ratio} {Coefficiente de Poisson}
::msgcat::mcset es Plasticity Plasticidad
::msgcat::mcset es {Yield criterion} {Criterio de fluencia}
::msgcat::mcset es Energy Energía
::msgcat::mcset es Mohr-Coulomb Mohr-Coulomb
::msgcat::mcset es Rankine Rankine
::msgcat::mcset es {Yield Stress} {Tensión de Fluencia}
::msgcat::mcset es {Dilatancy angle} {Ángulo de dilatancia}
::msgcat::mcset es {Saturation law} {Ley de saturación}
::msgcat::mcset es Non No
::msgcat::mcset es Exponential Exponencial
::msgcat::mcset es Damage Daño
::msgcat::mcset es {Tensile strength} {Resistencia a la tracción}
::msgcat::mcset es {Tensile fracture energy} {Enercía de fractura de tracción}
::msgcat::mcset es Thermal Térmico
::msgcat::mcset es {Expansion coeff} {Coeficiente de expansión}
::msgcat::mcset es {Specific heat} {Calor específico}
::msgcat::mcset es Viscosity Viscosidad
::msgcat::mcset es {Bulk Modulus} {Módulo de compressibilidad}
::msgcat::mcset es Air Aire
::msgcat::mcset es Water Agua
::msgcat::mcset es Plastic Plástico
::msgcat::mcset es Composite Compuesto
::msgcat::mcset es {DEM material} {Material DEM}
::msgcat::mcset es DEM-DefaultMaterial {DEM-Material por defecto}
::msgcat::mcset es {Material name} {Nombre de material}
::msgcat::mcset es {Particle properties} {Propiedades de la partícula}
::msgcat::mcset es Sphericity Esfericidad
::msgcat::mcset es {Particle sphericity} {Esfericidad de la partícula}
::msgcat::mcset es {Friction angle} {Ángulo de fricción}
::msgcat::mcset es {Particle friction angle} {Ángulo de fricción de la partícula}
::msgcat::mcset es {Restitution coefficient} {Coeficiente de restitución}
::msgcat::mcset es {Rotational damping ratio} {Ratio de amortiguamiento rotacional}
::msgcat::mcset es Color Color
::msgcat::mcset es {New DEM material type} {Nuevo tipo de material DEM}
::msgcat::mcset es {Non-Newtonian fluid} {Fluido no Newtoniano}
::msgcat::mcset es {Non-Newtonian fluid option} {Opción de fluido no Newtoniano}
::msgcat::mcset es {Plastic viscosity} {Viscosidad plástica}
::msgcat::mcset es {Define the plastic viscosity value} {Defina el valor de la viscosidad plástica}
::msgcat::mcset es {Bingham smoother} {Parámetro regularizador de Bingham}
::msgcat::mcset es {Define the Bingham smoother value} {Defina el valor del parámetro regularizador de Bingham}
::msgcat::mcset es {Yield stress} {Tensión de fluencia}
::msgcat::mcset es {Define the yield stress value} {Defina el valor de la tensión de fluencia}
::msgcat::mcset es {Power law N} {n de la ley potencial}
::msgcat::mcset es {Define the power law n value} {Defina el valor de la n de la ley potencial}
::msgcat::mcset es {Power law K} {K de la ley potencial}
::msgcat::mcset es {Define the power law K value} {Defina el valor de la K de la ley potencial}
::msgcat::mcset es {Gel strength} {Resistencia de Gel}
::msgcat::mcset es {Define the gel strength} {Defina la resistencia de gel}
::msgcat::mcset es {Power Law N} {n de la ley potencial}
::msgcat::mcset es {Define the power law N value} {Defina el valor de la n de la ley potencial}
::msgcat::mcset es {Power Law K} {K de la ley potencial}
::msgcat::mcset es {Define the gel strength value} {Defina el valor de la resistencia de gel}
::msgcat::mcset es {Density (Kg/m3)} {Densidad (Kg/m3)}
::msgcat::mcset es {Density of the material (not bulk density)} {Densidad del material (no de conjunto o peso bruto)}
::msgcat::mcset es {Young modulus (Pa)} {Módulo de Young (Pa)}
::msgcat::mcset es {The Young's Modulus of the material (not bulk stiffness)} {Módulo de Young del material (no la rigidez del conjunto)}
::msgcat::mcset es {The Poisson's Ratio of the material (not bulk Ratio)} {El coeficiente de Poisson del material (no del conjunto)}
::msgcat::mcset es {Cohesion (Pa)} {Cohesión (Pa)}
::msgcat::mcset es {Particle cohesion (JKR)} {Cohesión de la partícula (JKR)}
::msgcat::mcset es {Particle friction angle (for Coulomb's friction)} {Ángulo de fricción de la partícula (para la fricción de Coulomb)}
::msgcat::mcset es {Coefficient of restitution} {Coeficiente de restitución}
::msgcat::mcset es {Discontinuum Contact Law} {Ley de contacto de discontinuo}
::msgcat::mcset es {Contact Laws based on Thornton, Cummins, Cleary, 2013: LSD and HMD} {Leyes de contacto basadas en Thornton, Cummins, Cleary, 2013: LSD y HMD}
::msgcat::mcset es DEM-SoyBean {DEM-Grano de soja}
::msgcat::mcset es {Particle cohesion} {Cohesión de la partícula}
::msgcat::mcset es {Discontinuous Contact Law} {Ley de contacto de discontinuo}
::msgcat::mcset es DEM-CornKernel DEM-Maíz
::msgcat::mcset es DEM-Wheat5 DEM-Trigo5
::msgcat::mcset es DEM-Rock1 DEM-Roca1
::msgcat::mcset es DEM-Rock2 DEM-Roca2
::msgcat::mcset es DEM-Ballast DEM-Balasto
::msgcat::mcset es {Particle cohesion (Pa)} {Cohesión de la partícula (Pa)}
::msgcat::mcset es {This GiD version is too old, get the last available version} {Esta versión de GiD es demasiado antigua, consiga la versión disponible más reciente}
::msgcat::mcset es {Couldn't read file %s} {No se pudo leer el archivo %s}
::msgcat::mcset es {Configuration file %s not found} {El archivo de configuración %s no se ha encontrado}
::msgcat::mcset es {Error: This interface requires GiD %s or later} {Error: esta interfaz requiere GiD %s o posterior}
::msgcat::mcset es {Error reading file '%s': %s} {Error al leer archivo '%s': %s}
::msgcat::mcset es {The simulation is not calculated yet or is currently being calculated} {La simulación no ha sido realizada o está en curso}
::msgcat::mcset es {MPI is not available for Windows yet. You can use OpenMP instead.} {MPI aun no está disponible en Windows. Puede usar OpenMP en su lugar.}
::msgcat::mcset es {Model validation} {Validación del modelo}
::msgcat::mcset es Close Cerrar
::msgcat::mcset es {Close the report window} {Cerrar la ventana de informe}
::msgcat::mcset es Print Imprimir
::msgcat::mcset es {Print the report via a temporal file using notepad} {Imprimir informe vía archivo temporal en notepad}
::msgcat::mcset es {Warning: Repeated groups (%s) between %s and %s} {Aviso: Grupos repetidos (%s) entre %s y %s}
::msgcat::mcset es {Warning: Repeated node (%s) between the %s and %s boundary condition. Check the group properties assigned to this boundary conditions} {Aviso: Nodo repetido (%s) entre las condiciones de contorno %s y %s. Compruebe las propiedades de grupo asignadas a esta condición de contorno}
::msgcat::mcset es Kratos#C#menu Kratos
::msgcat::mcset es {Model properties#C#menu} {Propiedades del modelo}
::msgcat::mcset es {Material database#C#menu} {Base de datos de materiales}
::msgcat::mcset es {Project settings#C#menu} {Propiedades proyecto}
::msgcat::mcset es {Define the group properties using the group editor} {Defina el grupo de propiedades con el editor de grupos}
::msgcat::mcset es {Define the model properties} {Define las propiedades del modelo}
::msgcat::mcset es {Define the material properties} {Define las propiedades del modelo}
::msgcat::mcset es {Define the curve properties} {Define las propiedades de la curva}
::msgcat::mcset es {Open the process control window} {Abrir ventana de control de proceso}
::msgcat::mcset es {Run the simulation} {Ejecutar la simulación}
::msgcat::mcset es {View process info} {Ver información de proyecto}
::msgcat::mcset es {Cancel process} {Cancelar proceso}
::msgcat::mcset es {Model definition toolbar} {Toolbar de definición del modelo}
::msgcat::mcset es {Could not make a backup copy of Kratos interface data file (%s)} {No se puede hacer una copia del fichero de Kratos (%s)}
::msgcat::mcset es {Cannot write file %s. Permission denied} {No se puede escribir el fichero %s. Permiso denegado}
::msgcat::mcset es {Kratos global settings} {Kratos global settings}
::msgcat::mcset es {Save and Close} {Guardar y cerrar}
::msgcat::mcset es {Printing is only supported under Windows} {Solo se puede imprimir en Windows}
::msgcat::mcset es {An error has been detected when get a temporal directory} {Se ha detectado un error accediendo a un directorio temporal}
::msgcat::mcset es {The project must be saved} {El proyecto tiene que estar guardado}
::msgcat::mcset es {Compressible fluids are not available in this version} {Fluidos compresibles no están disponibles en esta versión}
::msgcat::mcset es {Pick Coordinates} {Escoger Coordenadas}
::msgcat::mcset es {Function manager} {Administrador de funciones}
::msgcat::mcset es {Unassign function} {Desasignar función}
::msgcat::mcset es {Entity %s} {Entidad %s}
::msgcat::mcset es Group Grupo
::msgcat::mcset es newGroup {nuevo grupo}
::msgcat::mcset es {Create automatic new group} {Crear grupo automáticamente}
::msgcat::mcset es Ok Aceptar
::msgcat::mcset es {Assign condition to the selected group} {Asignar condiciones para el grupo seleccionado}
::msgcat::mcset es Cancel Cancelar
::msgcat::mcset es {Cancel assignation} {Cancelar asignación}
::msgcat::mcset es {Cut Id} {Corte Id}
::msgcat::mcset es {Choose a new cut identifier} {Elija nuevo identificador de corte}
::msgcat::mcset es {Graph Id} {Gráfico Id}
::msgcat::mcset es {Choose a new graph identifier} {Elija un nuevo identificador gráfico}
::msgcat::mcset es {Property Id} {Propiedad Id}
::msgcat::mcset es {Choose a new property identifier} {Elija un nuevo identificador de la propiedad}
::msgcat::mcset es {Assign the defined properties} {Asignar las propiedades definidas}
::msgcat::mcset es {Cancel the defined properties} {Cancelar las propiedades definidas}
::msgcat::mcset es {The property name can not be empty} {El nombre de propiedad no puede ser vacío}
::msgcat::mcset es {This name property it is already assigned.} {Este nombre de propiedad ya está asignado.}
::msgcat::mcset es Group: Grupo:
::msgcat::mcset es {Confirm values} {Confirmar valores}
::msgcat::mcset es {This property name already exist.} {El nombre de propiedad ya existe.}
::msgcat::mcset es {Add a new function} {Añadir nueva función}
::msgcat::mcset es {Delete the selected function} {Borrar la función seleccionada}
::msgcat::mcset es Apply Aplicar
::msgcat::mcset es {Assign the selection function and close editor} {Assign the selection function and close editor}
::msgcat::mcset es {Please, select the function you want to assign to '%s'.} {Please, select the function you want to assign to '%s'.}
::msgcat::mcset es {Function Id} {Function Id}
::msgcat::mcset es {Function definition} {Function definition}
::msgcat::mcset es Root Raíz
::msgcat::mcset es {Name id:} {Name id:}
::msgcat::mcset es {Kratos variables} {Variables Kratos}
::msgcat::mcset es {Add variable} {Añadir variable}
::msgcat::mcset es {Add this function} {Añadir esta función}
::msgcat::mcset es {Please, choose a non-empty ID.'} {Por favor, elija un ID que no esté vacío.}
::msgcat::mcset es {No function selected to remove.} {No hay función seleccionada para eliminar.}
::msgcat::mcset es {This function is assigned %s time%s in this project,
do you want to unassign %s and continue?} {Esta función se ha asignadod %s veces %s en este proyecto 
 ¿Desea cancelar la desasignación de %s y continuar?}
::msgcat::mcset es {The new group '%s' has not any usefull entity assigned.} {El nuevo grupo '%s' no tiene ningun entdad asignadaº}
::msgcat::mcset es {You have to choose one group
 (you can create a new one pushing the button on the right)} {Tiene que elegir un grupo (se puede crear uno con el botón de la izquierda)}
::msgcat::mcset es {This group it is already assigned to this condition.} {Este grupo ya esta asignado a esta condición.}
::msgcat::mcset es {You must define a Property before!} {Antes debe definir una propiedad.}
::msgcat::mcset es {You must define a Property before.} {Antes debe definir una propiedad.}
::msgcat::mcset es Model Modelo
::msgcat::mcset es Materials Materiales
::msgcat::mcset es {Project properties} {Propiedades de proyecto}
::msgcat::mcset es {Double-click toggle window or inline visualization} {Doble clic cambia entre ventana o visualización en línea}
::msgcat::mcset es {Double click here to tear off the window} {Haga doble clic aquí para hacer exterior la ventana}
::msgcat::mcset es {Double click here to integrate the window} {Haga doble clic aquí para integrar la ventana}
::msgcat::mcset es {Create new material} {Crear nuevo material}
::msgcat::mcset es {Delete material} {Borrar material}
::msgcat::mcset es {Refresh Tree} {Refrescar árbol}
::msgcat::mcset es {No materials group selected} {No se ha seleccionado un grupo de material}
::msgcat::mcset es {Bad material name, start or end by '//' is not allowed} {Nombre de material incorrecto, no puede empezar o acabar en "//"}
::msgcat::mcset es {New Material} {Nuevo material}
::msgcat::mcset es {Delete Material} {Borrar material}
::msgcat::mcset es {Rename material} {Renombrar material}
::msgcat::mcset es {Copy material} {Copiar material}
::msgcat::mcset es {Collapse All} {Colapsar todos}
::msgcat::mcset es {Expand All} {Expandir todos}
::msgcat::mcset es {Root folder can't be edited} {La carpeta raíz no puede editarse}
::msgcat::mcset es {Click Ok or Cancel in the bottom frame before selecting a new item} {Haga click en Ok o en Cancelar en la parte baja de la ventana antes de seleccionar otra entrada}
::msgcat::mcset es {You must define a valid Property for this element type.} {Debe definir una propiedad válida para este tipo de elemento}
::msgcat::mcset es New Nuevo
::msgcat::mcset es Delete Eliminar
::msgcat::mcset es Edit Editar
::msgcat::mcset es {Draw Entities} {Dibujar entidades}
::msgcat::mcset es {List Entities} {Listar Entidades}
::msgcat::mcset es {List Subtree} {Listar Sub-árbol}
::msgcat::mcset es {This property it is assigned to %s groups.
Do you want to delete the property and all this groups?} {Esta propiedad esta asignada a %s.
Desea borrar la propiedad y todos sus grupos?}
::msgcat::mcset es {Group Id} {Grupo id}
::msgcat::mcset es {View group entities} {Ver las entidades del Grupo}
::msgcat::mcset es {Press 'Finish' to stop the entities selection} {Pulse 'Finalizar' para parar la selección de entidades}
::msgcat::mcset es {Note: This action will affect all the Project Properties} {Nota: esto afectará a todas las Propiedades del Proyecto}
::msgcat::mcset es {You can't use some reservate chars like} {No se pueden usar caracteres reservados como}
::msgcat::mcset es {You can not choose an empty group name} {No debe escoger un nombre de grupo vacío}
::msgcat::mcset es {Rename Error Window} {Cambiar el nombre de la ventana de error}
::msgcat::mcset es {Please choose a new name} {Escoja un nuevo nombre}
::msgcat::mcset es {Choose a valid name} {Escoja un nombre válido}
::msgcat::mcset es Young_Modulus {Módulo de Young}
::msgcat::mcset es Poisson_Ratio {Coeficiente de Poisson}
::msgcat::mcset es {There are properties assigned to %s, do you want to %s it?
 %s} {Hay propiedades asignadas a %s, ¿seguro que quiere %s?
 %s}
::msgcat::mcset es {Cannot run the simulation. This version of the problem type does not support quadrilateral elements.} {No se puede ejecutar la simulación. Esta versión del tipo de problema no soporta elementos cuadriláteros}
::msgcat::mcset es {Open the GiD editor} {Abrir el editor de GiD}
::msgcat::mcset es tests tests
::msgcat::mcset es {No material selected} {No se ha seleccionado material}
::msgcat::mcset es {New Group#C#layer} {Nuevo Grupo}
::msgcat::mcset es {Apply this attribute to a Group containing Surfaces or Triangles of  Mesh. It will work as a wall which cannot be crossed by the DEM Elements} {Asigne este atributo a un Grupo que contenga Superficies o Triangulos de la Malla. Actuará como una pared que no puede ser atravesada por los Elementos DEM}
